src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ApeMaterno__c</fullName>
        <description>Apellido Materno de la cuenta</description>
        <label>Apellido Materno</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EstadoOtro__c</fullName>
        <label>Estado</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Estado__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Estado</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Ubicacion__c.TipoUbicacion__c</field>
                <operation>equals</operation>
                <value>Estado</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Ubicacion__c</referenceTo>
        <relationshipLabel>Cuentas</relationshipLabel>
        <relationshipName>Cuenta</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Municipio__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Municipio</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Ubicacion__c.TipoUbicacion__c</field>
                <operation>equals</operation>
                <value>Municipio</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Ubicacion__c</referenceTo>
        <relationshipLabel>Cuentas (Municipio)</relationshipLabel>
        <relationshipName>Cuentas2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pais__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pais</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Ubicacion__c.TipoUbicacion__c</field>
                <operation>equals</operation>
                <value>País</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Ubicacion__c</referenceTo>
        <relationshipLabel>Cuentas (Pais)</relationshipLabel>
        <relationshipName>Cuentas1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Catalogo__c.object
<CustomObject>
    <fields>
        <fullName>Descripcion__c</fullName>
        <label>Descripción</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>IdProfesion__c</fullName>
        <label>IdProfesión</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NombreCampoCandidato__c</fullName>
        <description>Captura del nombre del campo relacionado al concepto de pago en candidato</description>
        <label>Nombre campo candidato</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Orden__c</fullName>
        <description>Aplica para Nivel</description>
        <label>Orden</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TipoCatalogo__c</fullName>
        <label>Tipo catálogo</label>
        <picklist>
            <picklistValues>
                <fullName>Concepto Pagos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nivel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Modalidad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requisitos de Beca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turno</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Periodicidad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Profesión</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forma de pago</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banco</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Catálogo</label>
    <nameField>
        <label>Nombre de Catálogo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catálogos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Ubicacion__c.object
<CustomObject>
    <description>Listado que contiene: País, estados y municipios</description>
    <fields>
        <fullName>IdUbicacion__c</fullName>
        <label>Id</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Ubicación</label>
    <nameField>
        <label>Nombre de Ubicación</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ubicaciones</pluralLabel>
    <recordTypes>
        <fullName>Estado</fullName>
        <active>true</active>
        <label>Estado</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CTA_LayoutCtrl.cls
public class CTA_LayoutCtrl {
    
    public Account cuenta {get;set;}
    public Contact contacto {get;set;}
    public String idCuenta {get;set;}
    
    public Date fechaActual {get;set;}
    public List<SelectOption> profesiones {get;set;}
    
    //listas de selección, cargan de Ubicacion__c de forma dependiente. 
    //Se llenan de forma diferenciada listas y objetos, debido a las necesidades de búsqueda del objeto.
    public List<Ubicacion__c> listaPaises {get{return UtilsOferta.getPaises();}set;}
    public List<SelectOption> paises {get;set;}
    public List<Ubicacion__c> listaEstados {get;set;}
    public List<SelectOption> estados {get;set;}
    public List<SelectOption> municipios {get;set;}
    
    
    
    public CTA_LayoutCtrl(ApexPages.StandardController stdController){
        idCuenta = System.currentPagereference().getParameters().get('Id');
        System.debug('idCuenta NUEVO '+ idCuenta);
        
        if(idCuenta!=null){
            cuenta = (Account)Database.query('SELECT '+String.join(new List<String>(SObjectType.Account.Fields.getMap().keySet()), ', ')+' FROM Account WHERE Id =: idCuenta');
              System.debug('idCuenta NUEVO 2'+ cuenta.Id);
            contacto = [SELECT Id, FirstName, LastName FROM contact WHERE AccountId=:cuenta.Id LIMIT 1];
        }else{
            cuenta=new Account();
            contacto= new Contact();
        }
        inicializaObjetos();
    }
    
    private void inicializaObjetos(){
        fechaActual  = date.today();
        
        profesiones= new List<SelectOption>();
        profesiones.add(new SelectOption('','-- Seleccione una profesión --'));
        for(Catalogo__c prof: [SELECT Id, Name, TipoCatalogo__c, IdProfesion__c, Descripcion__c, NombreCampoCandidato__c, Orden__c FROM Catalogo__c WHERE IdProfesion__c!=null] ){
            profesiones.add(new SelectOption(prof.Id,prof.Name));
        }
        
        
        // CONDICIONES INICIALES PARA UBICACIÓN
        paises = new List<SelectOption>();
        paises.add(new SelectOption('','- Seleccione un país -'));
        
        for(Ubicacion__c country: listaPaises){
            paises.add(new SelectOption(country.Id,country.Name));
            if(country.Name=='MEXICO' && cuenta.Pais__c==null){
                cuenta.Pais__c=country.Id;
            }
        }
        System.debug(paises);
        System.debug(listaPaises);
        
        if(cuenta.Pais__c!=null){ getEstados(); }
        else{
            cuenta.Estado__c=cuenta.Municipio__c=null;
            estados = new List<SelectOption>();
            estados.add(new SelectOption('','- Debe seleccionar un país -'));
            listaEstados = new List<Ubicacion__c>();
            municipios = new List<SelectOption>();
            municipios.add(new SelectOption('','- Debe seleccionar un estado -'));
        }
        if(cuenta.Estado__c!=null){ getMunicipios(); }
        else{
            cuenta.Municipio__c=null;
            municipios = new List<SelectOption>();
            municipios.add(new SelectOption('','- Debe seleccionar un estado -'));
        }
    }
    
    
    /* MODULO DE UBICACIONES */
    public void getEstados(){
        Ubicacion__c paisActual = new Ubicacion__c();
        for(Ubicacion__c place: listaPaises){
            if(cuenta.Pais__c==place.Id){
                paisActual=place;
                break;
            }
        }
        listaEstados = UtilsOferta.getEstados(paisActual.IdUbicacion__c);
        estados = new List<SelectOption>();
        estados.add( new SelectOption('','- Seleccione un estado -') );
        for(Ubicacion__c state: listaEstados){
            estados.add(new SelectOption(state.Id,state.Name));
        }
        
        municipios = new List<SelectOption>();
        municipios.add(new SelectOption('','- Debe seleccionar un estado -'));
        if(estados.size()>1){
            cuenta.EstadoOtro__c=null;
            if(cuenta.Estado__c!=null){
                getMunicipios();
            }
        }else{
            cuenta.Estado__c=null;
            municipios = new List<SelectOption>();
            municipios.add(new SelectOption('','No disponible'));
        }
    }
    public void getMunicipios(){
        Ubicacion__c state = new Ubicacion__c();
        for(Ubicacion__c place: listaEstados){
            if(cuenta.Estado__c==place.Id){
                state=place;
                break;
            }
        }
        municipios = UtilsOferta.getMunicipios(state.IdUbicacion__c);
        
        
    }/* TERMINA DE OBTENER UBICACIONES */
    
    
    public void save(){
        try{
            String camposFaltantes='';
            if(cuenta.PersonEmail == null ){camposFaltantes+=' | Correo electrónico |'; }
            if(contacto.LastName == null ){camposFaltantes=camposFaltantes+' | Apellido paterno |'; }
            if(contacto.FirstName == null ){camposFaltantes=camposFaltantes+' | Nombre |'; }
            cuenta.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cuenta personal').getRecordTypeId();
            if(idCuenta == null){
                cuenta.LastName = contacto.LastName;
            }
            if(camposFaltantes!=''){
                PageMessagesController.addMessage(new PageMessagesController.PageMessage(PageMessagesController.Severity.ERROR, 'Se deben llenar todos los campos obligatorios:  '+camposFaltantes) );
                return;
            }else{
                upsert contacto;
                upsert cuenta;
            }
            
            PageMessagesController.addMessage(new PageMessagesController.PageMessage(PageMessagesController.Severity.CONFIRM, 'La información se guardo correctamente' ));
        }catch(Exception e){
            PageMessagesController.addMessage(new PageMessagesController.PageMessage(PageMessagesController.Severity.ERROR, 'CTA:   '+cuenta+'   Causa: '+e.getCause()+' '+cuenta.LastName+' '+cuenta.ApeMaterno__c+' '+ e.getMessage() + e.getLineNumber()));
        }
    }

}