src/objects/Beca__c.object
<CustomObject>
    <label>Beca</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Nombre de Beca</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Becas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Descuento__c.object
<CustomObject>
    <fields>
        <fullName>Estatus__c</fullName>
        <label>Estatus</label>
        <picklist>
            <picklistValues>
                <fullName>Activo</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactivo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rechazado</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Descuentos</relationshipLabel>
        <relationshipName>Descuentos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PorcentajeDescuento__c</fullName>
        <label>Porcentaje descuento</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Descuento</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Descuentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Beca__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Beca</label>
        <referenceTo>Beca__c</referenceTo>
        <relationshipLabel>Candidatos</relationshipLabel>
        <relationshipName>Candidatos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PorcentajeDescuento__c</fullName>
        <description>Porcentaje de descuento en inscripción</description>
        <label>% de descuento en inscripción</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/SolicitudBeca__c.object
<CustomObject>
    <fields>
        <fullName>Beca__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Beca</label>
        <referenceTo>Beca__c</referenceTo>
        <relationshipLabel>Solicitudes de beca</relationshipLabel>
        <relationshipName>SolicitudesBeca</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Estatus__c</fullName>
        <label>Estatus</label>
        <picklist>
            <picklistValues>
                <fullName>Activo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactivo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rechazada</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Solicitudes de beca</relationshipLabel>
        <relationshipName>SolicitudesBeca</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Porcentaje__c</fullName>
        <label>Porcentaje</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Solicitud de beca</label>
    <nameField>
        <label>Nombre de Solicitud de beca</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solicitudes de beca</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DescuentosByLeadCtrl.cls
public with sharing class DescuentosByLeadCtrl {
    
    public List<Descuento__c> descuentos { set;}
    public List<SolicitudBeca__c> becas { set;}
    private	String Id_number;
    
    /**
    * @author:      Gerardo Martínez
    * @date:        24/06/2016
    * @description: Carga el id de un lead cuando se abre la visual force de detalles de un lead
    * @param:       ApexPages.StandardController
    * @return:      
    */
    
    public DescuentosByLeadCtrl(ApexPages.StandardController controller){
        Lead leadObj = (Lead)controller.getRecord();
        Id_number = leadObj.Id;
    }
   
    /**
    * @author:      Gerardo Martínez
    * @date:        24/06/2016
    * @description: Obtiene los descuentos asociados a un lead
    * @param:       
    * @return:      List<Descuento__c >
    */
    
    public List<Descuento__c > getDescuentos() {
        List<Descuento__c > results = [SELECT Id, Name, Estatus__c,CreatedDate,PorcentajeDescuento__c FROM Descuento__c Descuento WHERE Descuento.Lead__c =:Id_number];
        return results;
	}
    
  /**
    * @author:      Gerardo Martínez
    * @date:        24/06/2016
    * @description: Obtiene los descuentos asociados a un lead
    * @param:       
    * @return:      List<Descuento__c >
    */
    public List<SolicitudBeca__c> getBecas() {
        List<SolicitudBeca__c > results = [SELECT Id, Name, Estatus__c,CreatedDate,Porcentaje__c,Beca__c  FROM SolicitudBeca__c WHERE Lead__c =:Id_number];
        return results;
	}


}