src/objects/Beca__c.object
<CustomObject>
    <label>Beca</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Nombre de Beca</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Becas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Descuento__c.object
<CustomObject>
    <fields>
        <fullName>Estatus__c</fullName>
        <label>Estatus</label>
        <picklist>
            <picklistValues>
                <fullName>Activo</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactivo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rechazado</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Oportunidad__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Oportunidad</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Descuentos</relationshipLabel>
        <relationshipName>Descuentos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PorcentajeDescuento__c</fullName>
        <label>Porcentaje descuento</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Descuento</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Descuentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Beca__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Beca</label>
        <referenceTo>Beca__c</referenceTo>
        <relationshipLabel>Candidatos</relationshipLabel>
        <relationshipName>Candidatos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PorcentajeDescuento__c</fullName>
        <description>Porcentaje de descuento en inscripción</description>
        <label>% de descuento en inscripción</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Beca__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Beca</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Beca__c.TipoBeca__c</field>
                <operation>equals</operation>
                <valueField>$Source.TipoBeca__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Beca__c</referenceTo>
        <relationshipLabel>Oportunidades</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PorcentajeDescuento__c</fullName>
        <label>% de descuento en inscripción</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SolicitudBeca__c.object
<CustomObject>
    <fields>
        <fullName>Beca__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Beca</label>
        <referenceTo>Beca__c</referenceTo>
        <relationshipLabel>Solicitudes de beca</relationshipLabel>
        <relationshipName>SolicitudesBeca</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Estatus__c</fullName>
        <label>Estatus</label>
        <picklist>
            <picklistValues>
                <fullName>Activo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactivo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rechazada</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Oportunidad__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Oportunidad</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Solicitudes de beca</relationshipLabel>
        <relationshipName>SolicitudesBeca</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Porcentaje__c</fullName>
        <label>Porcentaje</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Solicitud de beca</label>
    <nameField>
        <label>Nombre de Solicitud de beca</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solicitudes de beca</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DescuentosByOpportunityCtrl.cls
public with sharing class DescuentosByOpportunityCtrl {
   
    public List<Descuento__c > descuentos { set;}
    public List<SolicitudBeca__c> becas { set;}
    private	String Id_number;
    
  /**
    * @author:      Gerardo Martínez
    * @date:        27/06/2016
    * @description: Carga el id de un lead cuando se abre la visual force de detalles de un lead
    * @param:       ApexPages.StandardController
    * @return:      
    */
    
    public DescuentosByOpportunityCtrl(ApexPages.StandardController ctrl){
        Opportunity oppObj = (Opportunity)ctrl.getRecord();
        Id_number = oppObj.Id;
    }
    
  	/**
    * @author:      Gerardo Martínez
    * @date:        27/06/2016
    * @description: Obtiene los descuentos asociados a una Opportunity
    * @param:       
    * @return:      List<Descuento__c >
    */
    
    public List<Descuento__c > getDescuentos() {
        List<Descuento__c > results = [SELECT Id, Name, Estatus__c,CreatedDate,PorcentajeDescuento__c FROM Descuento__c Descuento WHERE Descuento.Oportunidad__c  =:Id_number];
        return results;
	}
    
    /**
    * @author:      Gerardo Martínez
    * @date:        24/06/2016
    * @description: Obtiene los descuentos asociados a un lead
    * @param:       
    * @return:      List<Descuento__c >
    */
    public List<SolicitudBeca__c> getBecas() {
        List<SolicitudBeca__c > results = [SELECT Id, Name, Estatus__c,CreatedDate,Porcentaje__c,Beca__c  FROM SolicitudBeca__c solicitudBeca WHERE solicitudBeca.Oportunidad__c =:Id_number];
        return results;
	}


}