src/objects/Beca__c.object
<CustomObject>
    <fields>
        <fullName>BecaPromocion__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Beca promoción</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Beneficiados__c</fullName>
        <description>Se usa para indicar quienes pueden ser los beneficiarios de esa beca.</description>
        <label>Beneficiados</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CantidadInscritos__c</fullName>
        <label>Cantidad de inscritos</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Beca</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Nombre de Beca</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Becas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ConfiguracionObjetoCambio__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Objeto para determinar los objetos a los cuales se les necesita dar un rastreo en el cambio de de sus campos, en los procesos Batch</description>
    <fields>
        <fullName>Campo__c</fullName>
        <description>Nombre API del campo</description>
        <label>Campo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Configuración objeto cambio</label>
</CustomObject>

src/classes/TriggerBecaHandlerTest.cls
@IsTest  public class TriggerBecaHandlerTest {
    @IsTest   public static void  TriggerBecaHandler(){
        
        Test.startTest();
        
        Beca__c bec = new Beca__c(BecaPromocion__c=true,
                                  Beneficiados__c ='EMPLEADOS O PERSONAL ADSCRITO', 
                                  CantidadInscritos__c =10
                                 );
        insert bec;
      
        ConfiguracionObjetoCambio__c ob = new ConfiguracionObjetoCambio__c(
            Name='Beca__c',
            Campo__c='Beca__c'
        );
        
        insert ob;
        
        TriggerBecaHandler obj = new TriggerBecaHandler();
        obj.afterUpdate();
        Test.stopTest();
        
    }
}