src/objects/BecaConvenioAsignacion__c.object
<CustomObject>
    <description>Relaciona los registros de beca convenio con diferentes planteles, niveles y programas</description>
    <fields>
        <fullName>Descuento__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Descuento</label>
        <referenceTo>Descuento__c</referenceTo>
        <relationshipName>Becas_Convenio_Asignaci_n</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ModalidadTodas__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Modalidad Todas</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Modalidad__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Modalidad</label>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipName>Becas_Convenio_Asignaci_n1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NivelTodos__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Nivel Todos</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Nivel</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Nivel</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipName>Becas_Convenio_Asignaci_n</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Periodo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Periodo</label>
        <referenceTo>Periodo__c</referenceTo>
        <relationshipName>Becas_Convenio_Asignaci_n</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PeriodosTodos__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Todos los periodos</description>
        <label>Periodos Todos</label>
        <type>Checkbox</type>
    </fields>
    <label>Asignación Beca Convenio/Descuento</label>
    <nameField>
        <label>Asignación</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asignaciones Beca Convenio/Descuento</pluralLabel>
    <recordTypes>
        <fullName>Descuento</fullName>
        <active>true</active>
        <label>Descuento</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Descuento__c.object
<CustomObject>
    <fields>
        <fullName>Comentarios__c</fullName>
        <label>Comentarios</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>DescuentoFinal__c</fullName>
        <label>Descuento final</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>DescuentoInicial__c</fullName>
        <label>Descuento inicial</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Estatus__c</fullName>
        <label>Estatus</label>
        <picklist>
            <picklistValues>
                <fullName>Activo</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactivo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rechazado</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FechaFinVigencia__c</fullName>
        <label>Fecha fin vigencia</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FechaInicioVigencia__c</fullName>
        <label>Fecha inicio vigencia</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Descuentos</relationshipLabel>
        <relationshipName>Descuentos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Modalidad__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Modalidad</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Modalidad</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Descuentos (Modalidad)</relationshipLabel>
        <relationshipName>Descuentos1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Modalidades__c</fullName>
        <label>Modalidades</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Nivel</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Nivel</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Descuentos</relationshipLabel>
        <relationshipName>Descuentos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Niveles__c</fullName>
        <label>Niveles</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Oportunidad__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Oportunidad</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Descuentos</relationshipLabel>
        <relationshipName>Descuentos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Periodo__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Periodo</label>
        <referenceTo>Periodo__c</referenceTo>
        <relationshipLabel>Descuentos</relationshipLabel>
        <relationshipName>Descuentos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Periodos__c</fullName>
        <label>Periodos</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PorcentajeDescuento__c</fullName>
        <label>Porcentaje descuento</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>TipoDescuento__c</fullName>
        <label>Tipo descuento</label>
        <picklist>
            <picklistValues>
                <fullName>Descuento individual vigente</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Promoción 0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Promoción Solicitada</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vigente__c</fullName>
        <formula>AND( FechaInicioVigencia__c &lt;= TODAY() , FechaFinVigencia__c &gt;= TODAY())</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vigente</label>
        <type>Checkbox</type>
    </fields>
    <label>Descuento</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Descuentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>AplicaPromocionCero__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Aplica promoción cero</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Modalidad__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Modalidad</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Modalidad</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Candidatos (Modalidad)</relationshipLabel>
        <relationshipName>Candidatos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Nivel</description>
        <label>Nivel</label>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Candidatos (Nivel)</relationshipLabel>
        <relationshipName>Nivel</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Periodo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Periodo</description>
        <label>Periodo</label>
        <referenceTo>Periodo__c</referenceTo>
        <relationshipLabel>Periodo</relationshipLabel>
        <relationshipName>Periodo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PorcentajeDescuento__c</fullName>
        <description>Porcentaje de descuento en inscripción</description>
        <label>% de descuento en inscripción</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SolicitudPromocion__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Solicitud de promoción</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>VigenciaDescuento__c</fullName>
        <label>Vigencia de descuento</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>AplicaPromocionCero__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Aplica promoción cero</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Modalidad__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Modalidad</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Modalidad</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Oportunidades</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Nivel</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Nivel</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Oportunidades (Nivel)</relationshipLabel>
        <relationshipName>Oportunidades1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Periodo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Periodo</label>
        <referenceTo>Periodo__c</referenceTo>
        <relationshipLabel>Oportunidades</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PorcentajeDescuento__c</fullName>
        <label>% de descuento en inscripción</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SolicitudPromocion__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Solicitud de promoción</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>VigenciaDescuento__c</fullName>
        <label>VigenciaDescuento</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Periodo__c.object
<CustomObject>
    <label>Periodo</label>
    <nameField>
        <label>Periodo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Periodos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TriggerDescuentoHandler.cls
public with sharing class TriggerDescuentoHandler extends TriggerHandler{
    /**
* @author:      Daniel Hernández
* @date:        07/06/2016
* @description: Valida que no se empalmen fechas en registros del objeto   coincidentes en Modalidad__c, Periodo__c y Nivel__c en el mismo periodo del tipo 'Descuento Individual vigente'
* @param:       
* @return:      
*/
    
    private Map<Id, Descuento__c> newMap;
    private Map<Id, Descuento__c> oldMap;
    private List<Descuento__c> newList;
    private List<Descuento__c> oldList;
    
    public List<Descuento__c> listaComparativa;
    
    public TriggerDescuentoHandler() {
        this.newMap = (Map<Id, Descuento__c>) trigger.newMap;
        this.oldMap = (Map<Id, Descuento__c>) trigger.oldMap;
        this.newList = (List<Descuento__c>) trigger.new;
        this.oldList = (List<Descuento__c>) trigger.old;
        
        listaComparativa = new List<Descuento__c>();
        try{
            listaComparativa = [SELECT Id,Name,Estatus__c,Comentarios__c,Lead__c,Modalidad__c,Modalidades__c,Nivel__c,Niveles__c,Periodo__c,Periodos__c,
                                DescuentoFinal__c,DescuentoInicial__c,FechaFinVigencia__c,FechaInicioVigencia__c,PorcentajeDescuento__c,TipoDescuento__c,Vigente__c 
                                FROM Descuento__c 
                                WHERE (TipoDescuento__c='Descuento individual vigente' OR TipoDescuento__c='Promoción 0')
                                AND Estatus__c='Activo'
                                LIMIT 100];
        }catch(Exception e){}
    }
    
    public override void beforeInsert(){
        for(Descuento__c disc : newList){
            if( listaComparativa.size()>0 && disc.Estatus__c=='Activo' && (disc.TipoDescuento__c=='Descuento individual vigente' || disc.TipoDescuento__c=='Promoción 0' ) ){
                validacionEmpalmeFecha(disc);
            }
        }
    }
    
    public override void afterInsert(){
        for(Descuento__c disc : newList){
            if(disc.TipoDescuento__c=='Promoción Solicitada' && disc.Lead__c!=null){
                actualizaPromocionLead(disc);
            }else if(disc.TipoDescuento__c=='Promoción Solicitada' && disc.Oportunidad__c!=null){
                actualizaPromocionOportunidad(disc);
            }
        }
    }
    
    
    public override void beforeUpdate(){
        for(Descuento__c disc : newList){
            if( listaComparativa.size()>0 && disc.Estatus__c=='Activo' && (disc.TipoDescuento__c=='Descuento individual vigente' || disc.TipoDescuento__c=='Promoción 0' ) ){
                validacionEmpalmeFecha(disc);
            }
        }
    }
    
    public override void afterUpdate(){
        for(Descuento__c disc : newList){
            if(disc.TipoDescuento__c=='Promoción Solicitada' && disc.Lead__c!=null){
                actualizaPromocionLead(disc);
            }else if(disc.TipoDescuento__c=='Promoción Solicitada' && disc.Oportunidad__c!=null){
                actualizaPromocionOportunidad(disc);
            }
        }
    }
    
    
    
    
    
    public void validacionEmpalmeFecha(Descuento__c disc){
        for(Descuento__c descuentoExistente: listaComparativa){
            if(disc.TipoDescuento__c == descuentoExistente.TipoDescuento__c){
                if( ( (disc.FechaInicioVigencia__c>=descuentoExistente.FechaInicioVigencia__c 	&& disc.FechaFinVigencia__c<=descuentoExistente.FechaFinVigencia__c) 	||
                     (descuentoExistente.FechaFinVigencia__c>=disc.FechaInicioVigencia__c 	&& descuentoExistente.FechaFinVigencia__c<=disc.FechaFinVigencia__c) 	||
                     (descuentoExistente.FechaInicioVigencia__c>=disc.FechaInicioVigencia__c 	&& descuentoExistente.FechaInicioVigencia__c<=disc.FechaFinVigencia__c) 
                    )&& descuentoExistente.Id !=disc.Id
                  ){
                      disc.addError('No pueden existir dos descuentos de este tipo, activos en un mismo lapso de tiempo');
                  }
            }
        }
    }
    
    public void actualizaPromocionLead(Descuento__c disc){
        Lead candidato = new Lead();
        
        try{
            candidato = [SELECT Id, Name, SolicitudPromocion__c, VigenciaDescuento__c, AplicaPromocionCero__c, IsConverted, PorcentajeDescuento__c, Nivel__c, Modalidad__c, Periodo__c
                         FROM Lead 
                         WHERE Id=:disc.Lead__c LIMIT 1];
        }catch(Exception e){}
        
        
        if(!candidato.IsConverted){
            
            if(candidato.Id!=null && candidato.AplicaPromocionCero__c==false){
                
                if(disc.Estatus__c=='Activo'){
                    candidato.PorcentajeDescuento__c = disc.PorcentajeDescuento__c;
                    candidato.SolicitudPromocion__c=true;
                    candidato.VigenciaDescuento__c = disc.FechaFinVigencia__c;
                }else{
                    BecaConvenioAsignacion__c descuentoAplicable = new BecaConvenioAsignacion__c();
                    try{
                        descuentoAplicable = [SELECT Id, Name, RecordType.Name, Periodo__c, Nivel__c, Modalidad__c, NivelTodos__c, ModalidadTodas__c, Descuento__r.Vigente__c,
                                              Descuento__r.FechaInicioVigencia__c, Descuento__r.FechaFinVigencia__c, Descuento__r.PorcentajeDescuento__c, Descuento__r.Estatus__c 
                                              FROM BecaConvenioAsignacion__C 
                                              WHERE RecordType.Name='Descuento' AND Descuento__r.Vigente__c=true AND Descuento__r.Estatus__c='Activo'
                                              
                                              AND (//Todas las opciones devueltas deben corresponder a un sólo padre Descuento__c, por tanto tienen el mismo porcentajeDescuento
                                                  (NivelTodos__c=true AND ModalidadTodas__c=true AND PeriodosTodos__c=true)
                                                  
                                                  OR (Nivel__c=:candidato.Nivel__c AND ModalidadTodas__c=true AND PeriodosTodos__c=true) 
                                                  OR (NivelTodos__c=true AND Modalidad__c=:candidato.Modalidad__c AND PeriodosTodos__c=true) 
                                                  OR (NivelTodos__c=true AND ModalidadTodas__c=true AND Periodo__c=:candidato.Periodo__c)
                                                  
                                                  OR(Nivel__c=:candidato.Nivel__c AND Modalidad__c=:candidato.Modalidad__c AND PeriodosTodos__c=true) 
                                                  OR(Nivel__c=:candidato.Nivel__c AND ModalidadTodas__c=true AND Periodo__c=:candidato.Periodo__c) 
                                                  OR(NivelTodos__c=true AND Modalidad__c=:candidato.Modalidad__c AND Periodo__c=:candidato.Periodo__c) 
                                                  
                                                  OR(Nivel__c=:candidato.Nivel__c AND Modalidad__c=:candidato.Modalidad__c AND Periodo__c=:candidato.Periodo__c)
                                              )
                                              LIMIT 1];
                        candidato.PorcentajeDescuento__c = descuentoAplicable.Descuento__r.PorcentajeDescuento__c;
                        candidato.VigenciaDescuento__c  = descuentoAplicable.Descuento__r.FechaFinVigencia__c;
                    }catch(Exception e){
                        candidato.PorcentajeDescuento__c = 0;
                    }
                    candidato.SolicitudPromocion__c=false;
                }
                upsert candidato;
            }
        }
    }
    
    
    
    public void actualizaPromocionOportunidad(Descuento__c disc){
        Opportunity oportunidad = new Opportunity();
        
        try{
            oportunidad = [SELECT Id, Name, PorcentajeDescuento__c, VigenciaDescuento__c, SolicitudPromocion__c, AplicaPromocionCero__c, Nivel__c, Modalidad__c, Periodo__c
                         FROM Opportunity 
                         WHERE Id=:disc.Oportunidad__c LIMIT 1];
        }catch(Exception e){}
        
        if(oportunidad.Id!=null && oportunidad.AplicaPromocionCero__c==false){
            
            if(disc.Estatus__c=='Activo'){
                oportunidad.PorcentajeDescuento__c = disc.PorcentajeDescuento__c;
                oportunidad.SolicitudPromocion__c=true;
                oportunidad.VigenciaDescuento__c = disc.FechaFinVigencia__c;
            }else{
                BecaConvenioAsignacion__c descuentoAplicable = new BecaConvenioAsignacion__c();
                try{
                    descuentoAplicable = [SELECT Id, Name, RecordType.Name, Periodo__c, Nivel__c, Modalidad__c, NivelTodos__c, ModalidadTodas__c, Descuento__r.Vigente__c,
                                          Descuento__r.FechaInicioVigencia__c, Descuento__r.FechaFinVigencia__c, Descuento__r.PorcentajeDescuento__c, Descuento__r.Estatus__c 
                                          FROM BecaConvenioAsignacion__C 
                                          WHERE RecordType.Name='Descuento' AND Descuento__r.Vigente__c=true AND Descuento__r.Estatus__c='Activo'
                                          
                                          AND (//Todas las opciones devueltas deben corresponder a un sólo padre Descuento__c, por tanto tienen el mismo porcentajeDescuento
                                              (NivelTodos__c=true AND ModalidadTodas__c=true AND PeriodosTodos__c=true)
                                              
                                              OR (Nivel__c=:oportunidad.Nivel__c AND ModalidadTodas__c=true AND PeriodosTodos__c=true) 
                                              OR (NivelTodos__c=true AND Modalidad__c=:oportunidad.Modalidad__c AND PeriodosTodos__c=true) 
                                              OR (NivelTodos__c=true AND ModalidadTodas__c=true AND Periodo__c=:oportunidad.Periodo__c)
                                              
                                              OR(Nivel__c=:oportunidad.Nivel__c AND Modalidad__c=:oportunidad.Modalidad__c AND PeriodosTodos__c=true) 
                                              OR(Nivel__c=:oportunidad.Nivel__c AND ModalidadTodas__c=true AND Periodo__c=:oportunidad.Periodo__c) 
                                              OR(NivelTodos__c=true AND Modalidad__c=:oportunidad.Modalidad__c AND Periodo__c=:oportunidad.Periodo__c) 
                                              
                                              OR(Nivel__c=:oportunidad.Nivel__c AND Modalidad__c=:oportunidad.Modalidad__c AND Periodo__c=:oportunidad.Periodo__c)
                                          )
                                          LIMIT 1];
                    oportunidad.PorcentajeDescuento__c = descuentoAplicable.Descuento__r.PorcentajeDescuento__c;
                    oportunidad.VigenciaDescuento__c  = descuentoAplicable.Descuento__r.FechaFinVigencia__c;
                }catch(Exception e){
                    oportunidad.PorcentajeDescuento__c = 0;
                }
                oportunidad.SolicitudPromocion__c=false;
            }
            upsert oportunidad;
        }
    }
    
}