src/objects/Beca__c.object
<CustomObject>
    <fields>
        <fullName>BecaPromocion__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Beca promoción</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Beneficiados__c</fullName>
        <description>Se usa para indicar quienes pueden ser los beneficiarios de esa beca.</description>
        <label>Beneficiados</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CantidadInscritos__c</fullName>
        <label>Cantidad de inscritos</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Beca</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Nombre de Beca</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Becas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ConfiguracionObjetoCambio__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Objeto para determinar los objetos a los cuales se les necesita dar un rastreo en el cambio de de sus campos, en los procesos Batch</description>
    <fields>
        <fullName>Campo__c</fullName>
        <description>Nombre API del campo</description>
        <label>Campo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Configuración objeto cambio</label>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>AsignacionAutomatica__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Asignación Automática del Prospecto</description>
        <label>Asignación automática</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Beca__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Beca</label>
        <referenceTo>Beca__c</referenceTo>
        <relationshipLabel>Candidatos</relationshipLabel>
        <relationshipName>Candidatos</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Negocio__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuraciones  globales</description>
    <label>Negocio</label>
</CustomObject>

src/classes/TriggerCandidatoHandlerTest.cls
@IsTest public class TriggerCandidatoHandlerTest {
    @IsTest   public static void  TriggerCandidatoHandlerTest(){
        
          Test.startTest();
        
    /*    Beca__c bec = new Beca__c(BecaPromocion__c=true,
                                  Beneficiados__c ='EMPLEADOS O PERSONAL ADSCRITO', 
                                  CantidadInscritos__c =10
                                 );
        insert bec;
      
        ConfiguracionObjetoCambio__c ob = new ConfiguracionObjetoCambio__c(
            Name='Beca__c',
            Campo__c='Beca__c'
        );
        
        insert ob;*/
        Negocio__c negocio = new Negocio__c(
        );
        insert negocio;
        Lead lead = new Lead( LastName='demo',
                             AsignacionAutomatica__c=true
                             
        
        );
        
        insert lead;
        TriggerCandidatoHandler obj = new TriggerCandidatoHandler();
        obj.afterInsert();
        Test.stopTest();
        
        
    }

}