src/objects/Beca__c.object
<CustomObject>
    <fields>
        <fullName>BecaPromocion__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Beca promoción</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Beneficiados__c</fullName>
        <description>Se usa para indicar quienes pueden ser los beneficiarios de esa beca.</description>
        <label>Beneficiados</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CantidadInscritos__c</fullName>
        <label>Cantidad de inscritos</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <label>Nivel</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OfertaEducativa__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Oferta Educativa</label>
        <referenceTo>OfertaEducativa__c</referenceTo>
        <relationshipLabel>Becas</relationshipLabel>
        <relationshipName>Becas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Periodo__c</fullName>
        <formula>OfertaEducativa__r.Periodo__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Periodo</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <label>Plantel</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Programa__c</fullName>
        <label>Programa</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Beca</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Nombre de Beca</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Becas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BecaConvenioAsignacion__c.object
<CustomObject>
    <description>Relaciona los registros de beca convenio con diferentes planteles, niveles y programas</description>
    <fields>
        <fullName>Modalidad__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Modalidad</label>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipName>Becas_Convenio_Asignaci_n1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Periodo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Periodo</label>
        <referenceTo>Periodo__c</referenceTo>
        <relationshipName>Becas_Convenio_Asignaci_n</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipName>Becas_Convenio_Asignaci_n</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Programa__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programa</label>
        <referenceTo>Programa__c</referenceTo>
        <relationshipName>Becas_Convenio_Asignaci_n</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Asignación Beca Convenio/Descuento</label>
    <nameField>
        <label>Asignación</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asignaciones Beca Convenio/Descuento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Catalogo__c.object
<CustomObject>
    <fields>
        <fullName>Abreviatura__c</fullName>
        <label>Abreviatura</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TipoCatalogo__c</fullName>
        <label>Tipo catálogo</label>
        <picklist>
            <picklistValues>
                <fullName>Concepto Pagos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nivel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Modalidad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requisitos de Beca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turno</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Periodicidad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Profesión</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forma de pago</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banco</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Catálogo</label>
    <nameField>
        <label>Nombre de Catálogo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catálogos</pluralLabel>
    <recordTypes>
        <fullName>Modalidad</fullName>
        <active>true</active>
        <description>Crear nuevo registro del tipo Modalidad</description>
        <label>Modalidad</label>
    </recordTypes>
    <recordTypes>
        <fullName>Nivel</fullName>
        <active>true</active>
        <description>Crear nuevo registro del tipo Nivel</description>
        <label>Nivel</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Negocio__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuraciones  globales</description>
    <fields>
        <fullName>Folio__c</fullName>
        <description>Número de folio consecutivo para candidatos y prospéctos</description>
        <inlineHelpText>Número de folio consecutivo para candidatos y prospéctos</inlineHelpText>
        <label>Folio</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MaximoGrupoOnline__c</fullName>
        <defaultValue>20</defaultValue>
        <description>Número de veces que permite el cupo de un grupo Online</description>
        <inlineHelpText>Número de veces que permite el cupo de un grupo Online</inlineHelpText>
        <label>Máximo grupo online</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MaximoGrupo__c</fullName>
        <defaultValue>10</defaultValue>
        <description>Número de veces que permite el cupo de un grupo Presencial o Ejecutiva</description>
        <inlineHelpText>Número de veces que permite el cupo de un grupo Presencial o Ejecutiva</inlineHelpText>
        <label>Máximo grupo</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Negocio</label>
</CustomObject>

src/objects/OfertaEducativa__c.object
<CustomObject>
    <fields>
        <fullName>Beca__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Beca</label>
        <referenceTo>Beca__c</referenceTo>
        <relationshipLabel>Ofertas Educativas</relationshipLabel>
        <relationshipName>OfertasEducativas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Modalidad__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Modalidad</inlineHelpText>
        <label>Modalidad</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Modalidad</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Ofertas Educativas</relationshipLabel>
        <relationshipName>Ofertas_Educativas</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Periodo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Periodo</label>
        <referenceTo>Periodo__c</referenceTo>
        <relationshipLabel>Ofertas Educativas</relationshipLabel>
        <relationshipName>Ofertas_Educativas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Plantel</inlineHelpText>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Ofertas Educativas</relationshipLabel>
        <relationshipName>Ofertas_Educativas</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Programa__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Programa</inlineHelpText>
        <label>Programa</label>
        <referenceTo>Programa__c</referenceTo>
        <relationshipLabel>Ofertas Educativas</relationshipLabel>
        <relationshipName>Ofertas_Educativas</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Oferta Educativa</label>
    <nameField>
        <displayFormat>OE-{0000000}</displayFormat>
        <label>Oferta Educativa</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ofertas Educativas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Periodo__c.object
<CustomObject>
    <fields>
        <fullName>ActivoPresencial__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activo presencial</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Activo__c</fullName>
        <label>Estatus</label>
        <picklist>
            <picklistValues>
                <fullName>Activo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactivo</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FechaFinReal__c</fullName>
        <label>Fecha fin real</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FechaFin__c</fullName>
        <label>Fecha fin programada</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FechaInicioReal__c</fullName>
        <label>Fecha inicio real</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FechaInicio__c</fullName>
        <label>Fecha inicio programada</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Periodo</label>
    <nameField>
        <label>Periodo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Periodos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Plantel__c.object
<CustomObject>
    <fields>
        <fullName>Abreviatura__c</fullName>
        <label>Abreviatura</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Calle__c</fullName>
        <label>Calle</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RazonSocial__c</fullName>
        <label>Razón social</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Plantel</label>
    <nameField>
        <label>Plantel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planteles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Programa__c.object
<CustomObject>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Programas</relationshipLabel>
        <relationshipName>Programas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Programa</label>
    <nameField>
        <label>Programa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Ubicacion__c.object
<CustomObject>
    <description>Listado que contiene: País, estados y municipios</description>
    <fields>
        <fullName>Abreviatura__c</fullName>
        <description>Aplica para estado</description>
        <externalId>true</externalId>
        <label>Abreviatura</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Cabecera__c</fullName>
        <description>Aplica para municipio</description>
        <label>Cabecera</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Capital__c</fullName>
        <label>Capital</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IdEstadoPais__c</fullName>
        <description>Aplica para municipio y estado</description>
        <label>Id Estado/País</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IdUbicacion__c</fullName>
        <label>Id</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TipoUbicacion__c</fullName>
        <label>Tipo</label>
        <picklist>
            <picklistValues>
                <fullName>Estado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>País</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Municipio</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Ubicación</label>
    <nameField>
        <label>Nombre de Ubicación</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ubicaciones</pluralLabel>
    <recordTypes>
        <fullName>Estado</fullName>
        <active>true</active>
        <label>Estado</label>
    </recordTypes>
    <recordTypes>
        <fullName>Municipio</fullName>
        <active>true</active>
        <label>Municipio</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UtilsExternalTest.cls
@IsTest public class UtilsExternalTest {
    
    @IsTest   public static void  UtilsExternalTest(){
        
        Negocio__c configuracionNegocio = Negocio__c.getOrgDefaults( );
        configuracionNegocio.MaximoGrupo__c=30;
        configuracionNegocio.MaximoGrupoOnline__c=50;
        upsert configuracionNegocio;
        Integer nextFolio = configuracionNegocio.Folio__c != null ? Integer.valueOf(configuracionNegocio.Folio__c) : 0;
        nextFolio = nextFolio + 1;
        date inicio = date.newInstance(2020, 1, 30);
        date fin = date.newInstance(2020, 2, 30);
        
        Periodo__c per = new Periodo__c(Name='agosto 2020',
                                        FechaInicio__c=inicio,
                                        FechaInicioReal__c=inicio,
                                        FechaFin__c =fin,
                                        FechaFinReal__c =fin,
                                        Activo__c='Activo',
                                        ActivoPresencial__c=true
                                       );
        insert per;
        
        Ubicacion__c ub = new Ubicacion__c(Name='MEXICO',
                                           IdUbicacion__c='157',
                                           TipoUbicacion__c='País'
                                          );
        insert ub;
        
        Ubicacion__c ubi = new Ubicacion__c(Name='D. F.',
                                            Abreviatura__c='DF',
                                            IdUbicacion__c='9',
                                            IdEstadoPais__c=ub.IdUbicacion__c,
                                            TipoUbicacion__c ='Estado'
                                           ); 
        insert ubi;
        
        Ubicacion__c mun = new Ubicacion__c(Name='San José de Gracia',
                                            Cabecera__c='San José de Gracia',
                                            Capital__c='0',
                                            IdUbicacion__c=ubi.IdUbicacion__c,
                                            IdEstadoPais__c=ub.IdUbicacion__c,
                                            TipoUbicacion__c ='Municipio'
                                           ); 
        insert mun;
        
        BecaConvenioAsignacion__c beca = new BecaConvenioAsignacion__c(Name='demo' );
        insert beca;
        
        Beca__c bec = new Beca__c(BecaPromocion__c=true,
                                  Beneficiados__c ='EMPLEADOS O PERSONAL ADSCRITO', 
                                  CantidadInscritos__c =10
                                 );
        
        Plantel__c plan = new Plantel__c (Calle__c='demo',
                                          RazonSocial__c='demo'
                                         );
        insert  plan;
        
        Catalogo__c cat = new Catalogo__c(Name='Online',
                                          TipoCatalogo__c='Modalidad');
        insert cat;
        
        Catalogo__c catn = new Catalogo__c(Name='Licenciatura',
                                           TipoCatalogo__c='Nivel');
        insert catn;
        
        Programa__c pr =new Programa__c(Name='INGENIERÍA EN SISTEMAS COMPUTACIONALES');
        insert pr;
        
        OfertaEducativa__c oe= new OfertaEducativa__c(Programa__c=pr.id,
                                                      Modalidad__c=cat.Id,
                                                      Nivel__c=catn.Id,
                                                      Plantel__c=plan.id,
                                                      Periodo__c=per.Id
                                                     );
        insert oe;
        
        UtilsExternal.ComboWrapper cw = new  UtilsExternal.ComboWrapper();
        
        cw=UtilsExternal.getExternalOfertaAcademica();
        
        Map<String, List<SObject>> ubicacion = new Map<String, List<SObject>>();
        ubicacion=UtilsExternal.getExternalUbicacion();
        
    }
}