src/objects/Beca__c.object
<CustomObject>
    <fields>
        <fullName>PorcentajeBeca__c</fullName>
        <label>% beca</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Beca</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Nombre de Beca</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Becas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BecaConvenioAsignacion__c.object
<CustomObject>
    <description>Relaciona los registros de beca convenio con diferentes planteles, niveles y programas</description>
    <fields>
        <fullName>PorcentajeBeca__c</fullName>
        <label>% beca</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Asignación Beca Convenio/Descuento</label>
    <nameField>
        <label>Asignación</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asignaciones Beca Convenio/Descuento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Beca__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Beca</label>
        <referenceTo>Beca__c</referenceTo>
        <relationshipLabel>Candidatos</relationshipLabel>
        <relationshipName>Candidatos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LetraBeca__c</fullName>
        <globalPicklist>CategoriaLetra</globalPicklist>
        <label>Letra de Beca</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PorcentajeBeca__c</fullName>
        <description>Porcentaje de descuento en colegiaturas</description>
        <inlineHelpText>Porcentaje de beca en colegiatura</inlineHelpText>
        <label>% de beca en colegiatura</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Beca__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Beca</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Beca__c.TipoBeca__c</field>
                <operation>equals</operation>
                <valueField>$Source.TipoBeca__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Beca__c</referenceTo>
        <relationshipLabel>Oportunidades</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LetraBeca__c</fullName>
        <globalPicklist>CategoriaLetra</globalPicklist>
        <label>Letra de Beca</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PorcentajeBeca__c</fullName>
        <label>% de beca en colegiatura</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SolicitudBeca__c.object
<CustomObject>
    <fields>
        <fullName>AsignacionBecaConvenio__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asignación Beca Convenio/Descuento</label>
        <referenceTo>BecaConvenioAsignacion__c</referenceTo>
        <relationshipLabel>Solicitudes de beca</relationshipLabel>
        <relationshipName>SolicitudesBeca</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Beca__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Beca</label>
        <referenceTo>Beca__c</referenceTo>
        <relationshipLabel>Solicitudes de beca</relationshipLabel>
        <relationshipName>SolicitudesBeca</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Estatus__c</fullName>
        <label>Estatus</label>
        <picklist>
            <picklistValues>
                <fullName>Activo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactivo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rechazada</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Solicitudes de beca</relationshipLabel>
        <relationshipName>SolicitudesBeca</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LetraBecaComercial__c</fullName>
        <label>Letra de Beca Comercial</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oportunidad__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Oportunidad</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Solicitudes de beca</relationshipLabel>
        <relationshipName>SolicitudesBeca</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Porcentaje__c</fullName>
        <label>Porcentaje</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Solicitud de beca</label>
    <nameField>
        <label>Nombre de Solicitud de beca</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solicitudes de beca</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TriggerSolicitudBecaHandler.cls
public with sharing class TriggerSolicitudBecaHandler extends TriggerHandler{
    /**
    * @author:      Daniel Hernández
    * @date:        27/06/2016
    * @description: Si el estatus de una Beca Solicitada cambia a "Activo" y esta seleccionado, el campo PorcentajeBeca__c en Lead u Opp se atualiza con el importe autotrizado.
    * @param:       
    * @return:      
    */
    
    private Map<Id, SolicitudBeca__c> newMap;
    private Map<Id, SolicitudBeca__c> oldMap;
    private List<SolicitudBeca__c> newList;
    private List<SolicitudBeca__c> oldList;
    
    public TriggerSolicitudBecaHandler() {
        this.newMap = (Map<Id, SolicitudBeca__c>) trigger.newMap;
        this.oldMap = (Map<Id, SolicitudBeca__c>) trigger.oldMap;
        this.newList = (List<SolicitudBeca__c>) trigger.new;
        this.oldList = (List<SolicitudBeca__c>) trigger.old;
    }
    
    public override void afterInsert(){
        for(SolicitudBeca__c nuevaSolicitud : newList){
            if( nuevaSolicitud.Oportunidad__c!=null){
                asignaPorcentajeOpp(nuevaSolicitud);
            }else if(nuevaSolicitud.Lead__c!=null){
                asignaPorcentajeLead(nuevaSolicitud);
            }
        }
    }
    
    public override void afterUpdate(){
        for(SolicitudBeca__c nuevaSolicitud : newList){
            if( nuevaSolicitud.Oportunidad__c!=null){
                asignaPorcentajeOpp(nuevaSolicitud);
            }else if(nuevaSolicitud.Lead__c!=null){
                asignaPorcentajeLead(nuevaSolicitud);
            }
        }
    }
    
    public override void beforeDelete(){
        for(SolicitudBeca__c nuevaSolicitud : oldList){
            if(nuevaSolicitud.Estatus__c=='Activo'){
                if(nuevaSolicitud.Oportunidad__c!=null){
                    try{
                        Opportunity oportunidad = [SELECT Id, Name, Beca__c, BecaConvenioAsignacion__c, PorcentajeBeca__c 
                                       FROM Opportunity 
                                       WHERE Id=:nuevaSolicitud.Oportunidad__c 
                                       AND Beca__c=:nuevaSolicitud.Beca__c 
                                       AND BecaConvenioAsignacion__c=:nuevaSolicitud.AsignacionBecaConvenio__c  
                                       LIMIT 1];
                        
                        oportunidad.PorcentajeBeca__c = 0;
                        oportunidad.LetraBeca__c = null;
                        upsert oportunidad;
                    }catch(Exception e){}
                }else if(nuevaSolicitud.Lead__c!=null){
                    try{
                        Lead candidato = [SELECT Id, Name, Beca__c, BecaConvenioAsignacion__c, PorcentajeBeca__c 
                                          FROM Lead 
                                          WHERE Id=:nuevaSolicitud.Lead__c 
                                          AND Beca__c=:nuevaSolicitud.Beca__c 
                                          AND BecaConvenioAsignacion__c=:nuevaSolicitud.AsignacionBecaConvenio__c  
                                          LIMIT 1];
                        
                        candidato.PorcentajeBeca__c = 0;
                        candidato.LetraBeca__c = null;
                        upsert candidato;
                        
                    }catch(Exception e){}
                }
            }
        }
    }
    
    
    public void asignaPorcentajeLead(SolicitudBeca__c nuevaSolicitud){
        
        try{
            Lead candidato = [SELECT Id, isConverted, Name, Beca__c, BecaConvenioAsignacion__c, PorcentajeBeca__c 
                              FROM Lead 
                              WHERE Id=:nuevaSolicitud.Lead__c 
                              AND Beca__c=:nuevaSolicitud.Beca__c 
                              AND BecaConvenioAsignacion__c=:nuevaSolicitud.AsignacionBecaConvenio__c  
                              LIMIT 1];
            
            if(!candidato.IsConverted){
                if(nuevaSolicitud.Estatus__c=='Activo'){
                    candidato.PorcentajeBeca__c = nuevaSolicitud.Porcentaje__c;
                    candidato.LetraBeca__c = nuevaSolicitud.LetraBecaComercial__c;
                    
                }else {
                    candidato.PorcentajeBeca__c = 0;
                    candidato.LetraBeca__c = null;
                }
                upsert candidato;
            }
        }catch(Exception e){}
        
    }
    
    
    public void asignaPorcentajeOpp(SolicitudBeca__c nuevaSolicitud){
        
        try{
            Opportunity oportunidad = [SELECT Id, Name, Beca__c, BecaConvenioAsignacion__c, PorcentajeBeca__c 
                                       FROM Opportunity 
                                       WHERE Id=:nuevaSolicitud.Oportunidad__c 
                                       AND Beca__c=:nuevaSolicitud.Beca__c 
                                       AND BecaConvenioAsignacion__c=:nuevaSolicitud.AsignacionBecaConvenio__c  
                                       LIMIT 1];
            
            if(nuevaSolicitud.Estatus__c=='Activo'){
                oportunidad.PorcentajeBeca__c = nuevaSolicitud.Porcentaje__c;
                oportunidad.LetraBeca__c = nuevaSolicitud.LetraBecaComercial__c;
            }else {
                oportunidad.PorcentajeBeca__c = 0;
                oportunidad.LetraBeca__c = null;
            }
            upsert oportunidad;
        }catch(Exception e){}
    }
    
    
}