src/objects/Catalogo__c.object
<CustomObject>
    <label>Catálogo</label>
    <nameField>
        <label>Nombre de Catálogo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catálogos</pluralLabel>
    <recordTypes>
        <fullName>Nivel</fullName>
        <active>true</active>
        <description>Crear nuevo registro del tipo Nivel</description>
        <label>Nivel</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FichaPago__c.object
<CustomObject>
    <fields>
        <fullName>FolioLead__c</fullName>
        <label>Folio de lead / oportunidad</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hasta__c</fullName>
        <label>Hasta el</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Nivel</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Nivel</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Fichas de pago</relationshipLabel>
        <relationshipName>Fichas_de_pago</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Oportunidad__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Oportunidad</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Fichas de pago</relationshipLabel>
        <relationshipName>Fichas_de_pago</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Fichas de pago</relationshipLabel>
        <relationshipName>Fichas_de_pago</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecibimosDe__c</fullName>
        <label>Recibimos de</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TipoFicha__c</fullName>
        <label>Tipo de ficha</label>
        <picklist>
            <picklistValues>
                <fullName>Nivel Doctorado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nivel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Promoción Cero</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ficha Especial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ficha Móvil</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TotaPagar__c</fullName>
        <label>Total a pagar</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Ficha de pago</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fichas de pago</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>FichaPago__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Ficha de Pago</description>
        <label>Con ficha pago</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Folio__c</fullName>
        <displayFormat>C-{000000}</displayFormat>
        <externalId>true</externalId>
        <label>Folio</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>ImporteTotal__c</fullName>
        <formula>Antologia__c +  ColegiaturaDescuento__c + InscripcionDescuento__c + ExamenAdmision__c +  Propedeutico__c +  Uniforme__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Importe total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Nivel</description>
        <label>Nivel</label>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Candidatos (Nivel)</relationshipLabel>
        <relationshipName>Nivel</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Plantel</description>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Candidatos</relationshipLabel>
        <relationshipName>Plantel</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VigenciaDescuento__c</fullName>
        <label>Vigencia de descuento</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Folio__c</fullName>
        <label>Folio</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ImporteTotal__c</fullName>
        <formula>IF( AplicaPromocionCero__c , 0, Inscripcion__c -( Inscripcion__c * PorcentajeDescuento__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Importe total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Nivel</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Nivel</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Oportunidades (Nivel)</relationshipLabel>
        <relationshipName>Oportunidades1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Oportunidades</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VigenciaDescuento__c</fullName>
        <label>VigenciaDescuento</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Plantel__c.object
<CustomObject>
    <label>Plantel</label>
    <nameField>
        <label>Plantel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planteles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SolicitudBeca__c.object
<CustomObject>
    <fields>
        <fullName>Estatus__c</fullName>
        <label>Estatus</label>
        <picklist>
            <picklistValues>
                <fullName>Activo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactivo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rechazada</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Oportunidad__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Oportunidad</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Solicitudes de beca</relationshipLabel>
        <relationshipName>SolicitudesBeca</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Solicitud de beca</label>
    <nameField>
        <label>Nombre de Solicitud de beca</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solicitudes de beca</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FichaPagoOpportunityCtrl.cls
public with sharing class FichaPagoOpportunityCtrl {

    public Opportunity infoOpp;
   	public Boolean existApproval {get;set;}
    /**
    * @author:      Gerardo Martínez
    * @date:        17/06/2016
    * @description: Constructor del controlador FichaPagoOpportunityCtrl
    * @param:       ApexPages.StandardController controller (controlador estandar).
    * @return:      
    */
    public FichaPagoOpportunityCtrl(ApexPages.StandardController controller){
    	infoOpp = (Opportunity)controller.getRecord();
        existApproval = false;
    } 
    

    /**
    * @author:      Gerardo Martínez
    * @date:        17/06/2016
    * @description: Regresa el registro creado de la página
    * @param:       ApexPages.StandardController controller (controlador estandar).
    * @return:      PageReference Visual Force Page
    */
    public PageReference createPayToken(){
        try{
        	SolicitudBeca__C solicitudes = [SELECT Id FROM SolicitudBeca__c WHERE Oportunidad__c =: infoOpp.id AND Estatus__c = 'Inactivo'];
            if(solicitudes != null){
                existApproval = true;
                return null;
            }
        }catch(Exception e){
        }
        Opportunity data = [SELECT Id, Name, VigenciaDescuento__c, Folio__c, ImporteTotal__c, ImportePagarConDescuento__c, Nivel__r.Name, Plantel__c FROM Opportunity WHERE Id =: infoOpp.Id];       
       
        FichaPago__c newToken = new FichaPago__c();
      
        newToken.FolioLead__c = Decimal.valueOf(data.Folio__c.replace('C-',''));
        newToken.RecibimosDe__c = (data.Name != null ? data.Name : '');
        newToken.TotaPagar__c = data.ImporteTotal__c; //Antes ImportePagarConDescuento__c
        newToken.Oportunidad__c = infoOpp.Id;
        newToken.Plantel__c = data.plantel__c;
        
        if(data.nivel__r.Name == 'Licenciatura' || data.nivel__r.Name == 'Maestría'){
            newToken.TipoFicha__c = 'Nivel';
        }else if(data.nivel__r.Name == 'Doctorado'){
            newToken.TipoFicha__c = 'Nivel Doctorado';
        }


        if(data.VigenciaDescuento__c != null){
                newToken.Hasta__c = data.VigenciaDescuento__c; 
        }else{
                Date today = Date.today();
                Date vigancia = today.addDays(10); 
                newToken.Hasta__c = vigancia; 
        }

        insert newToken;
        return new PageReference('/' + newToken.Id);

    }
    
    public PageReference exit(){
        return new PageReference('/' + infoOpp.id);
    }
}