src/objects/Catalogo__c.object
<CustomObject>
    <fields>
        <fullName>IdInternoNivel__c</fullName>
        <externalId>true</externalId>
        <label>Id Interno Nivel</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Catálogo</label>
    <nameField>
        <label>Nombre de Catálogo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catálogos</pluralLabel>
    <recordTypes>
        <fullName>FormaPago</fullName>
        <active>true</active>
        <label>Forma de pago</label>
    </recordTypes>
    <recordTypes>
        <fullName>Nivel</fullName>
        <active>true</active>
        <description>Crear nuevo registro del tipo Nivel</description>
        <label>Nivel</label>
    </recordTypes>
    <recordTypes>
        <fullName>TipoTarjeta</fullName>
        <active>true</active>
        <description>Tipo de Tarjeta</description>
        <label>Tipo Tarjeta</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Descuento__c.object
<CustomObject>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Nivel</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Nivel</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Descuentos</relationshipLabel>
        <relationshipName>Descuentos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Oportunidad__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Oportunidad</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Descuentos</relationshipLabel>
        <relationshipName>Descuentos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Periodo__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Periodo</label>
        <referenceTo>Periodo__c</referenceTo>
        <relationshipLabel>Descuentos</relationshipLabel>
        <relationshipName>Descuentos</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Descuento</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Descuentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FichaPago__c.object
<CustomObject>
    <fields>
        <fullName>Descuento__c</fullName>
        <label>Descuento</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>FechaPago__c</fullName>
        <label>Fecha de pago</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FuentePago__c</fullName>
        <label>Fuente de pago</label>
        <picklist>
            <picklistValues>
                <fullName>O</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>H</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Hasta__c</fullName>
        <label>Hasta el</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>HoraPago__c</fullName>
        <label>Hora de pago</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Importe__c</fullName>
        <label>Importe</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MontoPagado__c</fullName>
        <label>Monto pagado</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Nivel</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Nivel</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Fichas de pago</relationshipLabel>
        <relationshipName>Fichas_de_pago</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NumeroAutorizacion__c</fullName>
        <description>Numero de autorización del pago</description>
        <label>Numero Autorización</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Oportunidad__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Oportunidad</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Fichas de pago</relationshipLabel>
        <relationshipName>Fichas_de_pago</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Periodo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Periodo</label>
        <referenceTo>Periodo__c</referenceTo>
        <relationshipLabel>Fichas de pago</relationshipLabel>
        <relationshipName>Fichas_de_pago</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Fichas de pago</relationshipLabel>
        <relationshipName>Fichas_de_pago</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecibimosDe__c</fullName>
        <label>Recibimos de</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TipoFicha__c</fullName>
        <label>Tipo de ficha</label>
        <picklist>
            <picklistValues>
                <fullName>Nivel Doctorado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nivel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Promoción Cero</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ficha Especial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ficha Móvil</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TotaPagar__c</fullName>
        <label>Total a pagar</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Ficha de pago</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fichas de pago</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>FichaPago__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Ficha de Pago</description>
        <label>Con ficha pago</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Folio__c</fullName>
        <displayFormat>C-{000000}</displayFormat>
        <externalId>true</externalId>
        <label>Folio</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>FormaPago__c</fullName>
        <globalPicklist>FormaPago</globalPicklist>
        <label>Forma de pago</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Inscripcion__c</fullName>
        <description>Monto de la Inscripción</description>
        <label>Inscripción</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Nivel</description>
        <label>Nivel</label>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Candidatos (Nivel)</relationshipLabel>
        <relationshipName>Nivel</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Periodo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Periodo</description>
        <label>Periodo</label>
        <referenceTo>Periodo__c</referenceTo>
        <relationshipLabel>Periodo</relationshipLabel>
        <relationshipName>Periodo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Plantel</description>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Candidatos</relationshipLabel>
        <relationshipName>Plantel</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Folio__c</fullName>
        <label>Folio</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FormaPago__c</fullName>
        <globalPicklist>FormaPago</globalPicklist>
        <label>Forma de pago</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Inscripcion__c</fullName>
        <label>Inscripción</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Nivel</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Nivel</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Oportunidades (Nivel)</relationshipLabel>
        <relationshipName>Oportunidades1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pago__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Realización del pago</description>
        <label>Pago</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Periodo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Periodo</label>
        <referenceTo>Periodo__c</referenceTo>
        <relationshipLabel>Oportunidades</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Oportunidades</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Periodo__c.object
<CustomObject>
    <fields>
        <fullName>IdPeriodo__c</fullName>
        <externalId>true</externalId>
        <label>IdPeriodo</label>
        <type>AutoNumber</type>
    </fields>
    <label>Periodo</label>
    <nameField>
        <label>Periodo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Periodos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Plantel__c.object
<CustomObject>
    <fields>
        <fullName>IdInterno__c</fullName>
        <externalId>true</externalId>
        <label>IdInterno</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Plantel</label>
    <nameField>
        <label>Plantel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planteles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OPP_PagoTarjetaController.cls
public without sharing class OPP_PagoTarjetaController {
	
    private Pago__c pagos;
    private Opportunity opportunity;
    public List<String> numTarjeta {get; set;}
    public String concepto {get; set;}
    public String tipoTarjeta {get; set;}
    public String mes {get; set;}
    public String anyo {get; set;}
    public String conceptoNum;
    public String codigo {get; set;}   
    public String error {get; set;}
    public Boolean pagoRealizado {get; set;}
    public String urlComprobante {get; set;}
    public FichaPago__c ficha;
    
    public Opportunity opp{
        get {
            if(opp == null){
                opp = [SELECT Id, Name, Folio__c, ImportePagarSinDescuento__c, ImportePagarConDescuento__c, PrimerPagoConTarjeta__c, DescuentoParaFicha__c, 
                       Nivel__r.Name, Nivel__r.IdInternoNivel__c, Plantel__r.IdInterno__c, Periodo__r.IdPeriodo__c,
                       Periodo__c, Plantel__c, Nivel__c, CorreoCuenta__c, StageName, Pago__c
                       FROM Opportunity 
                       WHERE Id =: opportunity.Id];
            }
            return opp;
        }
        private set;
    }
    
    public OPP_PagoTarjetaController(ApexPages.StandardController stdController) {
        this.opportunity = (Opportunity)stdController.getRecord();
        pagoRealizado = opp.Pago__c == true ? opp.Pago__c : false;
        numTarjeta = new String[4];
        for (Integer i = 0; i<numTarjeta.size(); i++){
            numTarjeta[i] = '';
        }
        pagos = Pago__c.getInstance();
        
        if((opp.Nivel__r.Name).equals('Doctorado') && !opp.PrimerPagoConTarjeta__c){
            concepto = Schema.sObjectType.Pago__c.fields.Examen__c.getLabel();
            conceptoNum = pagos.Examen__c;
        }
        else{
        	concepto = Schema.sObjectType.Pago__c.fields.Inscripcion__c.getLabel();
            conceptoNum = pagos.Inscripcion__c;
        }
    }
    
    
    	    
    public List<SelectOption> getTipoTarjetaSelectList() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('0', '-- Seleccione --'));  
        options.add(new SelectOption(pagos.TarjetaMasterCard__c, Schema.sObjectType.Pago__c.fields.TarjetaMasterCard__c.getLabel()));
        options.add(new SelectOption(pagos.TarjetaVisa__c , Schema.sObjectType.Pago__c.fields.TarjetaVisa__c.getLabel()));
        return options;
    }

    public List<SelectOption> getMonths() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('0', '-- mm --')); 
        for(Integer i=1; i<=12; i++){
            String m = String.valueOf(i);
            if (m.length() == 1){
                m = '0' + m;
            }
            options.add(new SelectOption(m , m));
        }
        return options;
    }
    
    public List<SelectOption> getYears() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('0', '-- yyyy --')); 
        Date dateToday = Date.today(); 
        Integer year = (dateToday).year();
        for(Integer i=year; i<=year+15; i++){
            String y = String.valueOf(i);
            options.add(new SelectOption(y, y));
        }
        return options;
    }
    
    public PageReference sentPayment(){
        Map<String, String> datosEnviar = new Map<String, String>();
        Boolean infoCorrect = true; 
        pagoRealizado = false;
        PageReference page;
        
        datosEnviar.put('matricula', opp.Folio__c);
        infoCorrect = (!datosEnviar.containsKey('matricula') || datosEnviar.get('matricula').equals(null) || datosEnviar.get('matricula').equals('')) ? false : infoCorrect; 
        
        datosEnviar.put('concepto', conceptoNum);
		infoCorrect = (!datosEnviar.containsKey('concepto') || datosEnviar.get('concepto').equals(null) || datosEnviar.get('concepto').equals('')) ? false : infoCorrect; 
        
        datosEnviar.put('descripcionConcepto', concepto);
        infoCorrect = (!datosEnviar.containsKey('descripcionConcepto') || datosEnviar.get('descripcionConcepto').equals(null) || datosEnviar.get('descripcionConcepto').equals('')) ? false : infoCorrect; 
        
        datosEnviar.put('cantidad', String.valueOf(opp.ImportePagarConDescuento__c));
        infoCorrect = (!datosEnviar.containsKey('cantidad') || datosEnviar.get('cantidad').equals(null) || datosEnviar.get('cantidad').equals('')) ? false : infoCorrect; 
        
        datosEnviar.put('tipo', tipoTarjeta);
        infoCorrect = (!datosEnviar.containsKey('tipo') || datosEnviar.get('tipo').equals(null) || datosEnviar.get('tipo').equals('0')) ? false : infoCorrect; 
        
        datosEnviar.put('pnumero', numTarjeta[0]);
        infoCorrect = (!datosEnviar.containsKey('pnumero') || datosEnviar.get('pnumero').equals(null) || datosEnviar.get('pnumero').equals('')) ? false : infoCorrect; 
        
        datosEnviar.put('snumero', numTarjeta[1]);
        infoCorrect = (!datosEnviar.containsKey('snumero') || datosEnviar.get('snumero').equals(null) || datosEnviar.get('snumero').equals('')) ? false : infoCorrect; 
        
        datosEnviar.put('tnumero', numTarjeta[2]);
        infoCorrect = (!datosEnviar.containsKey('tnumero') || datosEnviar.get('tnumero').equals(null) || datosEnviar.get('tnumero').equals('')) ? false : infoCorrect; 
        
        datosEnviar.put('cnumero', numTarjeta[3]);
        infoCorrect = (!datosEnviar.containsKey('cnumero') || datosEnviar.get('cnumero').equals(null) || datosEnviar.get('cnumero').equals('')) ? false : infoCorrect; 
        
        datosEnviar.put('mes', mes);
        infoCorrect = (!datosEnviar.containsKey('mes') || datosEnviar.get('mes').equals(null) || datosEnviar.get('mes').equals('0')) ? false : infoCorrect; 
        
        datosEnviar.put('anio', anyo);
        infoCorrect = (!datosEnviar.containsKey('anio') || datosEnviar.get('anio').equals(null) || datosEnviar.get('anio').equals('0')) ? false : infoCorrect; 
        
        datosEnviar.put('codigo', codigo);
        infoCorrect = (!datosEnviar.containsKey('codigo') || datosEnviar.get('codigo').equals(null) || datosEnviar.get('codigo').equals('')) ? false : infoCorrect; 
        
        datosEnviar.put('formaPago', pagos.FormaPago__c);
        infoCorrect = (!datosEnviar.containsKey('formaPago') || datosEnviar.get('formaPago').equals(null) || datosEnviar.get('formaPago').equals('')) ? false : infoCorrect; 
        
        datosEnviar.put('nivel', String.valueOf(opp.Nivel__r.IdInternoNivel__c));
        infoCorrect = (!datosEnviar.containsKey('nivel') || datosEnviar.get('nivel').equals(null) || datosEnviar.get('nivel').equals('')) ? false : infoCorrect; 
        
        Date dateToday = Date.today();
        dateToday = dateToday.addMonths(1);
        datosEnviar.put('fechaserver', dateToday.day() +'/'+ dateToday.month() +'/'+ dateToday.year());
        infoCorrect = (!datosEnviar.containsKey('fechaserver') || datosEnviar.get('fechaserver').equals(null) || datosEnviar.get('fechaserver').equals('')) ? false : infoCorrect; 
        
        datosEnviar.put('IdPlantel', String.valueOf(opp.Plantel__r.IdInterno__c));
        infoCorrect = (!datosEnviar.containsKey('IdPlantel') || datosEnviar.get('IdPlantel').equals(null) || datosEnviar.get('IdPlantel').equals('')) ? false : infoCorrect; 
        
        datosEnviar.put('periodoEscolar', String.valueOf(opp.Periodo__r.IdPeriodo__c));
        infoCorrect = (!datosEnviar.containsKey('periodoEscolar') || datosEnviar.get('periodoEscolar').equals(null) || datosEnviar.get('periodoEscolar').equals('')) ? false : infoCorrect; 
        
        if(!infoCorrect){
            PageMessagesController.addMessage(new PageMessagesController.PageMessage(PageMessagesController.Severity.ERROR, 'Todos los parametros son obligatorios'));
            page = ApexPages.CurrentPage();
            return page;
        }
        
        String respuestaSer = EnvioPago(datosEnviar);
        page = ApexPages.CurrentPage();
        
        if(respuestaSer.contains('MAXIMUM ISSUING BANK NAME PER JAN')){
            Integer position = respuestaSer.lastIndexOf('Y_');
            String codigAuto = respuestaSer.substring(position + 2, position + 8);
            createFichaPago(codigAuto);
            pagoRealizado = true;
            ComprobanteLeadCtrl.sendMailComprobante(opp.Folio__c, concepto, opp.CorreoCuenta__c, codigAuto, String.valueOf(opp.ImportePagarConDescuento__c), String.valueOf(ficha.FechaPago__c), pagos.Mensaje_nota_comprobante__c);            
            PageMessagesController.addMessage(new PageMessagesController.PageMessage(PageMessagesController.Severity.CONFIRM, 'La operación fue aprobada, con el siguiente código de aprobación: '+codigAuto+'.'));            
            urlComprobante = 'https://' + String.valueOf(URL.getSalesforceBaseUrl().getHost()) +'/apex/ComprobanteLead?folio='+ encodeASCII(opp.Folio__c);
            urlComprobante += '&concepto='+ encodeASCII(concepto); 
            urlComprobante += '&autorizacion='+ encodeASCII(codigAuto) +'&cantidad='+ encodeASCII(String.valueOf(opp.ImportePagarConDescuento__c))+'&fecha='+ encodeASCII(String.valueOf(ficha.FechaPago__c)) +'&nota2='+ encodeASCII(pagos.Mensaje_nota_comprobante__c); 
            return new PageReference(urlComprobante).setRedirect(true);
            
        }else if(respuestaSer.contains('N_INVALID ACCOUNT NUMBER')){
            PageMessagesController.addMessage(new PageMessagesController.PageMessage(PageMessagesController.Severity.ERROR, 'El número que usted ingresó no corresponde a los números de tarjetas soportadas por el sistema. Debe verificar el número que digito y corregirlo.'));          
        
        }else if(respuestaSer.contains('N_')){
            error = respuestaSer.substring(respuestaSer.lastIndexOf('-->N_'));
            List<String> partsError = error.split('\n'); 
			error = partsError.size() > 0 ? partsError[0].substring((partsError[0].lastIndexOf('-->N_'))+5) : 'Error al ejecutar la operación por favor intente más tarde';
            PageMessagesController.addMessage(new PageMessagesController.PageMessage(PageMessagesController.Severity.ERROR, error));          
        
        }else if(respuestaSer.contains('este concepto ya se ha realizado')){
            PageMessagesController.addMessage(new PageMessagesController.PageMessage(PageMessagesController.Severity.ERROR, 'La transacción para este concepto ya se ha realizado con anterioridad'));          
            pagoRealizado = true;
        
        }else if(respuestaSer.equals('Read timed out') || respuestaSer.contains('N_Servidor Saturado ')){
            PageMessagesController.addMessage(new PageMessagesController.PageMessage(PageMessagesController.Severity.ERROR, 'No es posible realizar la transacción en este momento, intenete nuevamente más tarde'));          
        
        }else{
            PageMessagesController.addMessage(new PageMessagesController.PageMessage(PageMessagesController.Severity.ERROR, respuestaSer));          
        	//page = new PageReference('/'+opp.Id);
        }
        return page;
    }
    
    public PageReference cancelPayment(){
        PageReference page;
        page = new PageReference('/'+opp.Id);
        page.setRedirect(true);
        return page;
    }
    
   
    public String EnvioPago(Map<String,String> datosPago){
        String url = pagos.EndPoint__c;
        Integer timeout = Integer.valueOf(pagos.TimeOut__c);
        String body = '';
        String bodyLog = '';
        String respuesta = '';      
        
        for(String parametro: datosPago.keySet()){
            body += parametro + '=' + datosPago.get(parametro) + '&';
            if(parametro.contains('numero') || parametro.equals('codigo')){
                bodyLog += parametro + '=' + '***' + '&';
            }
            else{
            	bodyLog += parametro + '=' + datosPago.get(parametro) + '&';
            }
        }
        body = body.removeEnd('&');
        
        Http objhttp;
        HttpRequest req ;
        HttpResponse res ;
        
        objhttp = new Http();
        req = new HttpRequest();
        res = new HttpResponse();
        req.setMethod('POST'); // req.setMethod('GET');
        req.setEndpoint(url);        
        req.setBody(body);
        req.setTimeout(120000);
        try {
            res = objhttp.send(req);
            if(res.getStatusCode() == 200){
                UtilsLog.createLog(UtilsLog.Estatus.CORRECTO, 'POSTenvioPago', bodyLog , String.valueOf(res.getBody()));                
                respuesta = String.valueOf(res.getBody());                
            }
            else{
                UtilsLog.createLogError('POSTenvioPagoE', bodyLog, res.getBody());
                respuesta = res.getBody();
            }
        }
        catch(System.Exception e) {
            UtilsLog.createLogError('POSTenvioPagoEx', bodyLog, e.getMessage()); 
            respuesta = e.getMessage();
        }        
        System.debug(res.getBody());
        return respuesta;
    } 
    
    public void createFichaPago(String folioAutorizacion){
        ficha = new FichaPago__c();      
        ficha.Descuento__c = opp.DescuentoParaFicha__c;
        ficha.FuentePago__c = 'T';
        ficha.Importe__c = opp.ImportePagarSinDescuento__c;
        ficha.MontoPagado__c = opp.ImportePagarConDescuento__c;
        ficha.TotaPagar__c = opp.ImportePagarConDescuento__c;
        ficha.Nivel__c = opp.Nivel__c;
        ficha.NumeroAutorizacion__c = folioAutorizacion;
        ficha.Oportunidad__c = opp.Id;
        ficha.Periodo__c = opp.Periodo__c;
        ficha.Plantel__c = opp.Plantel__c;
        ficha.RecibimosDe__c = opp.Name;
        ficha.TipoTarjeta__c = tipoTarjeta == pagos.TarjetaMasterCard__c ? 'MásterCard' : 'Visa';
        ficha.FechaPago__c = Date.today();
        ficha.Hasta__c = Date.today();
        ficha.HoraPago__c = Datetime.now().format('h:mm a');
        ficha.TipoFicha__c = 'Pago Online';
        ficha.RecordTypeId = Schema.SObjectType.FichaPago__c.getRecordTypeInfosByName().get('Pago Online').getRecordTypeId();
        try{
            insert ficha; 
        }
        catch(Exception e){
            UtilsLog.createLogError('InsertNewFichaPagoByPagoConTarjeta', String.valueOf(ficha), e.getMessage());
        }
        
    }
    
    public static String encodeASCII(String cadena){
        return EncodingUtil.urlEncode(cadena, 'UTF-8');
    }
    
}