src/objects/Catalogo__c.object
<CustomObject>
    <label>Catálogo</label>
    <nameField>
        <label>Nombre de Catálogo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catálogos</pluralLabel>
    <recordTypes>
        <fullName>Modalidad</fullName>
        <active>true</active>
        <description>Crear nuevo registro del tipo Modalidad</description>
        <label>Modalidad</label>
    </recordTypes>
    <recordTypes>
        <fullName>Nivel</fullName>
        <active>true</active>
        <description>Crear nuevo registro del tipo Nivel</description>
        <label>Nivel</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Modalidad__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Modalidad</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Modalidad</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Candidatos (Modalidad)</relationshipLabel>
        <relationshipName>Candidatos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Nivel</description>
        <label>Nivel</label>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Candidatos (Nivel)</relationshipLabel>
        <relationshipName>Nivel</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OfertaEducativa__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Búsqueda de Oferta Educativa para el Canidato</description>
        <label>Oferta educativa</label>
        <referenceTo>OfertaEducativa__c</referenceTo>
        <relationshipLabel>Candidatos</relationshipLabel>
        <relationshipName>Candidatos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Periodo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Periodo</description>
        <label>Periodo</label>
        <referenceTo>Periodo__c</referenceTo>
        <relationshipLabel>Periodo</relationshipLabel>
        <relationshipName>Periodo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Plantel</description>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Candidatos</relationshipLabel>
        <relationshipName>Plantel</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Programa__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Programa</description>
        <label>Programa</label>
        <referenceTo>Programa__c</referenceTo>
        <relationshipLabel>Candidatos</relationshipLabel>
        <relationshipName>Programa</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Materia__c.object
<CustomObject>
    <fields>
        <fullName>Modalidad__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Modalidad</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Modalidad</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Materias (Modalidad)</relationshipLabel>
        <relationshipName>Modalidad</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Nivel</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Nivel</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Materias</relationshipLabel>
        <relationshipName>Materias</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Materias</relationshipLabel>
        <relationshipName>Materias</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Programa__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Programa</label>
        <referenceTo>Programa__c</referenceTo>
        <relationshipLabel>Materias</relationshipLabel>
        <relationshipName>Materias</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Materia</label>
    <nameField>
        <label>Materia</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OfertaConceptoPagos__c.object
<CustomObject>
    <fields>
        <fullName>Activo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ConceptoPago__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Concepto pago</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Concepto Pagos</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Ofertas Concepto Pagos</relationshipLabel>
        <relationshipName>Ofertas_Concepto_Pagos</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Monto__c</fullName>
        <label>Monto</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OfertaEducativa__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Oferta educativa</label>
        <referenceTo>OfertaEducativa__c</referenceTo>
        <relationshipLabel>Ofertas Concepto Pagos</relationshipLabel>
        <relationshipName>OfertasConceptoPagos</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Oferta Concepto Pagos</label>
    <nameField>
        <displayFormat>OE-CP-{00000}</displayFormat>
        <label>Oferta Concepto Pagos</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ofertas Concepto Pagos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OfertaEducativa__c.object
<CustomObject>
    <fields>
        <fullName>Modalidad__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Modalidad</inlineHelpText>
        <label>Modalidad</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Modalidad</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Ofertas Educativas</relationshipLabel>
        <relationshipName>Ofertas_Educativas</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Nivel</inlineHelpText>
        <label>Nivel</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Nivel</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Ofertas Educativas (Nivel)</relationshipLabel>
        <relationshipName>Ofertas_Educativas1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Periodo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Periodo</label>
        <referenceTo>Periodo__c</referenceTo>
        <relationshipLabel>Ofertas Educativas</relationshipLabel>
        <relationshipName>Ofertas_Educativas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Plantel</inlineHelpText>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Ofertas Educativas</relationshipLabel>
        <relationshipName>Ofertas_Educativas</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Programa__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Programa</inlineHelpText>
        <label>Programa</label>
        <referenceTo>Programa__c</referenceTo>
        <relationshipLabel>Ofertas Educativas</relationshipLabel>
        <relationshipName>Ofertas_Educativas</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Oferta Educativa</label>
    <nameField>
        <displayFormat>OE-{0000000}</displayFormat>
        <label>Oferta Educativa</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ofertas Educativas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Periodo__c.object
<CustomObject>
    <fields>
        <fullName>ActivoEjecutiva__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activo ejecutiva</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ActivoOnline__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activo online</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ActivoPresencial__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activo presencial</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Activo__c</fullName>
        <label>Estatus</label>
        <picklist>
            <picklistValues>
                <fullName>Activo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactivo</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Periodo</label>
    <nameField>
        <label>Periodo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Periodos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Plantel__c.object
<CustomObject>
    <label>Plantel</label>
    <nameField>
        <label>Plantel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planteles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Programa__c.object
<CustomObject>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Nivel</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Nivel</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Programas</relationshipLabel>
        <relationshipName>Programas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Programas</relationshipLabel>
        <relationshipName>Programas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Programa</label>
    <nameField>
        <label>Programa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Ubicacion__c.object
<CustomObject>
    <description>Listado que contiene: País, estados y municipios</description>
    <fields>
        <fullName>IdEstadoPais__c</fullName>
        <description>Aplica para municipio y estado</description>
        <label>Id Estado/País</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IdUbicacion__c</fullName>
        <label>Id</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TipoUbicacion__c</fullName>
        <label>Tipo</label>
        <picklist>
            <picklistValues>
                <fullName>Estado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>País</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Municipio</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Ubicación</label>
    <nameField>
        <label>Nombre de Ubicación</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ubicaciones</pluralLabel>
    <recordTypes>
        <fullName>Estado</fullName>
        <active>true</active>
        <label>Estado</label>
    </recordTypes>
    <recordTypes>
        <fullName>Municipio</fullName>
        <active>true</active>
        <label>Municipio</label>
    </recordTypes>
    <recordTypes>
        <fullName>Pais</fullName>
        <active>true</active>
        <label>Pais</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UtilsExternal.cls
global class UtilsExternal {
	/**
    * @author:      Salvador Reyna
    * @date:        28/06/2016
    * @description: 
    * @param:       
    * @return:      
    */
    public Id idLead {get;set;}
    public String email {get;set;}
    
    @RemoteAction
    global static ComboWrapper getExternalOfertaAcademica(){
        List<OfertaEducativa__c> listOffer = [SELECT Id, Modalidad__c, Modalidad__r.Name,
                                        		Nivel__c, Nivel__r.Name,
                                        		Plantel__c, Plantel__r.Name,
                                        		Programa__c, Programa__r.Name,
                                                Periodo__r.ActivoEjecutiva__c, 
                                                Periodo__r.ActivoOnline__c, 
                                                Periodo__r.ActivoPresencial__c
                                        		FROM OfertaEducativa__c WHERE 
                                         		Periodo__r.Activo__c = 'Activo' 
                                         		AND (Nivel__r.Name = 'Licenciatura' 
                                                OR Nivel__r.Name = 'Maestría' 
                                                OR Nivel__r.Name = 'Doctorado')
                                                AND (Periodo__r.ActivoEjecutiva__c = true OR 
                                                Periodo__r.ActivoOnline__c = true OR 
                                                Periodo__r.ActivoPresencial__c = true)];
        
        ItemWrapper itemModalidad = new ItemWrapper('Modalidad');
        ItemWrapper itemNivel = new ItemWrapper('Nivel');
        ItemWrapper itemPlantel = new ItemWrapper('Plantel');
        ItemWrapper itemPrograma = new ItemWrapper('Programa');
        
        String modalidadBussy = '';
        String nivelBussy = '';
        String plantelBussy = '';
        String programaBussy = '';
        for(OfertaEducativa__c offer: listOffer){
            InfoWrapper infoModalidad = new infoWrapper();
            InfoWrapper infoNivel = new infoWrapper();
            InfoWrapper infoPlantel = new infoWrapper();
            InfoWrapper infoPrograma = new infoWrapper();
            
            if(((offer.Modalidad__r.Name).equals('Online') && offer.Periodo__r.ActivoOnline__c == true) ||
               ((offer.Modalidad__r.Name).equals('Ejecutiva') && offer.Periodo__r.ActivoEjecutiva__c == true) ||
               ((offer.Modalidad__r.Name).equals('Presencial') && offer.Periodo__r.ActivoPresencial__c == true)){
                   //Informacion de la modalidad
                   infoModalidad.dataId = offer.Modalidad__c;
                   infoModalidad.name = offer.Modalidad__r.Name;
                   //Información del nivel
                   infoNivel.dataId = String.valueOf(offer.Nivel__c) + '-' +String.valueOf(offer.Modalidad__c);
                   infoNivel.name = offer.Nivel__r.Name;
                   infoNivel.parent = offer.Modalidad__c;
                   //Información del Plantel
                   infoPlantel.dataId = String.valueOf(offer.Plantel__c) + '-' + String.valueOf(offer.Nivel__c) + '-' + String.valueOf(offer.Modalidad__c);
                   infoPlantel.name = offer.Plantel__r.Name;
                   infoPlantel.parent = String.valueOf(offer.Nivel__c) + '-' + String.valueOf(offer.Modalidad__c);
                   //Información del Programa
                   infoPrograma.dataId =  String.valueOf(offer.Id) + '-' +String.valueOf(offer.Programa__c) + '-' + String.valueOf(offer.Plantel__c) + '-' + String.valueOf(offer.Nivel__c) + '-' + String.valueOf(offer.Modalidad__c);
                   infoPrograma.name = offer.Programa__r.Name;
                   infoPrograma.parent = String.valueOf(offer.Plantel__c) + '-' + String.valueOf(offer.Nivel__c) + '-' + String.valueOf(offer.Modalidad__c);
                   
                   if(!modalidadBussy.contains(offer.Modalidad__c)){
                       itemModalidad.items.add(infoModalidad);
                       modalidadBussy += '-' + offer.Modalidad__c;
                   }
                   
                   String toNivel = String.valueOf(offer.Nivel__c) + String.valueOf(offer.Modalidad__c);
                   if(!nivelBussy.contains(toNivel)){
                       itemNivel.items.add(infoNivel);
                       nivelBussy += '-' + offer.Nivel__c + offer.Modalidad__c;
                   }
                   
                   String toPlantel = String.valueOf(offer.Plantel__c) + String.valueOf(offer.Nivel__c) + String.valueOf(offer.Modalidad__c);
                   if(!plantelBussy.contains(toPlantel)){
                       itemPlantel.items.add(infoPlantel);
                       plantelBussy += '-' + offer.Plantel__c + offer.Nivel__c + offer.Modalidad__c;
                   }
                   
                   String toPrograma = String.valueOf(offer.Programa__c) + String.valueOf(offer.Plantel__c) + String.valueOf(offer.Nivel__c) + String.valueOf(offer.Modalidad__c);
                   if(!programaBussy.contains(toPrograma)){
                       itemPrograma.items.add(infoPrograma);
                       programaBussy += '-' + offer.Programa__c + offer.Plantel__c + offer.Nivel__c + offer.Modalidad__c;
                   }
               }
        }
        ComboWrapper cw = new ComboWrapper();
		cw.modalidad = itemModalidad;
        cw.nivel = itemNivel;
        cw.plantel = itemPlantel;
        cw.programa = itemPrograma;
        return cw;
    }

	/**
    * @author:      Gabriel Garcia
    * @date:        04/07/2016
    * @description: Método para obtener los cátalogos de ubicación
    * @param:       
    * @return:      
    */
    @RemoteAction
    global static Map<String, List<SObject>> getExternalUbicacion(){
        Map<String, List<SObject>> ubicacion = new Map<String, List<SObject>>();
        ubicacion.put('pais', Database.query('SELECT Id, IdUbicacion__c, Name, IdEstadoPais__c FROM Ubicacion__c WHERE TipoUbicacion__c= \'País\' ORDER BY Name'));
        ubicacion.put('estado', Database.query('SELECT IdUbicacion__c, Name, IdEstadoPais__c FROM Ubicacion__c WHERE TipoUbicacion__c= \'Estado\' ORDER BY Name'));
        ubicacion.put('municipio', Database.query('SELECT IdUbicacion__c, Name, IdEstadoPais__c FROM Ubicacion__c WHERE TipoUbicacion__c= \'Municipio\' ORDER BY Name'));
        
        return ubicacion;
    }
    
    @RemoteAction
    //@future(callout=true)
    global static void sendEmailCalculadora(String idLead, String email, String promedio, String descuentoInsc, String descuentoMens, String vigencia){
        System.debug('*********** ' + idLead + ' ' + email);
        Id leadId = Id.valueOf(idLead);
        PlantillaCalculoRegistradoController.sendMail(leadId, email, promedio, descuentoInsc, descuentoMens, vigencia);   
    }
        
    /*
    @RemoteAction
    global static ComboUbicacionWrapper getExternalUbicacion(){
    
        ItemWrapper itemPais = new ItemWrapper('País');
        ItemWrapper itemEstado = new ItemWrapper('Estado');
        ItemWrapper itemMunicipio = new ItemWrapper('Municipio');
        
        String paisBussy = '';
        String estadoBussy = '';
        String municipioBussy = '';
        
        List<Ubicacion__c> listMunicipios = [SELECT IdUbicacion__c, Name, IdEstadoPais__c FROM Ubicacion__c WHERE TipoUbicacion__c= 'Municipio' ORDER BY Name];
        for(Ubicacion__c municipio: listMunicipios){
            InfoWrapper infoMunicipio = new infoWrapper();
            //Informacion de Municipio
            infoMunicipio.dataId = municipio.IdUbicacion__c;
            infoMunicipio.name = municipio.Name;
            infoMunicipio.parent = municipio.IdEstadoPais__c;        
            itemMunicipio.items.add(infoMunicipio);
        }
        
        List<Ubicacion__c> listPaises = [SELECT IdUbicacion__c, Name FROM Ubicacion__c WHERE TipoUbicacion__c= 'País' ORDER BY Name];
        for(Ubicacion__c pais: listPaises){
            InfoWrapper infoPais = new infoWrapper();
            //Informacion del pais
            infoPais.dataId = pais.IdUbicacion__c;
            infoPais.name = pais.Name;
            itemPais.items.add(infoPais);
        }
        
        List<Ubicacion__c> listEstados = [SELECT IdUbicacion__c, Name, IdEstadoPais__c FROM Ubicacion__c WHERE TipoUbicacion__c= 'Estado' ORDER BY Name];
        for(Ubicacion__c estado: listEstados){
            InfoWrapper infoEstado = new infoWrapper();
            //Informacion de Estado
            infoEstado.dataId = estado.IdUbicacion__c;
            infoEstado.name = estado.Name;
            infoEstado.parent = estado.IdEstadoPais__c;
            itemEstado.items.add(infoEstado);
        }
        
        
        ComboUbicacionWrapper cw = new ComboUbicacionWrapper();
		cw.pais = itemPais;
        cw.estado = itemEstado;
        cw.municipio = itemMunicipio;
        return cw;
    }
    */
    @RemoteAction
    global static Map<String, String> getMontos(String ofe){
    	Map<String, String> montos = new Map<String , String>();
        List<OfertaConceptoPagos__c> listMontos = new List<OfertaConceptoPagos__c>();
        listMontos = [SELECT Id, Monto__c, ConceptoPago__r.Name, OfertaEducativa__c FROM OfertaConceptoPagos__c  WHERE OfertaEducativa__c =: ofe];
        for(OfertaConceptoPagos__c mont: listMontos){
            montos.put(mont.ConceptoPago__r.Name, String.valueOf(mont.Monto__c));
        }
        return montos;
    }
    
    global class InfoWrapper{
        public String dataId {get;set;}
        public String parent {get;set;}
        public String name {get;set;}
    	
        public InfoWrapper(){}
    }
    
    global class ItemWrapper{
        public List<InfoWrapper> items {get;set;}
        public String titulo {get; set;}
        public ItemWrapper(String titulo){
            items = new List<InfoWrapper>();
            this.titulo = titulo;
        }
        
    }
    
    global class ComboWrapper{
        public ItemWrapper modalidad {get;set;}
        public ItemWrapper nivel {get;set;}
        public ItemWrapper plantel {get;set;}
        public ItemWrapper programa {get;set;}
        
        public ComboWrapper(){
            modalidad = new ItemWrapper('Modalidad');
            nivel = new ItemWrapper('Nivel');
            plantel = new ItemWrapper('Plantel');
            programa = new ItemWrapper('Programa');
        }
    }
    
 /*   global class ComboUbicacionWrapper{
        public ItemWrapper pais {get;set;}
        public ItemWrapper estado {get;set;}
        public ItemWrapper municipio {get;set;}
        
        public ComboUbicacionWrapper(){
            pais = new ItemWrapper('País');
            estado = new ItemWrapper('Estado');
            municipio = new ItemWrapper('Municipio');
        }
    }*/
}