src/objects/Catalogo__c.object
<CustomObject>
    <label>Catálogo</label>
    <nameField>
        <label>Nombre de Catálogo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catálogos</pluralLabel>
    <recordTypes>
        <fullName>Nivel</fullName>
        <active>true</active>
        <description>Crear nuevo registro del tipo Nivel</description>
        <label>Nivel</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FichaPago__c.object
<CustomObject>
    <fields>
        <fullName>CadenaCodigo__c</fullName>
        <formula>PrefijoIdentificador__c &amp;( Name ) &amp; 
TEXT( YEAR( Hasta__c ) ) &amp; 
IF( LEN(TEXT(MONTH(Hasta__c)))&gt;1, TEXT( MONTH(Hasta__c)), &apos;0&apos;&amp; TEXT(MONTH(Hasta__c))) &amp; 
IF( LEN(TEXT(DAY(Hasta__c)))&gt;1, TEXT( DAY(Hasta__c)), &apos;0&apos;&amp; TEXT(DAY(Hasta__c))) &amp;
LPAD(TEXT(FLOOR(TotaPagar__c) ), 5,&quot;0&quot;) &amp;
RPAD(
   SUBSTITUTE(TEXT(TotaPagar__c - FLOOR(TotaPagar__c) ), &quot;0.&quot;, &quot;&quot;) ,2,&quot;0&quot;
   )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cadena para código</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConceptoEspecial__c</fullName>
        <defaultValue>&quot;prueba&quot;</defaultValue>
        <label>Concepto</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Concepto__c</fullName>
        <formula>CASE(TEXT( TipoFicha__c ), 
&quot;Nivel Doctorado&quot;, &quot;Examen de Admisión e Inscripción&quot;, 
&quot;Nivel&quot;, &quot;Inscripción&quot;, 
&quot;Promoción Cero&quot;, &quot;Cuota primer colegiatura&quot;,
&quot;Ficha Especial&quot;, &quot;Diferencia de mensualidad&quot;,
&quot;Ficha Móvil&quot;, &quot;El importe incluye &quot; &amp;  TEXT(Descuento__c * 100) &amp; &quot;% de descuento.  &quot; &amp; BR() &amp; &quot;Cuota de inscripción&quot;,
&quot;N/A&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Concepto</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CondensacionFecha__c</fullName>
        <formula>LPAD(TEXT(((YEAR(Hasta__c) - 2013) * 372) + ( ( MONTH(Hasta__c) -1) * 31) + ( DAY(Hasta__c) - 1)), 4, &quot;0&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Condensación de fecha</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Constante__c</fullName>
        <formula>CASE(TEXT( TipoFicha__c ), 
&quot;Nivel Doctorado&quot;, &quot;1&quot;, 
&quot;Nivel&quot;, &quot;2&quot;, 
&quot;Promoción Cero&quot;, &quot;3&quot;, 
&quot;Ficha Especial&quot;, &quot;4&quot;, 
&quot;Ficha Móvil&quot;, &quot;5&quot;, 
&quot;0&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Constante</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hasta__c</fullName>
        <label>Hasta el</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Fichas de pago</relationshipLabel>
        <relationshipName>Fichas_de_pago</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Nivel</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Nivel</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Fichas de pago</relationshipLabel>
        <relationshipName>Fichas_de_pago</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NotaEspecial__c</fullName>
        <label>Nota</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Notas1__c</fullName>
        <formula>&quot;Una vez realizado el pago no habrá devolución.&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Notas 1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notas2__c</fullName>
        <formula>&quot;Si se requiere factura, favor de solicitar el mismo día de pago.&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Notas 2</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Fichas de pago</relationshipLabel>
        <relationshipName>Fichas_de_pago</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProgramasRelacionados__c</fullName>
        <label>Programas Relacionados</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RecibimosDe__c</fullName>
        <label>Recibimos de</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReferenciaCliente__c</fullName>
        <formula>&quot;600000&quot;&amp; Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Referencia del cliente</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReferenciaHSBC__c</fullName>
        <externalId>true</externalId>
        <label>Referencia HSBC</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ReferenciaOXXO__c</fullName>
        <externalId>true</externalId>
        <label>Referencia OXXO</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TotaPagar__c</fullName>
        <label>Total a pagar</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Ficha de pago</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fichas de pago</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Instituto__c.object
<CustomObject>
    <label>Instituto</label>
    <nameField>
        <label>Nombre de Instituto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Institutos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>FichaPago__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Ficha de Pago</description>
        <label>Con ficha pago</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Nivel</description>
        <label>Nivel</label>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Candidatos (Nivel)</relationshipLabel>
        <relationshipName>Nivel</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Plantel</description>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Candidatos</relationshipLabel>
        <relationshipName>Plantel</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Plantel__c.object
<CustomObject>
    <fields>
        <fullName>Instituto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Instituto</label>
        <referenceTo>Instituto__c</referenceTo>
        <relationshipLabel>Planteles</relationshipLabel>
        <relationshipName>Planteles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plantel</label>
    <nameField>
        <label>Plantel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planteles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GenerarPDFFichaPagoCtrl.cls
public with sharing class GenerarPDFFichaPagoCtrl {
    Public FichaPago__c idToken {get; set;}
    
    public GenerarPDFFichaPagoCtrl(ApexPages.StandardController controller ){
        idToken = (FichaPago__c)controller.getRecord();
    }
    
    public void sendMail(){
        
        system.debug('sendmail id '+idToken.Id );
        FichaPago__c ord = [SELECT Id, ReferenciaCliente__c, RecordType.Name, ConceptoEspecial__c,Concepto__c, RecibimosDe__c, TotaPagar__c,
                            Notas1__c, Notas2__c, NotaEspecial__c, Name, CondensacionFecha__c, Constante__c, CadenaCodigo__c,
                            Lead__r.Email, Hasta__c, Plantel__r.Instituto__r.Encabezado__c, ProgramasRelacionados__c, Lead__r.Nivel__r.Name,
                            ReferenciaOXXO__c, ReferenciaHSBC__c FROM FichaPago__c WHERE Id = :idToken.Id];
        system.debug('ord.RecordType.Name--> '+ord.RecordType.Name);
        
         system.debug('ord.Lead__r.Nivel__r.Name--> '+ord.Lead__r.Nivel__r.Name);
        if(ord.RecordType.Name == 'Ficha Especial'){
            BarCodeLeadCtrl.sendMail(ord.Hasta__c, ord.NotaEspecial__c,'', ord.ConceptoEspecial__c, ord.Lead__r.Email, ord.RecibimosDe__c, ord.Name, String.valueOf(ord.TotaPagar__c), ord.ReferenciaHSBC__c, ord.ReferenciaOXXO__c, String.valueOf(ord.Plantel__r.Instituto__r.Encabezado__c));
        }else if(ord.RecordType.Name == 'Ficha de Nivel'){
            if(ord.Lead__r.Nivel__r.Name == 'Cursos y Diplomados'){
                BarCodeLeadCtrl.sendMail(ord.Hasta__c, ord.Notas1__c, ord.Notas2__c, ord.Concepto__c, ord.Lead__r.Email, ord.RecibimosDe__c, ord.Name, String.valueOf(ord.TotaPagar__c), ord.ReferenciaHSBC__c, ord.ReferenciaOXXO__c, String.valueOf('INSTITUTO_NIVEL2'));
            }else{        
             
                BarCodeLeadCtrl.sendMail(ord.Hasta__c, ord.Notas1__c, ord.Notas2__c, ord.Concepto__c, ord.Lead__r.Email, ord.RecibimosDe__c, ord.Name, String.valueOf(ord.TotaPagar__c), ord.ReferenciaHSBC__c, ord.ReferenciaOXXO__c, String.valueOf(ord.Plantel__r.Instituto__r.Encabezado__c));
            }
        }
        
    }
}