src/objects/Catalogo__c.object
<CustomObject>
    <fields>
        <fullName>TipoCatalogo__c</fullName>
        <label>Tipo catálogo</label>
        <picklist>
            <picklistValues>
                <fullName>Concepto Pagos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nivel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Modalidad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requisitos de Beca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turno</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Periodicidad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Profesión</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forma de pago</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banco</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Catálogo</label>
    <nameField>
        <label>Nombre de Catálogo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catálogos</pluralLabel>
    <recordTypes>
        <fullName>Nivel</fullName>
        <active>true</active>
        <description>Crear nuevo registro del tipo Nivel</description>
        <label>Nivel</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Descuento__c.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Descuentos</relationshipLabel>
        <relationshipName>Descuentos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Nivel</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Nivel</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Descuentos</relationshipLabel>
        <relationshipName>Descuentos</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Descuento</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Descuentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FichaPago__c.object
<CustomObject>
    <fields>
        <fullName>Descuento__c</fullName>
        <label>Descuento</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>FolioLead__c</fullName>
        <label>Folio de lead / oportunidad</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hasta__c</fullName>
        <label>Hasta el</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Importe__c</fullName>
        <label>Importe</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Fichas de pago</relationshipLabel>
        <relationshipName>Fichas_de_pago</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MontoPagado__c</fullName>
        <label>Monto pagado</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Nivel</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Nivel</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Fichas de pago</relationshipLabel>
        <relationshipName>Fichas_de_pago</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Fichas de pago</relationshipLabel>
        <relationshipName>Fichas_de_pago</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecibimosDe__c</fullName>
        <label>Recibimos de</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TotaPagar__c</fullName>
        <label>Total a pagar</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Ficha de pago</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fichas de pago</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Calle__c</fullName>
        <label>Calle</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FichaPago__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Ficha de Pago</description>
        <label>Con ficha pago</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Folio__c</fullName>
        <displayFormat>C-{000000}</displayFormat>
        <externalId>true</externalId>
        <label>Folio</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Nivel</description>
        <label>Nivel</label>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Candidatos (Nivel)</relationshipLabel>
        <relationshipName>Nivel</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Plantel</description>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Candidatos</relationshipLabel>
        <relationshipName>Plantel</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Ventas</fullName>
        <active>true</active>
        <businessProcess>Ventas</businessProcess>
        <label>Ventas</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Negocio__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuraciones  globales</description>
    <fields>
        <fullName>Folio__c</fullName>
        <description>Número de folio consecutivo para candidatos y prospéctos</description>
        <inlineHelpText>Número de folio consecutivo para candidatos y prospéctos</inlineHelpText>
        <label>Folio</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Negocio</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Folio__c</fullName>
        <label>Folio</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Nivel</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Nivel</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Oportunidades (Nivel)</relationshipLabel>
        <relationshipName>Oportunidades1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Oportunidades</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Plantel__c.object
<CustomObject>
    <fields>
        <fullName>Calle__c</fullName>
        <label>Calle</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RazonSocial__c</fullName>
        <label>Razón social</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Plantel</label>
    <nameField>
        <label>Plantel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planteles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FichaPagoOpportunityCtrlTest.cls
@isTest   public class FichaPagoOpportunityCtrlTest {
    @IsTest   public static void createPayToken(){
        
        RecordType rt =[select id,Name, sObjectType from RecordType where sObjectType='Lead' AND NAME ='Ventas'  limit 1];
       System.debug('id del query '+rt.Id); 
         System.debug('Name del query '+rt.Name); 
         System.debug('SobjectType del query '+rt.SobjectType); 
        Negocio__c configuracionNegocio = Negocio__c.getOrgDefaults();
        upsert configuracionNegocio;
        Integer nextFolio = configuracionNegocio.Folio__c != null ? Integer.valueOf(configuracionNegocio.Folio__c) : 0;
        nextFolio = nextFolio + 1;
        
        Catalogo__c cat = new Catalogo__c(Name='Doctorado',
                                          TipoCatalogo__c='Nivel'
                                         );
        
        insert cat;
        Plantel__c plan = new Plantel__c (Calle__c='demo',
                                          RazonSocial__c='demo'
                                         );
        insert  plan;
        
        Opportunity opp=new Opportunity(Name='demodan',
                                        StageName ='dd',
                                        CloseDate= Date.today()
                                        ,Folio__c='9983434',
                                        Nivel__c=cat.Id,
                                        Plantel__c=plan.Id,
                                      RecordTypeId=rt.Id
                                       );
        insert opp;
        
        
      
        Lead lead = new  Lead(LastName='demo',
                              Folio__c = String.valueOf(nextFolio),
                              Nivel__c=cat.id
                             );
        lead.Email='dsanchez@ctconsulting.com.mx';
        insert lead;
        
        FichaPago__c fp = new FichaPago__c(Importe__c=33330,
                                           Descuento__c=4,
                                           FolioLead__c= nextFolio,
                                           Hasta__c =Date.today(),
                                           MontoPagado__c =4545,
                                           TotaPagar__c =4444,
                                            Lead__c=lead.Id,
                                           RecibimosDe__c='demo' 
                                          );
        
        insert fp;
        ApexPages.StandardController controller = new ApexPages.StandardController(opp);
        Test.setCurrentPageReference(new pageReference('Page.mypage'));
       

        FichaPagoOpportunityCtrl obj = new FichaPagoOpportunityCtrl(controller);
        
        obj.createPayToken();
    }
}