src/objects/Catalogo__c.object
<CustomObject>
    <fields>
        <fullName>TipoCatalogo__c</fullName>
        <label>Tipo catálogo</label>
        <picklist>
            <picklistValues>
                <fullName>Concepto Pagos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nivel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Modalidad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requisitos de Beca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turno</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Periodicidad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Profesión</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forma de pago</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banco</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Catálogo</label>
    <nameField>
        <label>Nombre de Catálogo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catálogos</pluralLabel>
    <recordTypes>
        <fullName>Modalidad</fullName>
        <active>true</active>
        <description>Crear nuevo registro del tipo Modalidad</description>
        <label>Modalidad</label>
    </recordTypes>
    <recordTypes>
        <fullName>Nivel</fullName>
        <active>true</active>
        <description>Crear nuevo registro del tipo Nivel</description>
        <label>Nivel</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Modalidad__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Modalidad</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Modalidad</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Candidatos (Modalidad)</relationshipLabel>
        <relationshipName>Candidatos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Nivel</description>
        <label>Nivel</label>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Candidatos (Nivel)</relationshipLabel>
        <relationshipName>Nivel</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OfertaEducativa__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Búsqueda de Oferta Educativa para el Canidato</description>
        <label>Oferta educativa</label>
        <referenceTo>OfertaEducativa__c</referenceTo>
        <relationshipLabel>Candidatos</relationshipLabel>
        <relationshipName>Candidatos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Periodo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Periodo</description>
        <label>Periodo</label>
        <referenceTo>Periodo__c</referenceTo>
        <relationshipLabel>Periodo</relationshipLabel>
        <relationshipName>Periodo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Plantel</description>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Candidatos</relationshipLabel>
        <relationshipName>Plantel</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Programa__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Programa</description>
        <label>Programa</label>
        <referenceTo>Programa__c</referenceTo>
        <relationshipLabel>Candidatos</relationshipLabel>
        <relationshipName>Programa</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/OfertaEducativa__c.object
<CustomObject>
    <fields>
        <fullName>Estatus__c</fullName>
        <label>Estatus</label>
        <picklist>
            <picklistValues>
                <fullName>Activo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactivo</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Modalidad__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Modalidad</inlineHelpText>
        <label>Modalidad</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Modalidad</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Ofertas Educativas</relationshipLabel>
        <relationshipName>Ofertas_Educativas</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Nivel</inlineHelpText>
        <label>Nivel</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Nivel</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Ofertas Educativas (Nivel)</relationshipLabel>
        <relationshipName>Ofertas_Educativas1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Periodo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Periodo</label>
        <referenceTo>Periodo__c</referenceTo>
        <relationshipLabel>Ofertas Educativas</relationshipLabel>
        <relationshipName>Ofertas_Educativas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Plantel</inlineHelpText>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Ofertas Educativas</relationshipLabel>
        <relationshipName>Ofertas_Educativas</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Programa__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Programa</inlineHelpText>
        <label>Programa</label>
        <referenceTo>Programa__c</referenceTo>
        <relationshipLabel>Ofertas Educativas</relationshipLabel>
        <relationshipName>Ofertas_Educativas</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Oferta Educativa</label>
    <nameField>
        <displayFormat>OE-{0000000}</displayFormat>
        <label>Oferta Educativa</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ofertas Educativas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Periodo__c.object
<CustomObject>
    <fields>
        <fullName>ActivoEjecutiva__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activo ejecutiva</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ActivoOnline__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activo online</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ActivoPresencial__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activo presencial</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Activo__c</fullName>
        <label>Estatus</label>
        <picklist>
            <picklistValues>
                <fullName>Activo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactivo</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Periodo</label>
    <nameField>
        <label>Periodo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Periodos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Plantel__c.object
<CustomObject>
    <label>Plantel</label>
    <nameField>
        <label>Plantel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planteles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Programa__c.object
<CustomObject>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Nivel</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Nivel</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Programas</relationshipLabel>
        <relationshipName>Programas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Programas</relationshipLabel>
        <relationshipName>Programas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Programa</label>
    <nameField>
        <label>Programa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Ubicacion__c.object
<CustomObject>
    <description>Listado que contiene: País, estados y municipios</description>
    <fields>
        <fullName>IdEstadoPais__c</fullName>
        <description>Aplica para municipio y estado</description>
        <label>Id Estado/País</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IdUbicacion__c</fullName>
        <label>Id</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TipoUbicacion__c</fullName>
        <label>Tipo</label>
        <picklist>
            <picklistValues>
                <fullName>Estado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>País</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Municipio</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Ubicación</label>
    <nameField>
        <label>Nombre de Ubicación</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ubicaciones</pluralLabel>
    <recordTypes>
        <fullName>Estado</fullName>
        <active>true</active>
        <label>Estado</label>
    </recordTypes>
    <recordTypes>
        <fullName>Municipio</fullName>
        <active>true</active>
        <label>Municipio</label>
    </recordTypes>
    <recordTypes>
        <fullName>Pais</fullName>
        <active>true</active>
        <label>Pais</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LNP_OfertaEducativaService.cls
@RestResource(urlMapping='/OfertaEducativaService/*')
global with sharing class LNP_OfertaEducativaService {
    @HttpGet
    global static void getList() {
        RestContext.response.addHeader('Content-Type', 'application/json');
        String pageRef = RestContext.request.params.get('page');
        String nivel = RestContext.request.params.get('nivel');
        String ofe = RestContext.request.params.get('ofe');
        String modalidad = RestContext.request.params.get('modalidad');
        String plantel = RestContext.request.params.get('plantel');
        String respuesta = 'ERROR';
        //Ubicacion
        String pais_input = RestContext.request.params.get('paisInput');
        String pais = RestContext.request.params.get('pais');
        String Estado = RestContext.request.params.get('estado');
        
        if(pageRef == '1'){
            if((modalidad != null && modalidad != '0') && (nivel == null || String.isEmpty(nivel) )){
                respuesta = getNiveles(modalidad);
            }else if((nivel != null && nivel != '0') && (plantel == null || String.isEmpty(plantel))){
                respuesta = getPlantel(nivel, modalidad);
            }else if(plantel != null && plantel != '0'){
                respuesta = getPrograma(nivel, modalidad, plantel);
            }
        }else if(pageRef == '0'){
            /*if(ofe != null && ofe != '0' && !String.isEmpty(ofe)){
                respuesta = getDataOfert(ofe, modalidad);
            }else */
            if((modalidad != null && modalidad != '0') && (nivel == null || String.isEmpty(nivel) )){
                respuesta = getNiveles(modalidad);
            }else if(nivel != null && nivel != '0'){
                respuesta = getPrograma(nivel, modalidad,'');
            }            
        }
        else if(pageRef == '2'){
            if((pais != null && pais != '0') && (estado == null || String.isEmpty(estado) )){
                respuesta = getEstados(pais);
            }
            else if((estado != null && estado != '0')){
                respuesta = getMunicipios(pais, estado);
            }
            else if((pais_input.equals('pais')) && (pais == null)){
                respuesta = getPaises();
            }
            
        }
        RestContext.response.responseBody = Blob.valueOf(respuesta);
    }
    
    global static String getNiveles(String modalidad){
    	String sqlModalidad = '';
    	String respuesta = '\"0\" : \"-Seleccione Grado-\",';
        String queryTipoModalidad = 'SELECT Id, Name FROM Catalogo__c WHERE TipoCatalogo__c = \'Modalidad\' ORDER BY Name';
        List<Catalogo__c> listTipoModalidad = (List<Catalogo__c>) Database.query(queryTipoModalidad);
        
		String query = 'SELECT Id,Name FROM Periodo__c WHERE Activo__c = \'Activo\' ';
        if(modalidad.equals(listTipoModalidad[2].Id)){
            query += 'AND ActivoPresencial__c = true';
        }else if(modalidad.equals(listTipoModalidad[1].Id)){
            query += 'AND ActivoOnline__c = true';
        }else if(modalidad.equals(listTipoModalidad[0].Id)){
            query += 'AND ActivoEjecutiva__c = true';
        }
        else{
            query = '';
        }
        
    	try{
        	List<Periodo__c> listPeriod= (List<Periodo__c>) Database.query(query);
        	Periodo__c periodo = listPeriod[0];
	        if(periodo != null){
	        	AggregateResult[] groupedResults = [SELECT Nivel__r.Name label,Nivel__c key 
                                                    FROM OfertaEducativa__c 
                                                    WHERE Periodo__c =: periodo.Id
                                                    	AND (Nivel__r.Name = 'Licenciatura' OR  Nivel__r.Name = 'Maestría' OR Nivel__r.Name = 'Doctorado')
                                                    	AND Estatus__c = 'Activo'
                                                    	AND Modalidad__c =: modalidad
                                                    GROUP BY  Nivel__r.Name,Nivel__c ];
	        	for (AggregateResult ar : groupedResults)  {
	        		respuesta += '"' + ar.get('key') + '" : "' +  ar.get('label') + '",';
	        	}
	        }
    	}catch(Exception e ){
    		respuesta = 'ERROR: ' + e.getMessage() + ' .Query: ' + query;
    	}
        respuesta = respuesta.removeEnd(',');
    	return '{' + respuesta +'}';
    }
    
    global static String getPrograma(String nivel, String modalidad, String plantel){
    	String sqlnivel = '';
    	String respuesta = '\"0\" : \"-Oferta Académica-\",';
        String queryTipoModalidad = 'SELECT Id, Name FROM Catalogo__c WHERE TipoCatalogo__c = \'Modalidad\' ORDER BY Name';
        List<Catalogo__c> listTipoModalidad = (List<Catalogo__c>) Database.query(queryTipoModalidad);
        String queryPlantel = 'SELECT id FROM Plantel__c WHERE Name=\'UNIVERSIDAD VIRTUAL\'';
        List<Plantel__c> listPlantel = (List<Plantel__c>) Database.query(queryPlantel);
        
        String query = 'SELECT Id,Name FROM Periodo__c WHERE Activo__c = \'Activo\' ';
        if(modalidad.equals(listTipoModalidad[2].Id)){
            query += 'AND ActivoPresencial__c = true';
        }else if(modalidad.equals(listTipoModalidad[1].Id)){
            query += 'AND ActivoOnline__c = true';
        }else if(modalidad.equals(listTipoModalidad[0].Id)){
            query += 'AND ActivoEjecutiva__c = true';
        }
        else{
            query = '';
        }
        
    	try{
        	List<SObject> listPeriod= (List<SObject>) Database.query(query);
        	SObject periodo = listPeriod[0];
            if(periodo != null){
                List<OfertaEducativa__c> listPeriod2;
                if(!String.isEmpty(plantel)){
                    listPeriod2 = (List<OfertaEducativa__c>) Database.query('SELECT Id, Programa__c, Programa__r.Name FROM OfertaEducativa__c WHERE Periodo__c = \''+ periodo.Id + '\' AND Nivel__c = \''+nivel+ '\' AND Modalidad__c =\''+ modalidad+ '\' AND Plantel__c =\''+ plantel+ '\' AND Estatus__c = \'Activo\' ORDER BY Programa__r.Name ASC');
                    for (OfertaEducativa__c ar : listPeriod2){                    
                        respuesta += '"' + ar.Id+ '" : "' +  ar.Programa__r.Name + '",';
                    }
                }else{
                    listPeriod2 = (List<OfertaEducativa__c>) Database.query('SELECT Id, Programa__r.Name FROM OfertaEducativa__c WHERE Periodo__c = \''+ periodo.Id + '\' AND Nivel__c = \''+nivel+ '\' AND Modalidad__c =\''+ listTipoModalidad[1].Id +'\' AND Plantel__c=\''+ listPlantel[0].id +'\' AND Estatus__c = \'Activo\' ORDER BY Programa__r.Name ASC');
                    for (OfertaEducativa__c ar : listPeriod2){                    
                        respuesta += '"' + ar.Id + '" : "' +  ar.Programa__r.Name + '",';
                    }
                }
	        }
    	}catch(Exception e ){
    		respuesta = 'ERROR: ' + e.getMessage() + ' .Query: ' + query;
    	}
        respuesta = respuesta.removeEnd(',');
    	return '{' + respuesta +'}';
    }
    
    global static String getPlantel(String nivel, String modalidad){
        String sqlnivel = '';
        String respuesta = '\"0\" : \"-Plantel educativo-\",';
        String queryTipoModalidad = 'SELECT Id, Name FROM Catalogo__c WHERE TipoCatalogo__c = \'Modalidad\' ORDER BY Name';
        List<Catalogo__c> listTipoModalidad = (List<Catalogo__c>) Database.query(queryTipoModalidad);
        
        String query = 'SELECT Id,Name FROM Periodo__c WHERE Activo__c = \'Activo\' ';
        if(modalidad.equals(listTipoModalidad[2].Id)){
            query += 'AND ActivoPresencial__c = true';
        }else if(modalidad.equals(listTipoModalidad[1].Id)){
            query += 'AND ActivoOnline__c = true';
        }else if(modalidad.equals(listTipoModalidad[0].Id)){
            query += 'AND ActivoEjecutiva__c = true';
        }
        else{
            query = '';
        }
        
        try{
            List<SObject> listPeriod= (List<SObject>) Database.query(query);
            SObject periodo = listPeriod[0];
            if(periodo != null){
                List<OfertaEducativa__c> listPeriod2 = (List<OfertaEducativa__c>) Database.query('SELECT Id, Plantel__c, Plantel__r.Name FROM OfertaEducativa__c WHERE Periodo__c = \''+ periodo.Id + '\' AND Nivel__c = \''+nivel+ '\' AND Modalidad__c =\''+ modalidad+ '\' AND Estatus__c = \'Activo\' ORDER BY Plantel__r.Name ASC');
                System.debug(listPeriod2);
                for (OfertaEducativa__c ar : listPeriod2){                    
                    respuesta += '"' + ar.Plantel__c + '" : "' +  ar.Plantel__r.Name + '",';
                }
            }
        }catch(Exception e ){
            respuesta = 'ERROR: ' + e.getMessage() + ' .Query: ' + query;
        }
        respuesta = respuesta.removeEnd(',');
        return '{' + respuesta +'}';
        
    }
    
    /*----------------------Ubicacion--------------------------*/
    global static String getPaises(){
        String respuesta = '\"0\" : \"--Seleccionar--\",';
        String query = 'SELECT IdUbicacion__c, Name FROM Ubicacion__c WHERE TipoUbicacion__c= \'País\' ORDER BY Name';
        try{
            List<Ubicacion__c> listPaises= (List<Ubicacion__c>) Database.query(query);
            if(listPaises.size() != 0){
                for (Ubicacion__c pa : listPaises){                    
                    respuesta += '"' + pa.IdUbicacion__c + '" : "' +  pa.Name + '",';
                }
            }
        }catch(Exception e ){
            respuesta = 'ERROR: ' + e.getMessage() + ' .Query: ' + query;
        }
        respuesta = respuesta.removeEnd(',');
        return '{'+ respuesta +'}';
    }
    
    global static String getEstados(String pais){
        String respuesta = '\"0\" : \"--Seleccionar--\",';
        String query = 'SELECT IdUbicacion__c, Name FROM Ubicacion__c WHERE TipoUbicacion__c= \'Estado\' AND IdEstadoPais__c = \''+pais+'\' ORDER BY Name';
        try{
            if(pais.equals('157')){
                List<Ubicacion__c> listEstados= (List<Ubicacion__c>) Database.query(query);
                if(listEstados.size() != 0){
                    for (Ubicacion__c es : listEstados){                    
                        respuesta += '"' + es.IdUbicacion__c + '" : "' +  es.Name + '",';
                    }
                }
            }
            else{
                respuesta = '\"-1\" : \"--No aplica--\",';
            }
        }catch(Exception e ){
            respuesta = 'ERROR: ' + e.getMessage() + ' .Query: ' + query;
        }
        respuesta = respuesta.removeEnd(',');
        return '{'+ respuesta +'}';
    }
    global static String getMunicipios(String pais, String estado){
        String respuesta = '\"0\" : \"--Seleccionar--\",';
        String query = 'SELECT IdUbicacion__c, Name FROM Ubicacion__c WHERE TipoUbicacion__c= \'Municipio\' AND IdEstadoPais__c = \''+estado+'\' ORDER BY Name';
        try{
            if(pais.equals('157')){
                List<Ubicacion__c> listMuicipios= (List<Ubicacion__c>) Database.query(query);
                if(listMuicipios.size() != 0){
                    for (Ubicacion__c mun : listMuicipios){                    
                        respuesta += '"' + mun.IdUbicacion__c + '" : "' +  mun.Name + '",';
                    }
                }
            }
            else{
                respuesta = '\"-1\" : \"--No Disponible--\",';
            }
        }catch(Exception e ){
            respuesta = 'ERROR: ' + e.getMessage() + ' .Query: ' + query;
        }
        respuesta = respuesta.removeEnd(',');
        return '{'+ respuesta +'}';
    }
    
    public class WrapperOferta{
        public Periodo__c periodo {get; set;}
        public String grupo {get; set;}
        public List<String> conceptos {get; set;}
        public List<String> becas {get; set;}
        
        public WrapperOferta(){
            
        }
    }
}