src/objects/Catalogo__c.object
<CustomObject>
    <label>Catálogo</label>
    <nameField>
        <label>Nombre de Catálogo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catálogos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>ColegiaturaDescuento__c</fullName>
        <formula>Colegiatura__c -( Colegiatura__c *  PorcentajeBeca__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Colegiatura con descuento</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Colegiatura__c</fullName>
        <label>Colegiatura</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FolioCalculadora__c</fullName>
        <formula>IF(TEXT(TipoBeca__c)= &quot;Beca Calculadora&quot;, &quot;CAL&quot; &amp; text(DAY( datevalue(CreatedDate) ))&amp;text(month( datevalue(CreatedDate) ))&amp; text(year( datevalue(CreatedDate) ))&amp;  Folio__c,&quot; &quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Folio calculadora</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InscripcionDescuento__c</fullName>
        <formula>IF( AplicaPromocionCero__c , 0, Inscripcion__c -( Inscripcion__c * PorcentajeDescuento__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Inscripción con descuento</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Inscripcion__c</fullName>
        <description>Monto de la Inscripción</description>
        <label>Inscripción</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Modalidad__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Modalidad</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Modalidad</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Candidatos (Modalidad)</relationshipLabel>
        <relationshipName>Candidatos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Nivel</description>
        <label>Nivel</label>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Candidatos (Nivel)</relationshipLabel>
        <relationshipName>Nivel</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Numero_Mensualidades__c</fullName>
        <formula>OfertaEducativa__r.NumeroColegiaturas__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Numero Mensualidades</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OfertaEducativa__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Búsqueda de Oferta Educativa para el Canidato</description>
        <label>Oferta educativa</label>
        <referenceTo>OfertaEducativa__c</referenceTo>
        <relationshipLabel>Candidatos</relationshipLabel>
        <relationshipName>Candidatos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Plantel</description>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Candidatos</relationshipLabel>
        <relationshipName>Plantel</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PorcentajeBeca__c</fullName>
        <description>Porcentaje de descuento en colegiaturas</description>
        <inlineHelpText>Porcentaje de beca en colegiatura</inlineHelpText>
        <label>% de beca en colegiatura</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>PorcentajeDescuento__c</fullName>
        <description>Porcentaje de descuento en inscripción</description>
        <label>% de descuento en inscripción</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Programa__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Programa</description>
        <label>Programa</label>
        <referenceTo>Programa__c</referenceTo>
        <relationshipLabel>Candidatos</relationshipLabel>
        <relationshipName>Programa</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Promedio__c</fullName>
        <globalPicklist>Promedio</globalPicklist>
        <label>Promedio</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>VigenciaDescuento__c</fullName>
        <label>Vigencia de descuento</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Materia__c.object
<CustomObject>
    <fields>
        <fullName>Modalidad__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Modalidad</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Modalidad</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Materias (Modalidad)</relationshipLabel>
        <relationshipName>Modalidad</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Nivel</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Nivel</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Materias</relationshipLabel>
        <relationshipName>Materias</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Materias</relationshipLabel>
        <relationshipName>Materias</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Programa__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Programa</label>
        <referenceTo>Programa__c</referenceTo>
        <relationshipLabel>Materias</relationshipLabel>
        <relationshipName>Materias</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Materia</label>
    <nameField>
        <label>Materia</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OfertaEducativa__c.object
<CustomObject>
    <fields>
        <fullName>Modalidad__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Modalidad</inlineHelpText>
        <label>Modalidad</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Modalidad</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Ofertas Educativas</relationshipLabel>
        <relationshipName>Ofertas_Educativas</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Nivel</inlineHelpText>
        <label>Nivel</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Nivel</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Ofertas Educativas (Nivel)</relationshipLabel>
        <relationshipName>Ofertas_Educativas1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Plantel</inlineHelpText>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Ofertas Educativas</relationshipLabel>
        <relationshipName>Ofertas_Educativas</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Programa__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Programa</inlineHelpText>
        <label>Programa</label>
        <referenceTo>Programa__c</referenceTo>
        <relationshipLabel>Ofertas Educativas</relationshipLabel>
        <relationshipName>Ofertas_Educativas</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Oferta Educativa</label>
    <nameField>
        <displayFormat>OE-{0000000}</displayFormat>
        <label>Oferta Educativa</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ofertas Educativas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Plantel__c.object
<CustomObject>
    <label>Plantel</label>
    <nameField>
        <label>Plantel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planteles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Programa__c.object
<CustomObject>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Nivel</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Nivel</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Programas</relationshipLabel>
        <relationshipName>Programas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Programas</relationshipLabel>
        <relationshipName>Programas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Programa</label>
    <nameField>
        <label>Programa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PlantillaCalculoRegistradoController.cls
public with sharing class PlantillaCalculoRegistradoController {
    public Id id {get; set;}
	public String promedio {get; set;}
    public String descuentoInsc {get; set;}
    public String descuentoMens {get; set;}
    public Double inscripcionDescuento {get; set;}
    public Double colegiaturaDescuento {get; set;}
    public String vigencia {get; set;}
    public Lead lead {get; set;}
    
    public PlantillaCalculoRegistradoController(){
        id = apexpages.currentpage().getparameters().get('id');
        promedio = apexpages.currentpage().getparameters().get('prom');
        descuentoInsc = apexpages.currentpage().getparameters().get('descInsc');
        descuentoMens = apexpages.currentpage().getparameters().get('descMens');
        vigencia = apexpages.currentpage().getparameters().get('vig');
        lead = [Select Modalidad__r.Name, Nivel__r.Name, Plantel__r.Name, Programa__r.Name, Promedio__c, PorcentajeBeca__c, 
                FolioCalculadora__c, Inscripcion__c, InscripcionDescuento__c, PorcentajeDescuento__c, Colegiatura__c, 
                ColegiaturaDescuento__c, Numero_Mensualidades__c, VigenciaDescuento__c, OfertaEducativa__c  
                FROM Lead WHERE Id = : id ];
        lead.PorcentajeDescuento__c = Integer.valueOf(descuentoInsc);
        lead.PorcentajeBeca__c = Integer.valueOf(descuentoMens);
        lead.Promedio__c = promedio;
        lead.VigenciaDescuento__c = Date.valueOf(vigencia);
        inscripcionDescuento = Double.valueOf(lead.Inscripcion__c) * (1-(Double.valueOf(descuentoInsc)/100));
        colegiaturaDescuento= Double.valueOf(lead.Colegiatura__c) * (1-(Double.valueOf(descuentoMens)/100));
        
    }
    
    @future(callout=true)
    public static void sendMail(Id leadId, String mailLead, String promedioL, String descuentoInscL, String descuentoMensL, String vigenciaL){
        List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();        
        String hostUrl = URL.getSalesforceBaseUrl().getHost();
        String urlM ='';
        if ( ValidaEntorno.isSandbox()) { 
            urlM = 'https://sandbox-ieu.cs2.force.com/PlantillaCalculoRegistrado?Id=' + leadId + '&prom='+promedioL+'&descInsc='+descuentoInscL+'&descMens='+descuentoMensL+'&vig='+vigenciaL;
        } else { 
            urlM = 'https://c.cs2.visual.force.com/apex/PlantillaCalculoRegistrado?Id=' + leadId + '&prom='+promedioL+'&descInsc='+descuentoInscL+'&descMens='+descuentoMensL+'&vig='+vigenciaL;
        }
        
        PageReference pdf = new PageReference(urlM);
        
        Blob body = !Test.isRunningTest() ? pdf.getContent() : Blob.ValueOf('dummy text');
        
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setToAddresses(new String[] { mailLead });
        mail.setSubject('Cálculo de tu colegiatura');                
        mail.setHtmlBody(body.toString());
        //mail.setReplyTo(mailPromotor);
        mails.add(mail);  
        
        if(!mails.isEmpty())
        {
            Messaging.SendEmail(mails);
        }  
        
    }
    
}