src/objects/Descuento__c.object
<CustomObject>
    <fields>
        <fullName>Oportunidad__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Oportunidad</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Descuentos</relationshipLabel>
        <relationshipName>Descuentos</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Descuento</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Descuentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FichaPago__c.object
<CustomObject>
    <fields>
        <fullName>Descuento__c</fullName>
        <label>Descuento</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Importe__c</fullName>
        <label>Importe</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Oportunidad__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Oportunidad</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Fichas de pago</relationshipLabel>
        <relationshipName>Fichas_de_pago</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Fichas de pago</relationshipLabel>
        <relationshipName>Fichas_de_pago</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecibimosDe__c</fullName>
        <label>Recibimos de</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TipoFicha__c</fullName>
        <label>Tipo de ficha</label>
        <picklist>
            <picklistValues>
                <fullName>Nivel Doctorado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nivel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Promoción Cero</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ficha Especial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ficha Móvil</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TotaPagar__c</fullName>
        <label>Total a pagar</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Ficha de pago</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fichas de pago</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Oportunidades</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Plantel__c.object
<CustomObject>
    <label>Plantel</label>
    <nameField>
        <label>Plantel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planteles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FichaPagoEspecialOpportunityCtrl.cls
public with sharing class FichaPagoEspecialOpportunityCtrl {
   
    public FichaPago__c ficha {get; set;}
	public RecordType recordType;

    public FichaPagoEspecialOpportunityCtrl(ApexPages.StandardController controller){
    	
    	Opportunity opp = (Opportunity)controller.getRecord();
    	opp=[SELECT Id, Name, Plantel__c from Opportunity WHERE Id=:opp.Id];
    	
    	ficha = new FichaPago__c();
    	ficha.RecibimosDe__c = (opp.Name != null? opp.Name : '');
        ficha.Oportunidad__c = opp.Id;
        ficha.Plantel__c = opp.plantel__c;
        recordType = [SELECT Id,Name FROM RecordType WHERE SobjectType='FichaPago__c' AND Name='Ficha Especial'];
        ficha.TipoFicha__c = 'Ficha Especial';
        ficha.RecordTypeId = recordType.Id;
        
    }
    
    public PageReference saveToken(){
    	ficha.TotaPagar__c = ficha.Importe__c - (ficha.Importe__c * (ficha.Descuento__c / 100));
    	if (ficha != null){
    		insert ficha;
    	}
       
        return new PageReference('/' + ficha.Id);
    }
    
    public PageReference exit(){
        return new PageReference('/' + ficha.Oportunidad__c);
    }
    
    

}