src/objects/Descuento__c.object
<CustomObject>
    <label>Descuento</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Descuentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FichaPago__c.object
<CustomObject>
    <fields>
        <fullName>Descuento__c</fullName>
        <label>Descuento</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>FolioLead__c</fullName>
        <label>Folio de lead / oportunidad</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hasta__c</fullName>
        <label>Hasta el</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Importe__c</fullName>
        <label>Importe</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MontoPagado__c</fullName>
        <label>Monto pagado</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RecibimosDe__c</fullName>
        <label>Recibimos de</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TotaPagar__c</fullName>
        <label>Total a pagar</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Ficha de pago</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fichas de pago</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Negocio__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuraciones  globales</description>
    <fields>
        <fullName>Folio__c</fullName>
        <description>Número de folio consecutivo para candidatos y prospéctos</description>
        <inlineHelpText>Número de folio consecutivo para candidatos y prospéctos</inlineHelpText>
        <label>Folio</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Negocio</label>
</CustomObject>

src/objects/Programa__c.object
<CustomObject>
    <label>Programa</label>
    <nameField>
        <label>Programa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BarCodeMovilCtrlTest.cls
@IsTest public class BarCodeMovilCtrlTest {
    @IsTest   public static void sendMail(){
        String ids='34253434';
        BarCodeMovilCtrl.sendMail(ids);
    }
    @IsTest   public static void refactorDate(){
        
        BarCodeMovilCtrl.refactorDate(Date.today());
    }
    @IsTest   public static void getFichasFromString(){
        
        
        Negocio__c configuracionNegocio = Negocio__c.getOrgDefaults();
        upsert configuracionNegocio;
        Integer nextFolio = configuracionNegocio.Folio__c != null ? Integer.valueOf(configuracionNegocio.Folio__c) : 0;
        nextFolio = nextFolio + 1;
        FichaPago__c fp = new FichaPago__c(Importe__c=33330,
                                           Descuento__c=4,
                                           FolioLead__c= nextFolio,
                                           Hasta__c =Date.today(),
                                           MontoPagado__c =4545,
                                           TotaPagar__c =4444,
                                           RecibimosDe__c ='demo'
                                          );
        
        insert fp;
        
        String ids=fp.Id;
        BarCodeMovilCtrl.getFichasFromString(ids);
    }
    @IsTest   public static void getProgramasRelacionados(){
        
        Programa__c pr =new Programa__c(Name='demo');
        insert pr;
        String ids=pr.Id;
        BarCodeMovilCtrl.getProgramasRelacionados(ids);
    }
    @IsTest   public static void GetResourceURL(){
        
        List<StaticResource> resourceList= [SELECT Name FROM StaticResource limit 1];
        String resourceName=String.valueOf(resourceList.get(0));           
        BarCodeMovilCtrl.GetResourceURL(resourceName);
    }
 @IsTest   public static void encodeASCII(){
        
        String cadena='demo';
        BarCodeMovilCtrl.encodeASCII(cadena);
    }    
    @IsTest   public static void BarCodeMovilCtrl(){
      //  BarCodeMovilCtrl crtl = new BarCodeMovilCtrl();
      //crtl.BarCodeMovilCtrl();
       // BarCodeMovilCtrl.BarCodeMovilCtrl();
    }   
}