src/objects/Descuento__c.object
<CustomObject>
    <label>Descuento</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Descuentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FichaPago__c.object
<CustomObject>
    <fields>
        <fullName>Concepto__c</fullName>
        <formula>CASE(TEXT( TipoFicha__c ), 
&quot;Nivel Doctorado&quot;, &quot;Examen de Admisión e Inscripción&quot;, 
&quot;Nivel&quot;, &quot;Inscripción&quot;, 
&quot;Promoción Cero&quot;, &quot;Cuota primer colegiatura&quot;,
&quot;Ficha Especial&quot;, &quot;Diferencia de mensualidad&quot;,
&quot;Ficha Móvil&quot;, &quot;El importe incluye &quot; &amp;  TEXT(Descuento__c * 100) &amp; &quot;% de descuento.  &quot; &amp; BR() &amp; &quot;Cuota de inscripción&quot;,
&quot;N/A&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Concepto</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Descuento__c</fullName>
        <label>Descuento</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Hasta__c</fullName>
        <label>Hasta el</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Importe__c</fullName>
        <label>Importe</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Notas1__c</fullName>
        <formula>&quot;Una vez realizado el pago no habrá devolución.&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Notas 1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notas2__c</fullName>
        <formula>&quot;Si se requiere factura, favor de solicitar el mismo día de pago.&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Notas 2</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Fichas de pago</relationshipLabel>
        <relationshipName>Fichas_de_pago</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProgramasRelacionados__c</fullName>
        <label>Programas Relacionados</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ReferenciaHSBC__c</fullName>
        <externalId>true</externalId>
        <label>Referencia HSBC</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ReferenciaOXXO__c</fullName>
        <externalId>true</externalId>
        <label>Referencia OXXO</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TotaPagar__c</fullName>
        <label>Total a pagar</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Ficha de pago</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fichas de pago</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Instituto__c.object
<CustomObject>
    <fields>
        <fullName>Encabezado__c</fullName>
        <label>Encabezado</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Instituto</label>
    <nameField>
        <label>Nombre de Instituto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Institutos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>FichaPago__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Ficha de Pago</description>
        <label>Con ficha pago</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Plantel</description>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Candidatos</relationshipLabel>
        <relationshipName>Plantel</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Programa__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Programa</description>
        <label>Programa</label>
        <referenceTo>Programa__c</referenceTo>
        <relationshipLabel>Candidatos</relationshipLabel>
        <relationshipName>Programa</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Plantel__c.object
<CustomObject>
    <fields>
        <fullName>Instituto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Instituto</label>
        <referenceTo>Instituto__c</referenceTo>
        <relationshipLabel>Planteles</relationshipLabel>
        <relationshipName>Planteles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plantel</label>
    <nameField>
        <label>Plantel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planteles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Programa__c.object
<CustomObject>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Programas</relationshipLabel>
        <relationshipName>Programas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Programa</label>
    <nameField>
        <label>Programa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BarCodeMovilCtrl.cls
public with sharing class BarCodeMovilCtrl {

    public String hasta {get; set;}
    public String recibimosde {get; set;}
    public String pago {get; set;}
    public String nota1 {get; set;}
    public String nota2 {get; set;}
    public String folio {get; set;}
    public String HSBCRef {get; set;}
    public String cadenaCodigo {get; set;}
    public String concept {get; set;}
    public String encabezado {get; set;}
    public String sig {get; set;}
    public String plantel {get; set;}
    public List<String> programas {get; set;}
    public String totalPagar {get; set;}
    public List<FichaPago__c> fichas {get; set;}
    
    
    public BarCodeMovilCtrl(){
      
        String Ids = apexpages.currentpage().getparameters().get('ids');
       
        programas = new List<String>();
        
         //Obtener Fichas de la base de datos
        fichas = getFichasFromString(Ids);
        
        if(fichas.size()>0){
            
            //Asignar valores que no cambian en las fichas de pago
            hasta = refactorDate(fichas.get(0).Hasta__c);
            totalPagar = String.valueOf(fichas.get(0).TotaPagar__c);
            nota1 = fichas.get(0).Notas1__c;
            concept = fichas.get(0).Concepto__c;
    
            
            //Asignar plantel obtenido de la base de datos
            Plantel__c plantelObj= [SELECT Id,Name,Instituto__c  FROM Plantel__c WHERE Id=:fichas.get(0).Plantel__c];
            Instituto__c ns = [SELECT Id,Name FROM Instituto__c WHERE Id=:plantelObj.Instituto__c ];
           	System.debug(fichas.get(0));
            encabezado=GetResourceURL(fichas.get(0).Plantel__r.Instituto__r.Encabezado__c); 
            System.debug(encabezado);
            
            
            
            if(plantelObj.Name.length()>0){
                plantel=plantelObj.Name;
            }
          
            //Obtener los Programas Relacionados a la ficha y asginagnarlos a una lista de strings 
            List<Programa__c> programasR= getProgramasRelacionados(fichas.get(0).ProgramasRelacionados__c);
            for(Programa__c  prog:  programasR ){
                programas.add(prog.Name+'<br/>');
            }
        }
        
        
    }
    
	@future(callout=true)
	public static void sendMail(String ids){
       
       
        String url = 'https://sandbox-ieu.cs2.force.com/apex/BarCodeMovil?ids='+ids;
        PageReference pdf = new PageReference(url);
        System.debug(url);
     
        String userName = UserInfo.getUserName();
       	User activeUser = [Select Email From User where Username = : userName limit 1];
		String userEmail = activeUser.Email;
        
        List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
		Blob body;
		try {
			body = pdf.getContent();
		} catch (VisualforceException e) {
			body = Blob.valueOf('Some Text');
		}
		
        Messaging.EmailFileAttachment attach = new Messaging.EmailFileAttachment();
        attach.setContentType('application/pdf');
        attach.setFileName('Ficha de pago.pdf');
        
        attach.Body = body;
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setToAddresses(new String[] { userEmail });
        mail.setSubject('PDF Generation');
        mail.setHtmlBody('PFA');
        mail.setFileAttachments(new Messaging.EmailFileAttachment[] { attach });
        mails.add(mail);  
        if(!mails.isEmpty())
        {
            Messaging.SendEmail(mails);
        }
	}

    public static String encodeASCII(String cadena){
        return EncodingUtil.urlEncode(cadena, 'ASCII');
    }
    
  	/**
    * @author:      Gerardo Martínez
    * @date:        05/08/2016
    * @description: Reorganiza una fecha en el formato del cliente.  
    * @param:       Date
    * @return:      String
    */
 
    public static String refactorDate(Date dateToCast){
        String myDate = string.valueOfGmt(dateToCast);
        String[] myDateOnly = myDate.split(' ');
        String[] strDate = myDateOnly[0].split('-');
        Integer myIntMonth = integer.valueOf(strDate[1]);
        Integer myIntYear = integer.valueOf(strDate[0]);
        Integer myIntDate = integer.valueOf(strDate[2]);
        return  myIntDate +'-'+myIntMonth+'-'+myIntYear;
        
      
    }
    
  	/**
    * @author:      Gerardo Martínez
    * @date:        05/08/2016
    * @description: Regresa una lista de objetos FichaPago__c de un string de Ids, separados por un guion.  
    * @param:       String
    * @return:      List<FichaPago__c>
    */
    
    public static List<FichaPago__c> getFichasFromString(String Ids){
       List<FichaPago__c> results = new List<FichaPago__c>();
        if(Ids.length()>0 && !Ids.equals('')){
            
       		List<String> listOfIds = Ids.split('-');
     
            for(String s: listOfIds ){
                results.add([SELECT Id, Name, Notas1__c, Notas2__c, Hasta__c, Importe__c, Plantel__c, Plantel__r.Instituto__r.Encabezado__c,
                             Descuento__c, TotaPagar__c, ReferenciaOXXO__c, ReferenciaHSBC__c, Concepto__c, ProgramasRelacionados__c
                             FROM FichaPago__c WHERE Id=:s LIMIT 1]);
            }   
        }
        
        return results;
    }
    
    /**
    * @author:      Gerardo Martínez
    * @date:        05/08/2016
    * @description: Regresa una lista de objetos Programa__C de un string de Ids, separados por una coma.  
    * @param:       String
    * @return:      List<Programa__c>
    */
    
    public static List<Programa__c> getProgramasRelacionados(String Ids){
         List<Programa__c> results = new List<Programa__c>();
         if(Ids.length()>0 && !Ids.equals('') ){
            
       		List<String> listOfIds = Ids.split(',');
     
            for(String s: listOfIds ){
                results.add([SELECT Id, Name FROM Programa__c WHERE Id=:s LIMIT 1]);
            }   
        }
        return results;
    }
    
        /**
    * @author:      Gerardo Martínez
    * @date:        07/08/2016
    * @description: Regresa el url de un recurso estático.  
    * @param:       String
    * @return:      String
    */
    
    public static String GetResourceURL(String resourceName){

            // Fetching the resource
            List<StaticResource> resourceList= [SELECT Name, NamespacePrefix, SystemModStamp FROM StaticResource WHERE Name = :resourceName];

            // Checking if the result is returned or not
            if(resourceList.size() == 1){

               // Getting namespace
               String namespace = resourceList[0].NamespacePrefix;
               // Resource URL
               return '/resource/' + resourceList[0].SystemModStamp.getTime() + '/' + (namespace != null && namespace != '' ? namespace + '__' : '') + resourceName; 
            }
            else return '';
        }
    

}