src/objects/Descuento__c.object
<CustomObject>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Nivel</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Nivel</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Descuentos</relationshipLabel>
        <relationshipName>Descuentos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Periodo__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Periodo</label>
        <referenceTo>Periodo__c</referenceTo>
        <relationshipLabel>Descuentos</relationshipLabel>
        <relationshipName>Descuentos</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Descuento</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Descuentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FichaPago__c.object
<CustomObject>
    <fields>
        <fullName>Descuento__c</fullName>
        <label>Descuento</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Hasta__c</fullName>
        <label>Hasta el</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Importe__c</fullName>
        <label>Importe</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Nivel</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Nivel</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Fichas de pago</relationshipLabel>
        <relationshipName>Fichas_de_pago</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Periodo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Periodo</label>
        <referenceTo>Periodo__c</referenceTo>
        <relationshipLabel>Fichas de pago</relationshipLabel>
        <relationshipName>Fichas_de_pago</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Fichas de pago</relationshipLabel>
        <relationshipName>Fichas_de_pago</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProgramasRelacionados__c</fullName>
        <label>Programas Relacionados</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TipoFicha__c</fullName>
        <label>Tipo de ficha</label>
        <picklist>
            <picklistValues>
                <fullName>Nivel Doctorado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nivel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Promoción Cero</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ficha Especial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ficha Móvil</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TotaPagar__c</fullName>
        <label>Total a pagar</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Ficha de pago</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fichas de pago</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>FichaPago__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Ficha de Pago</description>
        <label>Con ficha pago</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Nivel</description>
        <label>Nivel</label>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Candidatos (Nivel)</relationshipLabel>
        <relationshipName>Nivel</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OfertaEducativa__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Búsqueda de Oferta Educativa para el Canidato</description>
        <label>Oferta educativa</label>
        <referenceTo>OfertaEducativa__c</referenceTo>
        <relationshipLabel>Candidatos</relationshipLabel>
        <relationshipName>Candidatos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Periodo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Periodo</description>
        <label>Periodo</label>
        <referenceTo>Periodo__c</referenceTo>
        <relationshipLabel>Periodo</relationshipLabel>
        <relationshipName>Periodo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Plantel</description>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Candidatos</relationshipLabel>
        <relationshipName>Plantel</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Programa__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Programa</description>
        <label>Programa</label>
        <referenceTo>Programa__c</referenceTo>
        <relationshipLabel>Candidatos</relationshipLabel>
        <relationshipName>Programa</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/OfertaEducativa__c.object
<CustomObject>
    <fields>
        <fullName>Descuento__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Descuento</label>
        <referenceTo>Descuento__c</referenceTo>
        <relationshipLabel>Ofertas Educativas</relationshipLabel>
        <relationshipName>Ofertas_Educativas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Nivel</inlineHelpText>
        <label>Nivel</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Nivel</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Ofertas Educativas (Nivel)</relationshipLabel>
        <relationshipName>Ofertas_Educativas1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Periodo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Periodo</label>
        <referenceTo>Periodo__c</referenceTo>
        <relationshipLabel>Ofertas Educativas</relationshipLabel>
        <relationshipName>Ofertas_Educativas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Plantel</inlineHelpText>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Ofertas Educativas</relationshipLabel>
        <relationshipName>Ofertas_Educativas</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Programa__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Programa</inlineHelpText>
        <label>Programa</label>
        <referenceTo>Programa__c</referenceTo>
        <relationshipLabel>Ofertas Educativas</relationshipLabel>
        <relationshipName>Ofertas_Educativas</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Oferta Educativa</label>
    <nameField>
        <displayFormat>OE-{0000000}</displayFormat>
        <label>Oferta Educativa</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ofertas Educativas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Periodo__c.object
<CustomObject>
    <label>Periodo</label>
    <nameField>
        <label>Periodo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Periodos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Plantel__c.object
<CustomObject>
    <label>Plantel</label>
    <nameField>
        <label>Plantel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planteles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Programa__c.object
<CustomObject>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Nivel</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Nivel</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Programas</relationshipLabel>
        <relationshipName>Programas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Programas</relationshipLabel>
        <relationshipName>Programas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Programa</label>
    <nameField>
        <label>Programa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FichaPagoMovilCtrl.cls
public with sharing class FichaPagoMovilCtrl {
	public FichaPago__c ficha {get; set;}
    Public RecordType rt;
    public String numeroFichas {get; set;}
    public Boolean consulto {get; set;}
    public Boolean todosProgramas {get; set;}
    public List<OfertaEducativa__c> listPrograma {get; set;}
    Public List<WrapperPrograma> listPrograms {get; set;}    
    public List<String> listSelecteds {get; set;}
    public FichaPagoMovilCtrl(){
        ficha = new FichaPago__c();
        consulto = false;
        rt = [SELECT Id,Name FROM RecordType WHERE SobjectType='FichaPago__c' AND Name='Ficha Móvil'];
    }
    
    public PageReference getPrograms(){
        listPrograms = new List<WrapperPrograma>();
        String criteria = 'Nivel__c = \''+ficha.Nivel__c+'\'';
         System.debug('criteria1--> '+ criteria);
        if(ficha.Periodo__c != null){
            criteria += ' AND Periodo__c = \''+ ficha.Periodo__c+'\'';
        }
        if(ficha.Plantel__c != null){
            criteria += ' AND Plantel__c = \''+ ficha.Plantel__c +'\'';
        }
        
        String query = 'SELECT Id, Name, Programa__c, Programa__r.Name FROM OfertaEducativa__c WHERE ' + criteria;
        listPrograma = (List<OfertaEducativa__c>) Database.query(query);
        for(OfertaEducativa__c offer: listPrograma){
            WrapperPrograma data = new WrapperPrograma();
            data.name = offer.Programa__r.Name;
            data.IdPrograma = offer.Programa__c;
            listPrograms.add(data);
        }
        if(!listPrograms.isEmpty()){
        	consulto = true;
            return null;
        }else{
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, 'No existen programas para los filtros seleccionados'));
            return null;
        }
    }
    
    public PageReference saveToken(){
        
        ficha.TotaPagar__c = ficha.Importe__c - (ficha.Importe__c * (ficha.Descuento__c / 100));
        ficha.TipoFicha__c = 'Ficha Móvil';
        ficha.RecordTypeId = rt.Id;
        List<FichaPago__c> fichasInsert = new List<FichaPago__c>();
        String selectedPrograms = '';
        if(todosProgramas){
            for(WrapperPrograma wpPrograma: listPrograms){
                selectedPrograms += wpPrograma.IdPrograma + ',';
            }
        }else{
            for(WrapperPrograma wpPrograma: listPrograms){
                If(wpPrograma.active == true){
                    selectedPrograms += wpPrograma.IdPrograma + ',';
                }
            }
        }
        
        ficha.ProgramasRelacionados__c = selectedPrograms.removeEnd(',');
        String fichasId = '';
        if(selectedPrograms != ''){
            for(Integer i = 0; i< Integer.valueOf(numeroFichas); i++){
                FichaPago__c newFicha= new FichaPago__c();
                newFicha.Descuento__c = ficha.Descuento__c;
                newFicha.Importe__c = ficha.Importe__c;
                newFicha.Hasta__c = ficha.Hasta__c;
                newFicha.Periodo__c = ficha.Periodo__c;
                newFicha.RecordTypeId = ficha.RecordTypeId;
                newFicha.TipoFicha__c = ficha.TipoFicha__c;
                newFicha.ProgramasRelacionados__c = ficha.ProgramasRelacionados__c;
                newFicha.Plantel__c = ficha.Plantel__c;
                newFicha.Nivel__c = ficha.Nivel__c;
                newFicha.TotaPagar__c = ficha.TotaPagar__c;
                fichasInsert.add(newFicha);            
            }
            upsert fichasInsert;
            for(FichaPago__c fichaValue :fichasInsert){
                fichasId= fichasId+fichaValue.Id + '-';
            }
            fichasId.removeEnd('-');
            BarCodeMovilCtrl.sendMail(fichasId);
            PageReference toTokens = new PageReference('/apex/FichaPagoPendiente');
            toTokens.setRedirect(true);
            return toTokens;
        }else{
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, 'No se ha seleccionado ningun programa para la ficha'));
            return null;
        }
    }
    
    public PageReference exit(){
        PageReference toTokens = new PageReference('/apex/FichaPagoPendiente');
        toTokens.setRedirect(true);
        return toTokens;
    }
    
    Public class WrapperPrograma{
       
        Public String name {get; set;}
        Public Boolean active {get; set;}
        Public Id idPrograma {get; set;}
        public WrapperPrograma(){
            active = false;
        }
    }
}