src/objects/FichaPago__c.object
<CustomObject>
    <fields>
        <fullName>FolioLead__c</fullName>
        <label>Folio de lead / oportunidad</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hasta__c</fullName>
        <label>Hasta el</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Nivel</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Nivel</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Fichas de pago</relationshipLabel>
        <relationshipName>Fichas_de_pago</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Periodo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Periodo</label>
        <referenceTo>Periodo__c</referenceTo>
        <relationshipLabel>Fichas de pago</relationshipLabel>
        <relationshipName>Fichas_de_pago</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Fichas de pago</relationshipLabel>
        <relationshipName>Fichas_de_pago</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProgramasRelacionados__c</fullName>
        <label>Programas Relacionados</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TotaPagar__c</fullName>
        <label>Total a pagar</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Ficha de pago</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fichas de pago</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Negocio__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuraciones  globales</description>
    <fields>
        <fullName>Folio__c</fullName>
        <description>Número de folio consecutivo para candidatos y prospéctos</description>
        <inlineHelpText>Número de folio consecutivo para candidatos y prospéctos</inlineHelpText>
        <label>Folio</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Negocio</label>
</CustomObject>

src/objects/OfertaEducativa__c.object
<CustomObject>
    <fields>
        <fullName>Conceptos__c</fullName>
        <description>Muestra todos los conceptos de pago capturados en el objeto Pagos oferta</description>
        <label>Conceptos</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Modalidad__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Modalidad</inlineHelpText>
        <label>Modalidad</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Modalidad</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Ofertas Educativas</relationshipLabel>
        <relationshipName>Ofertas_Educativas</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Nivel</inlineHelpText>
        <label>Nivel</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Nivel</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Ofertas Educativas (Nivel)</relationshipLabel>
        <relationshipName>Ofertas_Educativas1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Periodo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Periodo</label>
        <referenceTo>Periodo__c</referenceTo>
        <relationshipLabel>Ofertas Educativas</relationshipLabel>
        <relationshipName>Ofertas_Educativas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Plantel</inlineHelpText>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Ofertas Educativas</relationshipLabel>
        <relationshipName>Ofertas_Educativas</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Programa__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Programa</inlineHelpText>
        <label>Programa</label>
        <referenceTo>Programa__c</referenceTo>
        <relationshipLabel>Ofertas Educativas</relationshipLabel>
        <relationshipName>Ofertas_Educativas</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Oferta Educativa</label>
    <nameField>
        <displayFormat>OE-{0000000}</displayFormat>
        <label>Oferta Educativa</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ofertas Educativas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Periodo__c.object
<CustomObject>
    <label>Periodo</label>
    <nameField>
        <label>Periodo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Periodos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Plantel__c.object
<CustomObject>
    <fields>
        <fullName>Abreviatura__c</fullName>
        <label>Abreviatura</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Plantel</label>
    <nameField>
        <label>Plantel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planteles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Programa__c.object
<CustomObject>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Nivel</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Nivel</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Programas</relationshipLabel>
        <relationshipName>Programas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Programas</relationshipLabel>
        <relationshipName>Programas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Programa</label>
    <nameField>
        <label>Programa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Ubicacion__c.object
<CustomObject>
    <description>Listado que contiene: País, estados y municipios</description>
    <fields>
        <fullName>Abreviatura__c</fullName>
        <description>Aplica para estado</description>
        <externalId>true</externalId>
        <label>Abreviatura</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IdEstadoPais__c</fullName>
        <description>Aplica para municipio y estado</description>
        <label>Id Estado/País</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Ubicación</label>
    <nameField>
        <label>Nombre de Ubicación</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ubicaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UtilsOfertaTest.cls
@isTest
public class UtilsOfertaTest {
    @IsTest   public static void getModalidades(){
        List<SelectOption> options = new List<SelectOption>();
        options=UtilsOferta.getModalidades();
    }
    @IsTest   public static void getPlanteles(){
        List<SelectOption> planteles = new List<SelectOption>();
        OfertaEducativa__c obj = new OfertaEducativa__c(Conceptos__c   =  'Nuevo',
                                                        Modalidad__c ='a03R00000059FVrIAM',
                                                        Nivel__c='a03R00000059FVDIA2',
                                                        Programa__c='a04R0000003k4QqIAI',
                                                        Plantel__c='a02R000000NukmYIAR');
        insert obj;
        planteles=UtilsOferta.getPlanteles(obj.Modalidad__c);
    }
    @IsTest   public static void getNiveles(){
        List<SelectOption> niveles = new List<SelectOption>();
        OfertaEducativa__c obj = new OfertaEducativa__c(Conceptos__c   =  'Nuevo',
                                                        Modalidad__c ='a03R00000059FVrIAM',
                                                        Nivel__c='a03R00000059FVDIA2',
                                                        Programa__c='a04R0000003k4QqIAI',
                                                        Plantel__c='a02R000000NukmYIAR');
        insert obj;
        niveles=UtilsOferta.getNiveles(obj.Plantel__c, obj.Modalidad__c);
    }
    @IsTest   public static void getProgramas(){
        List<SelectOption> programas = new List<SelectOption>();
        OfertaEducativa__c obj = new OfertaEducativa__c(Conceptos__c   =  'Nuevo',
                                                        Modalidad__c ='a03R00000059FVrIAM',
                                                        Nivel__c='a03R00000059FVDIA2',
                                                        Programa__c='a04R0000003k4QqIAI',
                                                        Plantel__c='a02R000000NukmYIAR');
        insert obj;
        programas=UtilsOferta.getProgramas(obj.Plantel__c, obj.Modalidad__c,obj.Nivel__c);
    }
    @IsTest   public static void getProgramasMoviles(){
        List<SelectOption> programas = new List<SelectOption>();
        Negocio__c configuracionNegocio = Negocio__c.getOrgDefaults();
        Integer nextFolio = configuracionNegocio.Folio__c != null ? Integer.valueOf(configuracionNegocio.Folio__c) : 0;
        
        FichaPago__c obj = new FichaPago__c(FolioLead__c= nextFolio, TotaPagar__c =333
                                            ,Hasta__c = Date.today()
                                            ,ProgramasRelacionados__c= 'a04R0000003k4RBIAY,a04R0000003k4RSIAY,a04R0000003k4TrIAI' );
        insert obj;
        programas=UtilsOferta.getProgramasMoviles(obj.Id);
    }
    @IsTest   public static void getModalidadesMoviles(){
        List<OfertaEducativa__c> periodos = new List<OfertaEducativa__c>();
        OfertaEducativa__c obj = new OfertaEducativa__c(Conceptos__c   =  'Nuevo',
                                                        Modalidad__c ='a03R00000059FVrIAM',
                                                        Nivel__c='a03R00000059FVDIA2',
                                                        Programa__c='a04R0000003k4QqIAI',
                                                        Plantel__c='a02R000000NukmYIAR');
        insert obj;
        periodos=UtilsOferta.getModalidadesMoviles(obj.Plantel__c,obj.Periodo__c, obj.Nivel__c, obj.Programa__c);
    }
    @IsTest   public static void getPeriodo(){
        List<SelectOption> periodos = new List<SelectOption>();
        OfertaEducativa__c obj = new OfertaEducativa__c(Conceptos__c   =  'Nuevo',
                                                        Modalidad__c ='a03R00000059FVrIAM',
                                                        Nivel__c='a03R00000059FVDIA2',
                                                        Programa__c='a04R0000003k4QqIAI',
                                                        Plantel__c='a02R000000NukmYIAR');
        insert obj;
        periodos=UtilsOferta.getPeriodo(obj.Plantel__c,obj.Modalidad__c,  obj.Nivel__c, obj.Programa__c);
    }
    @IsTest   public static void getPeriodos(){
        List<OfertaEducativa__c> periodos = new List<OfertaEducativa__c>();
        OfertaEducativa__c obj = new OfertaEducativa__c(Conceptos__c   =  'Nuevo',
                                                        Modalidad__c ='a03R00000059FVrIAM',
                                                        Nivel__c='a03R00000059FVDIA2',
                                                        Programa__c='a04R0000003k4QqIAI',
                                                        Plantel__c='a02R000000NukmYIAR');
        insert obj;
        periodos=UtilsOferta.getPeriodos(obj.Plantel__c,obj.Modalidad__c,  obj.Nivel__c, obj.Programa__c);
    }
    @IsTest   public static void getPaises(){
        List<Ubicacion__c> options = new List<Ubicacion__c>();
        options=UtilsOferta.getPaises();
    }
    @IsTest   public static void getEstados(){
        Ubicacion__c obj = new Ubicacion__c(Abreviatura__c ='Nuevo');
        insert obj;
        List<Ubicacion__c> options = new List<Ubicacion__c>();
        options=UtilsOferta.getEstados(obj.IdEstadoPais__c);
    }
    @IsTest   public static void getMunicipios(){
        
        Ubicacion__c obj = new Ubicacion__c(Abreviatura__c ='Nuevo',
                                            IdEstadoPais__c ='7');
        insert obj;
        List<SelectOption> options = new List<SelectOption>();
        options=UtilsOferta.getMunicipios(obj.IdEstadoPais__c);
    }
}