src/objects/FichaPago__c.object
<CustomObject>
    <fields>
        <fullName>Notas2__c</fullName>
        <formula>&quot;Si se requiere factura, favor de solicitar el mismo día de pago.&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Notas 2</label>
        <type>Text</type>
    </fields>
    <label>Ficha de pago</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fichas de pago</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GenerarPDFComprobanteCtrl.cls
public with sharing class GenerarPDFComprobanteCtrl { 
    Public FichaPago__c idToken {get; set;} 
    FichaPago__c  ord;  
        
    public GenerarPDFComprobanteCtrl( ){
        
    } 
    @future(callout=true)
    public static void sendMailComprobante(String folio, String concepto,String mail, String autorizacion, String cantidad, String id){ 
        //System.debug('ENTRA A SENDMAILCOMPROBANTE');
        FichaPago__c  ord; 
        DateTime hoy = datetime.now();
        
        String fecha= string.valueOf(hoy.format('dd/MM/yyyy HH:mm:ss') ); 
        ord = new  FichaPago__c();  
        ord = [SELECT  Notas2__c FROM FichaPago__c  WHERE Id = :id limit 1]; 
        String nota2=ord.Notas2__c; 
        if(folio!=''|| concepto!=''|| autorizacion !=''|| cantidad !='' ){  
            ComprobanteLeadCtrl.sendMailComprobante(folio, concepto,mail, autorizacion, cantidad ,fecha, nota2   );
        } else{
            
        }
        
        
    }
}