src/objects/Grupo__c.object
<CustomObject>
    <fields>
        <fullName>Activo__c</fullName>
        <label>Activo</label>
        <picklist>
            <picklistValues>
                <fullName>Activo</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactivo</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <formula>OfertaEducativa__r.Nivel__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Nivel</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OfertaEducativa__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Oferta educativa</label>
        <referenceTo>OfertaEducativa__c</referenceTo>
        <relationshipLabel>Grupos</relationshipLabel>
        <relationshipName>Grupos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Periodo__c</fullName>
        <formula>OfertaEducativa__r.Periodo__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Periodo</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <formula>OfertaEducativa__r.Plantel__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Plantel</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Programa__c</fullName>
        <formula>OfertaEducativa__r.Programa__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Programa</label>
        <type>Text</type>
    </fields>
    <label>Grupo</label>
    <nameField>
        <label>Clave</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>ModalidadEjecutiva__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Modalidad Ejecutiva</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ModalidadOnline__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Modalidad Online</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ModalidadPresencial__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Modalidad Presencial</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Modalidad__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Modalidad</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Modalidad</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Candidatos (Modalidad)</relationshipLabel>
        <relationshipName>Candidatos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Nivel</description>
        <label>Nivel</label>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Candidatos (Nivel)</relationshipLabel>
        <relationshipName>Nivel</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OfertaEducativa__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Búsqueda de Oferta Educativa para el Canidato</description>
        <label>Oferta educativa</label>
        <referenceTo>OfertaEducativa__c</referenceTo>
        <relationshipLabel>Candidatos</relationshipLabel>
        <relationshipName>Candidatos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Periodo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Periodo</description>
        <label>Periodo</label>
        <referenceTo>Periodo__c</referenceTo>
        <relationshipLabel>Periodo</relationshipLabel>
        <relationshipName>Periodo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Plantel</description>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Candidatos</relationshipLabel>
        <relationshipName>Plantel</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Programa__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Programa</description>
        <label>Programa</label>
        <referenceTo>Programa__c</referenceTo>
        <relationshipLabel>Candidatos</relationshipLabel>
        <relationshipName>Programa</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Materia__c.object
<CustomObject>
    <fields>
        <fullName>Modalidad__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Modalidad</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Modalidad</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Materias (Modalidad)</relationshipLabel>
        <relationshipName>Modalidad</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Nivel</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Nivel</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Materias</relationshipLabel>
        <relationshipName>Materias</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Materias</relationshipLabel>
        <relationshipName>Materias</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Programa__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Programa</label>
        <referenceTo>Programa__c</referenceTo>
        <relationshipLabel>Materias</relationshipLabel>
        <relationshipName>Materias</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Materia</label>
    <nameField>
        <label>Materia</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Negocio__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuraciones  globales</description>
    <fields>
        <fullName>ModalidadOnline__c</fullName>
        <description>Id del catálogo correspondiente a la modalidad online</description>
        <inlineHelpText>Id del catálogo correspondiente a la modalidad online</inlineHelpText>
        <label>Modalidad Online</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Negocio</label>
</CustomObject>

src/objects/OfertaEducativa__c.object
<CustomObject>
    <fields>
        <fullName>Modalidad__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Modalidad</inlineHelpText>
        <label>Modalidad</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Modalidad</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Ofertas Educativas</relationshipLabel>
        <relationshipName>Ofertas_Educativas</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Nivel</inlineHelpText>
        <label>Nivel</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Nivel</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Ofertas Educativas (Nivel)</relationshipLabel>
        <relationshipName>Ofertas_Educativas1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Periodo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Periodo</label>
        <referenceTo>Periodo__c</referenceTo>
        <relationshipLabel>Ofertas Educativas</relationshipLabel>
        <relationshipName>Ofertas_Educativas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Plantel</inlineHelpText>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Ofertas Educativas</relationshipLabel>
        <relationshipName>Ofertas_Educativas</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Programa__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Programa</inlineHelpText>
        <label>Programa</label>
        <referenceTo>Programa__c</referenceTo>
        <relationshipLabel>Ofertas Educativas</relationshipLabel>
        <relationshipName>Ofertas_Educativas</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Oferta Educativa</label>
    <nameField>
        <displayFormat>OE-{0000000}</displayFormat>
        <label>Oferta Educativa</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ofertas Educativas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Periodo__c.object
<CustomObject>
    <fields>
        <fullName>ActivoEjecutiva__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activo ejecutiva</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ActivoOnline__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activo online</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ActivoPresencial__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activo presencial</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Activo__c</fullName>
        <label>Estatus</label>
        <picklist>
            <picklistValues>
                <fullName>Activo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactivo</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Periodo</label>
    <nameField>
        <label>Periodo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Periodos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Programa__c.object
<CustomObject>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Nivel</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Nivel</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Programas</relationshipLabel>
        <relationshipName>Programas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Programas</relationshipLabel>
        <relationshipName>Programas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Programa</label>
    <nameField>
        <label>Programa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OFE_OfertaAcademicaMotor.cls
public with sharing class OFE_OfertaAcademicaMotor {
	public Periodo__c period {get;set;}
    public OFE_OfertaAcademicaMotor(){
    
    }
    
    /**
    * @author:      Rogelio Jiménez
    * @date:        16/05/2016
    * @description: 
    * @param:       Lead
    * @return:      OfertaEducativa__c
    */
    
     public map<lead,OfertaEducativa__c> obtainAcademicOffer(list<lead> leads){
    	OfertaEducativa__c academicOffert = new OfertaEducativa__c();
    	map<lead,OfertaEducativa__c> mapLeadOferta = new map<lead,OfertaEducativa__c>();
    	String modalidad = '';
    /*	modalidad = lead.ModalidadPresencial__c ? modalidad + ' OR ActivoPresencial__c = true ': '';
    	modalidad = lead.ModalidadOnline__c ? modalidad + ' OR ActivoOnline__c = true ': modalidad + '';
    	modalidad = lead.ModalidadEjecutiva__c ? modalidad + ' OR ActivoEjecutiva__c = true ': modalidad + '';*/
    	
    	modalidad = ' AND (ActivoPresencial__c = true  OR ActivoOnline__c = true OR ActivoEjecutiva__c = true)';
        
    	String query = 'SELECT Id,Name,ActivoPresencial__c,ActivoOnline__c,ActivoEjecutiva__c FROM Periodo__c WHERE Activo__c = \'Activo\' ' + modalidad;
        //System.debug('obtainAcademicOffer: ' + query);
        List<Periodo__c> listPeriod= (List<Periodo__c>) Database.query(query);
        //period = listPeriod[0];
        
        for(Periodo__c period:listPeriod ){
        	for(Lead lead:leads){
        		academicOffert = getAccademicOferByPeriodo(period,lead);
                if(academicOffert != null){
	        		mapLeadOferta.put(lead,academicOffert);
                }
        	}
        	
        }
        return mapLeadOferta;
    }
    
    public OfertaEducativa__c obtainAcademicOffer(Lead lead){
        System.debug(lead);
    	OfertaEducativa__c academicOffert = new OfertaEducativa__c();
    	String modalidad = '';
    	modalidad = lead.ModalidadPresencial__c ? modalidad + ' AND ActivoPresencial__c = true ': '';
    	modalidad = lead.ModalidadOnline__c ? modalidad + ' AND ActivoOnline__c = true ': modalidad + '';
    	modalidad = lead.ModalidadEjecutiva__c ? modalidad + ' AND ActivoEjecutiva__c = true ': modalidad + '';
        
    	String query = 'SELECT Id,Name,ActivoPresencial__c,ActivoOnline__c,ActivoEjecutiva__c FROM Periodo__c WHERE Activo__c = \'Activo\' ' + modalidad;
        //System.debug('obtainAcademicOffer: ' + query);
        List<Periodo__c> listPeriod= (List<Periodo__c>) Database.query(query);
        //period = listPeriod[0];
        
        for(Periodo__c period:listPeriod ){
        	academicOffert = getAccademicOferByPeriodo(period,lead);
        	if(academicOffert != null){
        		 return academicOffert;
        	}
        }
        //System.debug(academicOffert);
        return academicOffert;
    }
    
     /**
    * @author:      Rogelio Jiménez
    * @date:        16/05/2016
    * @description: 
    * @param:       
    * @return:     OfertaEducativa__c
    */
     public static OfertaEducativa__c getAccademicOferByPeriodo(Periodo__c period,Lead lead){
     	OfertaEducativa__c accademicOffer = null;
         System.debug('Periodo: ' + period);
         System.debug('lead: '+ lead);
     	list<OfertaEducativa__c> oferts = new list<OfertaEducativa__c>();
     	if(period!= null && lead != null){
     		System.debug('getAccademicOferByPeriodo: ' + period +',' + lead.Modalidad__c +','+ lead.Plantel__c +',' +  lead.Nivel__c + ',' +  lead.Programa__c);
     		if((lead.ModalidadPresencial__c &&  period.ActivoPresencial__c) || 
     				(lead.ModalidadOnline__c &&  period.ActivoOnline__c) || (lead.ModalidadEjecutiva__c &&  period.ActivoEjecutiva__c)){
     					try{
				     	 		oferts = [SELECT id,Name,Periodo__c,Modalidad__c,Plantel__c,Nivel__c,Programa__c
				     	 												FROM OfertaEducativa__c WHERE Periodo__c =: period.Id 
				     	 												AND Modalidad__c =: lead.Modalidad__c AND Plantel__c =: lead.Plantel__c
				     	 												AND Nivel__c =: lead.Nivel__c AND Programa__c =: lead.Programa__c AND Estatus__c =: 'Activo'
				     	 												];
				     	}catch(Exception e){
				     		System.debug('No hay oferta académica que asignar: ' + e.getMessage());
				     	}
     		
     		}
     		
     	
     	//Devolver la que tiene prioridad online. Pendiente RJP
 	 	if(oferts.size() > 0)
 	 		accademicOffer = oferts[0];
     	}
     	System.debug('oferta: ' + accademicOffer);
     	return accademicOffer;
     }
     
     /**
    * @author:      Rogelio Jiménez
    * @date:        16/05/2016
    * @description: 
    * @param:       
    * @return:     OfertaEducativa__c
    */
     public  Grupo__c getGroupByAcademicOffer(OfertaEducativa__c academicOffer){
     	Grupo__c groupAssigned = new Grupo__c() ;
     	list<Grupo__c> groupsAssigned = new list<Grupo__c>();
     	if(academicOffer != null){
     			groupsAssigned = [SELECT id,Name,Grupo__c,OfertaEducativa__c,OfertaEducativa__r.Modalidad__c,OfertaEducativa__r.Modalidad__r.Name,Cupo__c,ProspectosAsignados__c 
     							FROM Grupo__c 
     							WHERE  OfertaEducativa__c =: academicOffer.Id];            	
         	System.debug('size groupasi '+groupsAssigned.size() );
            if(groupsAssigned.size() >= 1){
                        Integer maximoInscribir = 0;
                        Integer prospectosAsignados = 0;
         			    for(Grupo__c grupo:groupsAssigned){
                            if (grupo.OfertaEducativa__r.Modalidad__r.Name == 'Presencial' || grupo.OfertaEducativa__r.Modalidad__r.Name == 'Ejecutiva' ){
                                    maximoInscribir = Integer.valueOf(grupo.Cupo__c) *  Integer.valueOf(Negocio__c.getOrgDefaults().MaximoGrupo__c);
                                    prospectosAsignados = grupo.ProspectosAsignados__c != null ? prospectosAsignados: 0;
                                    if(prospectosAsignados <= maximoInscribir){
                                        groupAssigned = grupo;
                                        break;
                                    }
                            }else{
                                System.debug('grupo.Cupo__c--> '+grupo.Cupo__c);
                                System.debug('Negocio__c.getOrgDefaults().MaximoGrupoOnline__c--> '+Negocio__c.getOrgDefaults().MaximoGrupoOnline__c);
                                
                                 maximoInscribir = Integer.valueOf(grupo.Cupo__c) * Integer.valueOf(Negocio__c.getOrgDefaults().MaximoGrupoOnline__c);
                                  prospectosAsignados = grupo.ProspectosAsignados__c != null ? prospectosAsignados: 0;
                                 if(prospectosAsignados <= maximoInscribir){
                                        groupAssigned = grupo;
                                        break;
                                 }
                            }
                        }
         		}else if (groupsAssigned.size() == 1){
                    groupAssigned = groupsAssigned.get(0);
                    if(groupAssigned.ProspectosAsignados__c == null){
                        groupAssigned.ProspectosAsignados__c = 1;
                    }else{
                        groupAssigned.ProspectosAsignados__c = groupAssigned.ProspectosAsignados__c + 1;
                    }
                }
     	}
     	return groupAssigned;
     }
     
}