src/objects/Grupo__c.object
<CustomObject>
    <fields>
        <fullName>Estatus__c</fullName>
        <label>Estatus</label>
        <picklist>
            <picklistValues>
                <fullName>Planeado</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Autorizado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rechazado</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Grupo__c</fullName>
        <label>Grupo</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Grupo</label>
    <nameField>
        <label>Clave</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Grupo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grupo</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Grupo__c.OfertaEducativa__c</field>
                <operation>equals</operation>
                <valueField>$Source.OfertaEducativa__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Grupo__c</referenceTo>
        <relationshipLabel>Oportunidades</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pago__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Realización del pago</description>
        <label>Pago</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ProcessBuilderLeadConvert.cls
public class ProcessBuilderLeadConvert {
	@InvocableMethod
    public static void leadConvert(List<Id> leadId){
        for(Id lead: leadId){
            ProcessBuilderLeadConvert.convertLead(lead);
        }
    }
    
    @future(callout=true)
    public static void convertLead(Id leadId){
        Database.LeadConvert lc = new Database.LeadConvert();
        lc.setLeadId(leadId);
        
        LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
        lc.setConvertedStatus(convertStatus.MasterLabel);
        
        Database.LeadConvertResult lcr = Database.convertLead(lc);
        Id oppId = lcr.getOpportunityId();
        
        Opportunity opp = [SELECT id, Grupo__r.Estatus__c  FROM Opportunity WHERE Id =: oppId];
        if(opp.Grupo__r.Estatus__c  == 'Autorizado'){
            opp.StageName = 'Ganada';
        }else{
            opp.StageName = 'Inscrito';
        }
        opp.Pago__c = true;
        update opp;
    }
}