src/objects/Grupo__c.object
<CustomObject>
    <fields>
        <fullName>AutorizaGrupo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Autorización de grupo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Estatus__c</fullName>
        <label>Estatus</label>
        <picklist>
            <picklistValues>
                <fullName>Planeado</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Autorizado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rechazado</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Grupo__c</fullName>
        <label>Grupo</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Grupo</label>
    <nameField>
        <label>Clave</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Grupo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grupo</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Grupo__c.OfertaEducativa__c</field>
                <operation>equals</operation>
                <valueField>$Source.OfertaEducativa__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Grupo__c</referenceTo>
        <relationshipLabel>Oportunidades</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ProcessBuilderMethods.cls
public class ProcessBuilderMethods {
	@InvocableMethod
    public static void changeStateOpportunity(List<Id> oppId){
        Opportunity opp = [SELECT id, Grupo__r.Estatus__c, Grupo__r.AutorizaGrupo__c FROM Opportunity WHERE Id =: oppId[0]];
        if(opp.Grupo__r.Estatus__c == 'Autorizado'){
            opp.StageName = 'Ganada';
        }else{
            opp.StageName = 'Inscrito';
        }
        update opp;
    }
}