src/objects/Grupo__c.object
<CustomObject>
    <fields>
        <fullName>Activo__c</fullName>
        <label>Activo</label>
        <picklist>
            <picklistValues>
                <fullName>Activo</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactivo</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Consecutivo__c</fullName>
        <label>Consecutivo</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Estatus__c</fullName>
        <label>Estatus</label>
        <picklist>
            <picklistValues>
                <fullName>Planeado</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Autorizado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rechazado</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Grupo__c</fullName>
        <label>Grupo</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <formula>OfertaEducativa__r.Nivel__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Nivel</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nomenclatura__c</fullName>
        <label>Nomenclatura</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OfertaEducativa__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Oferta educativa</label>
        <referenceTo>OfertaEducativa__c</referenceTo>
        <relationshipLabel>Grupos</relationshipLabel>
        <relationshipName>Grupos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <formula>OfertaEducativa__r.Plantel__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Plantel</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Programa__c</fullName>
        <formula>OfertaEducativa__r.Programa__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Programa</label>
        <type>Text</type>
    </fields>
    <label>Grupo</label>
    <nameField>
        <label>Clave</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OfertaEducativa__c.object
<CustomObject>
    <fields>
        <fullName>Estatus__c</fullName>
        <label>Estatus</label>
        <picklist>
            <picklistValues>
                <fullName>Activo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactivo</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Grupo__c</fullName>
        <label>Grupo</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Nivel</inlineHelpText>
        <label>Nivel</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Nivel</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Ofertas Educativas (Nivel)</relationshipLabel>
        <relationshipName>Ofertas_Educativas1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Plantel</inlineHelpText>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Ofertas Educativas</relationshipLabel>
        <relationshipName>Ofertas_Educativas</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Programa__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Programa</inlineHelpText>
        <label>Programa</label>
        <referenceTo>Programa__c</referenceTo>
        <relationshipLabel>Ofertas Educativas</relationshipLabel>
        <relationshipName>Ofertas_Educativas</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RvoeVigente__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>RVOE vigente asociado al programa al momento de configurar la oferta educativa</description>
        <label>RVOE Vigente</label>
        <referenceTo>RVOE__c</referenceTo>
        <relationshipLabel>Ofertas Educativas</relationshipLabel>
        <relationshipName>Ofertas_Educativas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Oferta Educativa</label>
    <nameField>
        <displayFormat>OE-{0000000}</displayFormat>
        <label>Oferta Educativa</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ofertas Educativas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Grupo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grupo</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Grupo__c.OfertaEducativa__c</field>
                <operation>equals</operation>
                <valueField>$Source.OfertaEducativa__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Grupo__c</referenceTo>
        <relationshipLabel>Oportunidades</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Nivel</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Nivel</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Oportunidades (Nivel)</relationshipLabel>
        <relationshipName>Oportunidades1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OfertaEducativa__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Oferta Educativa</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>OfertaEducativa__c.Periodo__c</field>
                <operation>equals</operation>
                <valueField>$Source.Periodo__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>OfertaEducativa__c</referenceTo>
        <relationshipLabel>Oportunidades</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Oportunidades</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Programa__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programa</label>
        <referenceTo>Programa__c</referenceTo>
        <relationshipLabel>Oportunidades</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Plantel__c.object
<CustomObject>
    <label>Plantel</label>
    <nameField>
        <label>Plantel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planteles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Programa__c.object
<CustomObject>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Nivel</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Nivel</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Programas</relationshipLabel>
        <relationshipName>Programas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Programas</relationshipLabel>
        <relationshipName>Programas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Programa</label>
    <nameField>
        <label>Programa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RVOE__c.object
<CustomObject>
    <fields>
        <fullName>Activo__c</fullName>
        <label>Activo</label>
        <picklist>
            <picklistValues>
                <fullName>Activo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactivo</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Nivel</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo__c.TipoCatalogo__c</field>
                <operation>equals</operation>
                <value>Nivel</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>RVOES</relationshipLabel>
        <relationshipName>RVOES</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <label>Consecutivo de RVOE</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>RVOES</relationshipLabel>
        <relationshipName>RVOES</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Programa__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Programa al que se asocia</description>
        <label>Programa</label>
        <referenceTo>Programa__c</referenceTo>
        <relationshipLabel>RVOES</relationshipLabel>
        <relationshipName>RVOES</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RVOE</label>
    <nameField>
        <displayFormat>RV-{00000}</displayFormat>
        <label># RVOE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RVOES</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TriggerGrupoHandler.cls
public with sharing class TriggerGrupoHandler extends TriggerHandler {
        private Map<Id, Grupo__c> newMap;
        private Map<Id, Grupo__c> oldMap;
        private List<Grupo__c> newList;
        private List<Grupo__c> oldList;
        
        public TriggerGrupoHandler() {
                this.newMap = (Map<Id, Grupo__c>) trigger.newMap;
                this.oldMap = (Map<Id, Grupo__c>) trigger.oldMap;
                this.newList = (List<Grupo__c>) trigger.new;
                this.oldList = (List<Grupo__c>) trigger.old;
                
        }
    
        //Asignar nomenclatura a grupo autorizado -calvarez
        public override void beforeUpdate() {
            Map<Id, Grupo__c> toUpdate = new Map<Id, Grupo__c>();
            for(Grupo__c grupo: newList){
                if(grupo.Estatus__c == 'Autorizado' && oldMap.get(grupo.Id).Estatus__c != grupo.Estatus__c && String.isBlank(grupo.Nomenclatura__c)){
                    toUpdate.put(grupo.Id, grupo);
                }
                if(grupo.Estatus__c == 'Rechazado') {
                    grupo.Activo__c = 'Inactivo ';
                }
            }
            List<Grupo__c> groups_u = [SELECT Id, Consecutivo__c, Nomenclatura__c, OfertaEducativa__r.RvoeVigente__r.Plan__c, 
                                       OfertaEducativa__r.Plantel__c,
                                       OfertaEducativa__r.Nivel__c,
                                       OfertaEducativa__r.Programa__c FROM Grupo__c WHERE Id IN :toUpdate.keySet()];
            if(groups_u.size() > 0) {
                Map<String, Integer> consecutivo = new Map<String, Integer>();
                for(Grupo__c gr : groups_u) {
                    String key = gr.OfertaEducativa__r.Plantel__c +''+ gr.OfertaEducativa__r.Nivel__c +''+ gr.OfertaEducativa__r.Programa__c;
                    List<sObject> listGr = [SELECT MAX(Consecutivo__c) maxVal FROM Grupo__c 
                                            WHERE OfertaEducativa__r.Plantel__c= :gr.OfertaEducativa__r.Plantel__c 
                                            AND OfertaEducativa__r.Nivel__c= :gr.OfertaEducativa__r.Nivel__c 
                                            AND OfertaEducativa__r.Programa__c= :gr.OfertaEducativa__r.Programa__c
                                           AND Nomenclatura__c != null];
                    if(toUpdate.containsKey(gr.Id)) {
                        Grupo__c grpUpdate = (Grupo__c) toUpdate.get(gr.Id);
                        //System.debug('Plantel__c: '+gr.OfertaEducativa__r.Plantel__c + ' - Nivel__c: ' + gr.OfertaEducativa__r.Nivel__c + ' - Programa__c: ' + gr.OfertaEducativa__r.Programa__c);
                        if(listGr.size() > 0) {
                            sObject sobj= listGr[0];
                            if(sobj.get('maxVal') != null) {
                                
                                Decimal val = ((Decimal)sobj.get('maxVal')) + 1;
                                
                                if(consecutivo.containsKey(key)) {
                                    Integer newVal = ((Integer)consecutivo.get(key)) + ((Integer)val);
                                    consecutivo.put(key, (((Integer)consecutivo.get(key)) + 1));
                                    val = (Decimal) newVal;
                                } else {
                                    consecutivo.put(key, 1);
                                }
                                gr.Consecutivo__c = (Double) val;
                                
                                
                            } else {
                           		if(consecutivo.containsKey(key)) {
                                    Integer newVal = ((Integer)consecutivo.get(key)) + 1;
                                    gr.Consecutivo__c = newVal;
                                    consecutivo.put(key, newVal);
                                } else {
                                    consecutivo.put(key, 1);
                                    gr.Consecutivo__c = 1;
                                } 
                            }
                        } else {
                            if(consecutivo.containsKey(key)) {
                                Integer newVal = ((Integer)consecutivo.get(key)) + 1;
                                gr.Consecutivo__c = newVal;
                                consecutivo.put(key, newVal);
                            } else {
                                consecutivo.put(key, 1);
                           		gr.Consecutivo__c = 1;
                            } 
                        }
                        if(gr.OfertaEducativa__c != null 
                           && gr.OfertaEducativa__r.RvoeVigente__c != null
                           && !String.isBlank(gr.OfertaEducativa__r.RvoeVigente__r.Plan__c)) {   
                               grpUpdate.Consecutivo__c =gr.Consecutivo__c;
                               grpUpdate.Nomenclatura__c = gr.OfertaEducativa__r.RvoeVigente__r.Plan__c + Integer.valueOf(String.valueOf(gr.Consecutivo__c));
                        }
                    }
                }
            }
        }
        
        public override void afterUpdate(){
            updateOpportunities(newList);
        }
        
        public void updateOpportunities(List<Grupo__c> groups){
            set<Id> idGroup = new set<Id>();
            for(Grupo__c grupo: groups){
                if(grupo.Estatus__c == 'Autorizado' && oldMap.get(grupo.Id).Estatus__c != grupo.Estatus__c){
                    idGroup.add(grupo.Id);
                }
            }
            
            
            
            list<Opportunity> opportunities = [SELECT id,Name,StageName FROM Opportunity WHERE Grupo__c IN : idGroup AND  StageName = 'Inscrito'];
            for(Opportunity opportunidad:opportunities){
                opportunidad.StageName = 'Ganada';
            }
            update opportunities;
        }
        
        
    }