src/objects/Grupo__c.object
<CustomObject>
    <fields>
        <fullName>Grupo__c</fullName>
        <label>Grupo</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inscritos__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Inscritos</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ModificadoERP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Modificado ERP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Validados__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Validados</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Grupo</label>
    <nameField>
        <label>Clave</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Folio__c</fullName>
        <displayFormat>C-{000000}</displayFormat>
        <externalId>true</externalId>
        <label>Folio</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Negocio__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuraciones  globales</description>
    <fields>
        <fullName>Folio__c</fullName>
        <description>Número de folio consecutivo para candidatos y prospéctos</description>
        <inlineHelpText>Número de folio consecutivo para candidatos y prospéctos</inlineHelpText>
        <label>Folio</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Negocio</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Folio__c</fullName>
        <label>Folio</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grupo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grupo</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Grupo__c.OfertaEducativa__c</field>
                <operation>equals</operation>
                <valueField>$Source.OfertaEducativa__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Grupo__c</referenceTo>
        <relationshipLabel>Oportunidades</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Validado__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Validado</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TriggerOportunidadHandler.cls
public with sharing class TriggerOportunidadHandler extends TriggerHandler{
    private Map<Id, Opportunity> newMap;
	private Map<Id, Opportunity> oldMap;
	private List<Opportunity> newList;
	private List<Opportunity> oldList;
	
	public TriggerOportunidadHandler() {
			this.newMap = (Map<Id, Opportunity>) trigger.newMap;
			this.oldMap = (Map<Id, Opportunity>) trigger.oldMap;
			this.newList = (List<Opportunity>) trigger.new;
			this.oldList = (List<Opportunity>) trigger.old;
			
	}
	
	
    public override void beforeInsert(){
		assignFolio(newList);
	}
	
	public override void afterUpdate(){
		assignWonOpportinities(newList);
		assignVerifiedOpportinities(newList);
		
	}
    
    public override void beforeUpdate(){
        sendToERP(newList,this.oldMap);
    }
	/**
    * @author:      Rogelio Jimenez
    * @date:        09/06/2016
    * @description: Asigna folio si la oportunidad no viene de un lead
    * @param:       list<Opportunity>
    * @return:      
    */
    
    public void assignFolio(List<Opportunity> opportunities){
        //Para verificar si viene de un lead hay que obtener los lead con idOportunidad
        set<Id> idsOpp = new set<Id>();
    	map<Id,Lead> mapOppLead = new map<Id,Lead>();
    	Negocio__c configuracionNegocio = Negocio__c.getOrgDefaults();
    	Integer nextFolio = configuracionNegocio.Folio__c != null ? Integer.valueOf(configuracionNegocio.Folio__c) : 0;
    	
    	for(Opportunity opp : opportunities){
    		//idsOpp.add(opp.Id);
    		if(!opp.EsConvertido__c){
    			nextFolio = nextFolio + 1;
    			opp.Folio__c = String.valueOf(nextFolio);
    		}
    	}
    	
    	configuracionNegocio.Folio__c = nextFolio;
     	update configuracionNegocio;
    	
    	/*for(Lead lead: [SELECT id,Name,ConvertedOpportunityId,Folio__c FROM Lead WHERE ConvertedOpportunityId IN : idsOpp ]){
    		System.debug(lead);
            if(!mapOppLead.containsKey(lead.ConvertedOpportunityId)){
    			mapOppLead.put(lead.ConvertedOpportunityId, lead);
    		}
    	}
    	
    	for(Opportunity opp : opportunities){
    		nextFolio = nextFolio + 1;
    		opp.Folio__c = String.valueOf(nextFolio);
    		if(!mapOppLead.containsKey(opp.Id)){
    			nextFolio = nextFolio + 1;
    			opp.Folio__c = String.valueOf(nextFolio);
            }else{
                 Lead lead= mapOppLead.get(opp.Id);
                 opp.Folio__c = String.valueOf(lead.Folio__c);
            }
    	}*/
    	
    	
    }
    
    /**
    * @author:      Rogelio Jimenez
    * @date:        17/06/2016
    * @description: Aumenta el valor de Incritos en el grupo cuando una oportuinda es Inscrito o Ganada
    * @param:       list<Opportunity>
    * @return:      
    */   
    public void assignWonOpportinities(List<Opportunity> opportunities){
    	list<Opportunity> opportunitesWon = new list<Opportunity>();
    	set<Id> idGrupos = new set<Id>();
    	map<Id,Grupo__c> mapGrupo = new map<Id,Grupo__c>();
    	
    	for(Opportunity oportunidad : opportunities){
    		if(oldMap.get(oportunidad.Id).StageName != oportunidad.StageName && oldMap.get(oportunidad.Id).StageName != 'Inscrito' && (oportunidad.StageName == 'Ganada' || oportunidad.StageName == 'Inscrito')){
    			opportunitesWon.add(oportunidad);
    			if(oportunidad.Grupo__c != null){
    				idGrupos.add(oportunidad.Grupo__c);
    			}
    		}
    	}
    	
    	mapGrupo = new Map<ID,Grupo__c>([SELECT Id,Inscritos__c FROM Grupo__c WHERE Id IN : idGrupos]);
    	
    	for(Opportunity oportunidad : opportunitesWon){
    		if(mapGrupo.containsKey(oportunidad.Grupo__c)){
    			Decimal inscritosAux = mapGrupo.get(oportunidad.Grupo__c).Inscritos__c != null ? mapGrupo.get(oportunidad.Grupo__c).Inscritos__c : 0;
    			inscritosAux = inscritosAux + 1;
    			mapGrupo.get(oportunidad.Grupo__c).Inscritos__c = inscritosAux;
    		}
    	}
    	if(mapGrupo.values().size() >0){
    		update mapGrupo.values();
    	}
    }
    
    /**
    * @author:      Rogelio Jimenez
    * @date:        17/06/2016
    * @description: Aumenta el valor de Verificados en el grupo cuando una oportuinda es verificada
    * @param:       list<Opportunity>
    * @return:      
    */
     public void assignVerifiedOpportinities(List<Opportunity> opportunities){
    	list<Opportunity> opportunitesVerify = new list<Opportunity>();
    	set<Id> idGrupos = new set<Id>();
    	map<Id,Grupo__c> mapGrupo = new map<Id,Grupo__c>();
    	
    	for(Opportunity oportunidad : opportunities){
    		if(oldMap.get(oportunidad.Id).Validado__c != oportunidad.Validado__c && oportunidad.Validado__c ){
    			opportunitesVerify.add(oportunidad);
    			if(oportunidad.Grupo__c != null){
    				idGrupos.add(oportunidad.Grupo__c);
    			}
    		}
    	}
    	
    	mapGrupo = new Map<ID,Grupo__c>([SELECT Id,Inscritos__c,Validados__c FROM Grupo__c WHERE Id IN : idGrupos]);
    	
    	for(Opportunity oportunidad : opportunitesVerify){
    		if(mapGrupo.containsKey(oportunidad.Grupo__c)){
    			Decimal validadadosAux = mapGrupo.get(oportunidad.Grupo__c).Validados__c != null ? mapGrupo.get(oportunidad.Grupo__c).Validados__c : 0;
    			validadadosAux = validadadosAux + 1;
    			mapGrupo.get(oportunidad.Grupo__c).Validados__c = validadadosAux;
    		}
    	}
    	if(mapGrupo.values().size() >0){
    		update mapGrupo.values();
    	}
    }
    
    /**
    * @author:      Rogelio Jiménez
    * @date:        27/06/2016
    * @description: Verifica el cambio en los campos para poder ser envaidos en Batch del ERP Master
    * @param:       List<Lead> newLeads
    * @return:     
    */
    
    public void sendToERP(list<Opportunity> newLeads,map<Id,Opportunity> oldMap){
    	if(Utils.MAP_OBJECT_FIELDS.containsKey('Opportunity')){
    		for(String field : Utils.MAP_OBJECT_FIELDS.get('Opportunity')){
    			for(Opportunity opp: newLeads){
	    			if(opp.get(field) != oldMap.get(opp.Id).get(field) &&!opp.ModificadoERP__c){
	    				opp.ModificadoERP__c = true;
	    				break;
	    			}
    			}
    		}
    	}
    }
    
}