src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Calle__c</fullName>
        <label>Calle</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Folio__c</fullName>
        <displayFormat>C-{000000}</displayFormat>
        <externalId>true</externalId>
        <label>Folio</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Plantel</description>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Candidatos</relationshipLabel>
        <relationshipName>Plantel</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Promotor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotor</label>
        <referenceTo>Promotor__c</referenceTo>
        <relationshipLabel>Candidatos</relationshipLabel>
        <relationshipName>Candidatos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VigenciaDescuento__c</fullName>
        <label>Vigencia de descuento</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Negocio__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuraciones  globales</description>
    <fields>
        <fullName>Folio__c</fullName>
        <description>Número de folio consecutivo para candidatos y prospéctos</description>
        <inlineHelpText>Número de folio consecutivo para candidatos y prospéctos</inlineHelpText>
        <label>Folio</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Negocio</label>
</CustomObject>

src/objects/Plantel__c.object
<CustomObject>
    <fields>
        <fullName>Calle__c</fullName>
        <label>Calle</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RazonSocial__c</fullName>
        <label>Razón social</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Plantel</label>
    <nameField>
        <label>Plantel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planteles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Promotor__c.object
<CustomObject>
    <fields>
        <fullName>Meta__c</fullName>
        <label>Meta</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OrdenNumerico__c</fullName>
        <label>Orden Numérico</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Promotores</relationshipLabel>
        <relationshipName>Promotores</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Promotor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Promotores</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Promotor</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Clave Promotor</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MailAsignacionPromotorTest.cls
@isTest public class MailAsignacionPromotorTest {
    
    @IsTest  (SeeAllData=true)
    public static void test(){
        
        Negocio__c configuracionNegocio = Negocio__c.getOrgDefaults();
        upsert configuracionNegocio;
        Integer nextFolio = configuracionNegocio.Folio__c != null ? Integer.valueOf(configuracionNegocio.Folio__c) : 0;
        nextFolio = nextFolio + 1;
        date fin = date.today();
        
        Plantel__c plan = new Plantel__c (Calle__c='demo',
                                          RazonSocial__c='demo' 
                                         );
        insert  plan;
        
        /*  Profile perfil = new Profile( Name='demo'
);
insert perfil;



User usuario = new User( Username='dsanchez@ctconsulting.com.mx',
LastName='demo',
Alias='demo',
CommunityNickname='IEUdemo',
TimeZoneSidKey='America/Mexico_City', 
LocaleSidKey='es_MX', 
EmailEncodingKey='ISO-8859-1',
ProfileId=perfil.Id,
LanguageLocaleKey ='es',
Email='dsanchez@ctconsulting.com.mx'
);
insert usuario;
*/
        User usuario = [ select Id,Username,LastName,Alias,CommunityNickname,TimeZoneSidKey,LocaleSidKey,EmailEncodingKey,ProfileId,LanguageLocaleKey,Email from User where Id = :UserInfo.getUserId() ];
        
        Promotor__c promotor = new Promotor__c( 
            Promotor__c=usuario.Id,
            Plantel__c=plan.id,
            OrdenNumerico__c=90,
            Meta__c=3
            
        );
        insert promotor;
        
        
        Lead lead = new  Lead(LastName='demo',
                              Folio__c = String.valueOf(nextFolio),
                              VigenciaDescuento__c=fin,
                              FirstName='demo',
                              Promotor__c=promotor.Id
                             );
        lead.Email='dsanchez@ctconsulting.com.mx';
        insert lead;
        
        
        
        Id leadId =lead.id;
        String mailLead='dsanchez@ctconsulting.com.mx';
        
        MailAsignacionPromotor obj = new MailAsignacionPromotor();
        
        // obj.sendMail(leadId, mailLead);
        try{
            MailAsignacionPromotor.sendMail(leadId, mailLead); 
        }catch(exception e){
            
        }
        
        
   
    
    
}

}