src/objects/Plantel__c.object
<CustomObject>
    <fields>
        <fullName>Calle__c</fullName>
        <label>Calle</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RazonSocial__c</fullName>
        <label>Razón social</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Plantel</label>
    <nameField>
        <label>Plantel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planteles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Promotor__c.object
<CustomObject>
    <fields>
        <fullName>Meta__c</fullName>
        <label>Meta</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OrdenNumerico__c</fullName>
        <label>Orden Numérico</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Plantel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Plantel</label>
        <referenceTo>Plantel__c</referenceTo>
        <relationshipLabel>Promotores</relationshipLabel>
        <relationshipName>Promotores</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Promotor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Promotores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UrlFotoGrande__c</fullName>
        <label>Url foto grande</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Promotor</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Clave Promotor</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SchedulablePromotorTest.cls
@isTest
public class SchedulablePromotorTest {
    
    // CRON expression: media noche marzo 15.
    // se ejecuta despues del   Test.stopTest().
    //CRON_EXP fromato hhmmssddmmyy
    
    public static String CRON_EXP = '0 0 0 15 3 ? 2022';
    
    static testmethod void test() {
        
        list<Promotor__c> promotores= new  list<Promotor__c>();
        
        Plantel__c plan = new Plantel__c (Calle__c='demo',
                                          RazonSocial__c='demo'
                                         );
        insert  plan;
        
        Promotor__c promotor = new Promotor__c( 
            Plantel__c=plan.id,
            OrdenNumerico__c=9,
            Meta__c=9,
            UrlFotoGrande__c  ='https://cs2.salesforce.com/img/userprofile/default_profile_200.png?fromEmail=1'
        );
        insert promotor;
        
        Test.startTest();
        
        // programamos el  test job
        String jobId = System.schedule('ScheduleApexClassTest',
                                       CRON_EXP,
                                       new SchedulablePromotor());
        
        // obtenemos la informacion de CronTrigger API object
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered,
                          NextFireTime
                          FROM CronTrigger WHERE id = :jobId];
        
        // validamos que la expresión sea la misma
        System.assertEquals(CRON_EXP,  ct.CronExpression);
        
        // validamos que el job aún no se haya ejecutado
        System.assertEquals(0, ct.TimesTriggered);
        
        // validamos la proxima vez que se ejecutara el job
        System.assertEquals('2022-03-15 00:00:00',String.valueOf(ct.NextFireTime));
        
        // validamos que el job aún no se haya ejecutado
        System.assertEquals(promotores.size(),0);
        Test.stopTest();
        // en este momento de debe de ejecutar el job jespués de Test.stopTest(),
        
        promotores=[SELECT Id FROM Promotor__c  ];
        
        //validamos que se haya ejecutado correctamente el job      
        System.assertEquals(promotores.size(), 1);
        
    }
}